// ─── COMPLETED BUILDS ────────────────────────────────────────────────────────
// Each entry is a fully configured, ready-to-download build.
// frameObj = primary object used in FRAME (outline) mode.
// fillObj  = primary object used in FILL (solid) mode.
// extraFrame / extraFill = comma-sep extras stacked on each point (optional).
// posX/Y/Z = pre-set world coordinates (flat ground at NWAF or Krasnoe).
// ─────────────────────────────────────────────────────────────────────────────

export interface CompletedBuild {
  id: string;
  category: string;
  icon: string;
  name: string;
  tagline: string;
  // Shape generation
  shape: string;
  params: Record<string, number>;
  // Object selection
  frameObj: string;
  fillObj: string;
  extraFrame?: string;
  extraFill?: string;
  // Auto-orient outward (good for rings, forts, walls)
  autoOrient?: boolean;
  // World position — NWAF or Krasnoe flat tarmac
  posX: number;
  posY: number;
  posZ: number;
  // Why these objects were chosen
  objectNotes: string;
  // suggested fill density (1=sparse 4=dense)
  fillDensity?: number;
  // Pre-computed object counts (frame pts / fill pts estimate)
  frameCount?: number;
  fillCount?: number;
}

// NWAF (Northwest Airfield, Chernarus) — long flat tarmac runway
const NWAF = { posX: 4630, posY: 135, posZ: 10490 };
// Krasnoe Airfield (SE coast) — wide flat apron area
const KRASN = { posX: 11950, posY: 148, posZ: 12540 };

export const COMPLETED_BUILDS: CompletedBuild[] = [

  // ─── 🚀 Sci-Fi & Space ─────────────────────────────────────────────────────
  {
    id: "death_star",
    category: "🚀 Sci-Fi",
    icon: "☄️",
    name: "Death Star",
    tagline: "Full sphere with dish trench. Hovers at 40m over the runway.",
    shape: "deathstar",
    params: { radius: 40, latSegs: 10, lonSegs: 16, dishRadius: 12, dishDepth: 6 },
    frameObj: "Land_GasTank_Cylindrical",
    fillObj: "Barrel_Blue",
    ...NWAF, posY: 175,
    objectNotes: "Gas tanks trace the spherical rings; barrels give a dense blue metallic fill.",
  },
  {
    id: "halo_ring",
    category: "🚀 Sci-Fi",
    icon: "💫",
    name: "Halo Ring",
    tagline: "Massive torus floating over the airfield — 120m across.",
    shape: "torus",
    params: { majorR: 60, minorR: 5, majorSegs: 36, minorSegs: 6 },
    frameObj: "StaticObj_Rail_Platform_Segment",
    fillObj: "Land_Concrete_01_F_10x10_DE",
    autoOrient: true,
    ...NWAF, posY: 160,
    objectNotes: "Rail platform segments curve naturally around the ring; concrete slabs thicken the band.",
  },
  {
    id: "borg_cube",
    category: "🚀 Sci-Fi",
    icon: "🟩",
    name: "Borg Cube",
    tagline: "40×40×40m wireframe cube. Shipping containers are peak Borg aesthetic.",
    shape: "borg_cube",
    params: { size: 40, gridLines: 4 },
    frameObj: "StaticObj_Container_1D",
    fillObj: "StaticObj_Container_1C",
    ...NWAF,
    objectNotes: "Industrial shipping containers on every face grid — perfect Borg collective architecture.",
  },
  {
    id: "orbital_station",
    category: "🚀 Sci-Fi",
    icon: "🛸",
    name: "Orbital Station",
    tagline: "Ring + spokes space station silhouette, hovering high.",
    shape: "orbital_station",
    params: { radius: 40, height: 12, ringSegs: 24, spokes: 6 },
    frameObj: "Land_Tank_SmallConcrete_Round",
    fillObj: "Land_GasTank_Cylindrical",
    ...NWAF, posY: 165,
    objectNotes: "Concrete round tanks trace the ring; gas tanks fill the curved station body.",
  },
  {
    id: "millennium_falcon",
    category: "🚀 Sci-Fi",
    icon: "🚀",
    name: "Millennium Falcon",
    tagline: "Saucer with mandibles and cockpit offset — iconic silhouette.",
    shape: "millennium_falcon",
    params: { radius: 25, height: 6, mandibleLen: 14, cockpitOffset: 10 },
    frameObj: "Land_GasTank_Cylindrical",
    fillObj: "Barrel_Green",
    ...NWAF,
    objectNotes: "Gas tanks frame the hull rings; green barrels fill the disc — distinct ship silhouette.",
  },
  {
    id: "black_hole",
    category: "🚀 Sci-Fi",
    icon: "🌀",
    name: "Black Hole",
    tagline: "Spiral arms radiating from a dense core — eerie gravitational art.",
    shape: "black_hole",
    params: { radius: 35, arms: 5, turns: 2 },
    frameObj: "Land_TankTrap_DE",
    fillObj: "Land_BarbedWire_01_DE",
    ...NWAF,
    objectNotes: "Czech hedgehog tank traps spiral outward; barbed wire fills the accretion disc arms.",
  },
  {
    id: "crashed_ufo",
    category: "🚀 Sci-Fi",
    icon: "💥",
    name: "Crashed UFO",
    tagline: "Tilted saucer disc half-buried in the airfield. Alien crash site.",
    shape: "crashed_ufo",
    params: { radius: 25, tilt: 28, rings: 6 },
    frameObj: "Land_GasTank_Cylindrical",
    fillObj: "Barrel_Green",
    extraFrame: "Barrel_Yellow",
    ...KRASN,
    objectNotes: "Gas cylinders trace the crashed disc edge; green + yellow barrels imply bio-contamination.",
  },

  // ─── 🎬 Movies & TV ─────────────────────────────────────────────────────────
  {
    id: "eye_of_sauron",
    category: "🎬 Movies",
    icon: "👁️",
    name: "Eye of Sauron",
    tagline: "Barad-dûr spire + fiery oval eye. 90m tall. Takes Mordor to DayZ.",
    shape: "eye_of_sauron",
    params: { height: 90, towerWidth: 28, eyeRadius: 22 },
    frameObj: "Land_PowerLine_Tower_DE",
    fillObj: "Land_RadioTower_1_DE",
    extraFrame: "Land_BarbedWire_01_DE",
    ...NWAF,
    objectNotes: "Power line towers trace the dark spire; radio towers fill the frame with a sinister silhouette. Barbed wire adds the spike detail.",
  },
  {
    id: "minas_tirith",
    category: "🎬 Movies",
    icon: "🏰",
    name: "Minas Tirith",
    tagline: "Multi-tower citadel rings. 7 towers, 90m tall — Gondor's capital.",
    shape: "azkaban_tower",
    params: { baseRadius: 35, height: 90, towerCount: 7 },
    frameObj: "StaticObj_Monument_Wall",
    fillObj: "Land_Wall_Concrete_4m_DE",
    extraFrame: "Land_Wall_Brick_8m_DE",
    ...KRASN,
    objectNotes: "Monument walls trace the iconic white-stone tower rings; brick+concrete walls fill the citadel body.",
  },
  {
    id: "atat_walker",
    category: "🎬 Movies",
    icon: "🐘",
    name: "AT-AT Walker",
    tagline: "4-legged walker: elevated box body, neck, boxy head, twin cannons.",
    shape: "atat_walker",
    params: { height: 30, width: 20 },
    frameObj: "Land_Wreck_BTR_DE",
    fillObj: "StaticObj_Container_1D",
    extraFrame: "Land_BarrierConcrete_01_DE",
    ...NWAF,
    objectNotes: "BTR wreck chunks trace the leg/body structure; containers fill the boxy hull; concrete barriers add the armour plate detail.",
  },
  {
    id: "t800",
    category: "🎬 Movies",
    icon: "💀",
    name: "T-800 Endoskeleton",
    tagline: "Skull cage, ribcage, spine, limbs. 22m tall chrome nightmare.",
    shape: "t800_endoskeleton",
    params: { height: 22, width: 10 },
    frameObj: "Land_TankTrap_DE",
    fillObj: "Barrel_Blue",
    extraFrame: "Land_BarbedWire_01_DE",
    ...NWAF,
    objectNotes: "Czech hedgehog traps read as the angular skeleton joints; barbed wire laces through the ribcage. Blue barrels give a metallic chrome fill.",
  },
  {
    id: "mordor_gate",
    category: "🎬 Movies",
    icon: "🌋",
    name: "Black Gate of Mordor",
    tagline: "Massive arch gate with flanking towers. 60m tall.",
    shape: "sci_fi_gate",
    params: { width: 80, height: 60 },
    frameObj: "Land_Wall_Concrete_8m_DE",
    fillObj: "Land_Wall_Brick_8m_DE",
    extraFrame: "Land_BarrierConcrete_02_DE",
    ...KRASN,
    objectNotes: "Concrete 8m walls form the dark tower flanks; concrete barriers detail the arch. Very imposing gate structure.",
  },
  {
    id: "star_destroyer",
    category: "🎬 Movies",
    icon: "🔺",
    name: "Star Destroyer",
    tagline: "Stepped pyramid wedge — the profile of an Imperial Star Destroyer.",
    shape: "pyramid_stepped",
    params: { size: 60, height: 20, steps: 5 },
    frameObj: "StaticObj_Container_1D",
    fillObj: "Land_BarrierConcrete_01_DE",
    ...NWAF,
    objectNotes: "Shipping containers define the wedge silhouette; concrete barriers fill the stepped decks.",
  },

  // ─── 🏛 Monuments ─────────────────────────────────────────────────────────
  {
    id: "stonehenge",
    category: "🏛 Monuments",
    icon: "🪨",
    name: "Stonehenge",
    tagline: "Standing stone circle with trilithon lintels. Built from rock monoliths.",
    shape: "stonehenge",
    params: { radius: 18, stones: 12, stoneH: 8, lintels: 6, innerRadius: 10 },
    frameObj: "DZ\\rocks_bliss\\rock_monolith1.p3d",
    fillObj: "DZ\\rocks_bliss\\stone9_moss.p3d",
    ...NWAF,
    objectNotes: "Rock monoliths ARE the standing stones — couldn't be more fitting. Mossy stones fill between the megaliths.",
  },
  {
    id: "colosseum",
    category: "🏛 Monuments",
    icon: "🏟️",
    name: "Colosseum",
    tagline: "Elliptical arena with 3 tiers, arch columns, and arena floor.",
    shape: "colosseum",
    params: { radius: 35, height: 24, tiers: 3, arches: 20 },
    frameObj: "Land_Wall_Concrete_4m_DE",
    fillObj: "Land_BarrierConcrete_01_DE",
    extraFrame: "Land_Wall_Brick_4m_DE",
    autoOrient: true,
    ...KRASN,
    objectNotes: "Concrete 4m walls trace the tiered arches; brick walls add texture between tiers; barriers fill the seating bowl.",
  },
  {
    id: "celtic_ring",
    category: "🏛 Monuments",
    icon: "⭕",
    name: "Celtic Stone Ring",
    tagline: "Double-ring megalith circle with inner altar stones.",
    shape: "celtic_ring",
    params: { outerR: 25, innerR: 18, stones: 16, lintels: 8 },
    frameObj: "DZ\\rocks_bliss\\rock_monolith1.p3d",
    fillObj: "DZ\\rocks_bliss\\stone9_moss.p3d",
    extraFill: "DZ\\rocks_bliss\\clutter_01.p3d",
    ...NWAF,
    objectNotes: "Monolith rocks form the outer standing stones; mossy stones and rock clutter fill the inner sacred ground.",
  },
  {
    id: "pyramid_aztec",
    category: "🏛 Monuments",
    icon: "🔺",
    name: "Aztec Pyramid",
    tagline: "5-step pyramid — 60m wide, 30m tall. Flat top for sacrificial altar.",
    shape: "pyramid_stepped",
    params: { size: 60, height: 30, steps: 5 },
    frameObj: "Land_Wall_Concrete_8m_DE",
    fillObj: "Land_ConcreteSlab_03_DE",
    extraFrame: "Land_BarrierConcrete_01_DE",
    autoOrient: true,
    ...NWAF,
    objectNotes: "8m concrete walls define each step tier; large concrete slabs fill the step faces; barriers add the decorative detail.",
  },

  // ─── 💀 Dark & Horror ──────────────────────────────────────────────────────
  {
    id: "giant_skull",
    category: "💀 Dark",
    icon: "💀",
    name: "Giant Skull",
    tagline: "18m radius skull with eye sockets and jaw. Horrifying base marker.",
    shape: "body_skull",
    params: { radius: 18, eyeSocket: 5, jawDrop: 8 },
    frameObj: "DZ\\rocks_bliss\\rock_spike1.p3d",
    fillObj: "Barrel_Red",
    ...KRASN,
    objectNotes: "Rock spikes form the jagged skull bone structure; red barrels fill the skull with a bloody interior.",
  },
  {
    id: "volcano",
    category: "💀 Dark",
    icon: "🌋",
    name: "Volcano",
    tagline: "Mt. Fuji profile — wide base, curved sides, open jagged crater. 50m base.",
    shape: "volcano",
    params: { baseRadius: 50, height: 32, craterRadius: 10, rimHeight: 4, rings: 10, spacing: 6 },
    frameObj: "DZ\\rocks_bliss\\rock_monolith2.p3d",
    fillObj: "DZ\\rocks_bliss\\stone9_moss.p3d",
    extraFill: "DZ\\rocks_bliss\\clutter_01.p3d",
    ...KRASN,
    objectNotes: "Rock monoliths outline the volcanic cone ridges and lava flows; mossy stones and clutter fill the mountain body.",
  },
  {
    id: "mushroom_cloud",
    category: "💀 Dark",
    icon: "☢️",
    name: "Mushroom Cloud",
    tagline: "Nuclear explosion silhouette. Yellow barrels = radiological hazard.",
    shape: "mushroom_cloud",
    params: { radius: 40, height: 80 },
    frameObj: "Barrel_Yellow",
    fillObj: "Land_GasTank_Big",
    extraFrame: "Barrel_Red",
    ...NWAF, posY: 135,
    objectNotes: "Yellow hazmat barrels trace the cloud outline; big gas tanks fill the stem and cap. Red barrels accent the fireball base.",
  },

  // ─── 🤖 Mechs ─────────────────────────────────────────────────────────────
  {
    id: "mech_bipedal",
    category: "🤖 Mechs",
    icon: "🤖",
    name: "Mech Warrior",
    tagline: "Bipedal mech — cockpit, torso, arms, legs. 25m tall war machine.",
    shape: "mech_bipedal",
    params: { height: 25, width: 14 },
    frameObj: "Land_Wreck_BTR_DE",
    fillObj: "StaticObj_Container_1D",
    extraFrame: "Land_Wreck_T72_DE",
    ...NWAF,
    objectNotes: "BTR wreck chunks form the armour plates; T72 wreck pieces add heavy tank-grade armour to the mech joints. Containers fill the torso.",
  },
  {
    id: "spider_walker",
    category: "🤖 Mechs",
    icon: "🕷️",
    name: "Spider Walker",
    tagline: "6-legged arachnid mech. Alien/Zerg aesthetic. 18m tall body.",
    shape: "mech_walker",
    params: { radius: 12, height: 18, legs: 6 },
    frameObj: "Land_Wreck_BTR_DE",
    fillObj: "Land_TankTrap_DE",
    extraFrame: "Land_BarbedWire_01_DE",
    ...NWAF,
    objectNotes: "BTR wrecks mark the leg joints and body rings; hedgehogs fill with a spiky mechanical look; barbed wire adds leg-spine detail.",
  },

  // ─── 🏰 Military & Bases ───────────────────────────────────────────────────
  {
    id: "star_fort",
    category: "🏰 Bases",
    icon: "⭐",
    name: "Star Fort",
    tagline: "6-pointed star bastion — DayZ's most defensible ground base shape.",
    shape: "star_fort",
    params: { radius: 40, points: 6, height: 8, wallThick: 3 },
    frameObj: "Land_HBarrier_5m_DE",
    fillObj: "Land_Sandbag_Wall_DE",
    extraFrame: "Land_BarbedWire_01_DE",
    autoOrient: true,
    ...KRASN,
    objectNotes: "HESCO 5m barriers form the star-fort walls and bastions; sandbag walls fill the ramparts; barbed wire crowns the parapets.",
  },
  {
    id: "prison_tower",
    category: "🏰 Bases",
    icon: "🗼",
    name: "Prison Tower",
    tagline: "5-floor circular tower with walkway ring per floor. 30m tall.",
    shape: "prison_tower",
    params: { radius: 12, height: 30, floors: 5, corridorDepth: 3 },
    frameObj: "Land_Mil_WatchtowerH_DE",
    fillObj: "Land_Bunker_DE",
    extraFrame: "Land_Wall_Concrete_4m_DE",
    autoOrient: true,
    ...KRASN,
    objectNotes: "Tall military watchtowers ring each floor; concrete 4m walls fill between towers; bunkers at ground level anchor the structure.",
  },

  // ─── ⚡ Lightweight Builds — server-friendly, handcrafted originals ──────────
  // All positioned at Krasnoe Airfield · Low object count · Console safe

  {
    id: "lw_treehouse",
    category: "⚡ Lightweight",
    icon: "🌲",
    name: "Birch Treehouse",
    tagline: "Four birch trees grow through a raised platform cabin with an A-frame roof. 22 objects.",
    shape: "treehouse",
    params: { size: 8, platformH: 6, wallH: 3 },
    frameObj: "DZ\\plants_bliss\\tree\\t_betulapendula_2f_summer.p3d",
    fillObj: "Pallet_EP1",
    ...KRASN, posX: 11900, posZ: 12490,
    frameCount: 22, fillCount: 22,
    objectNotes: "Frame mode: 22 birch trees — 12 form the four structural trunks rising from ground, 4 mark the platform edges, 4 define the wall corners, 2 ridge the roofline. Fill mode swaps to wooden pallets for a solid timber-platform look. Drop it in a forest clearing for peak immersion.",
  },
  {
    id: "lw_checkpoint",
    category: "⚡ Lightweight",
    icon: "🚧",
    name: "Military Checkpoint",
    tagline: "Staggered concrete barriers, flanking sandbag nests, rear watchtowers. 9 objects.",
    shape: "checkpoint",
    params: { width: 12, depth: 8 },
    frameObj: "Land_BarrierConcrete_01_DE",
    fillObj: "Land_Sandbag_Corner_DE",
    ...KRASN, posX: 11970, posZ: 12610,
    frameCount: 9, fillCount: 9,
    objectNotes: "9 concrete barriers arranged in a classic zigzag — vehicles must slow to navigate. Two flanking positions for shooters, two rear watchtower slots. Fill mode converts to sandbag corners for a softer, entrenched look. Ultra-lightweight: 9 objects total.",
  },
  {
    id: "lw_watchtower_triangle",
    category: "⚡ Lightweight",
    icon: "🔭",
    name: "Watchtower Triangle",
    tagline: "Three watchtowers at equilateral triangle vertices with sandbag walls and a fire centre. 7 objects.",
    shape: "watchtower_post",
    params: { radius: 12 },
    frameObj: "Land_Mil_WatchtowerH_DE",
    fillObj: "Land_Sandbag_Wall_DE",
    ...KRASN, posX: 12010, posZ: 12480,
    frameCount: 7, fillCount: 7,
    objectNotes: "Three tall military watchtowers form an equilateral triangle — any approach is covered by at least two towers. Three sandbag wall midpoints seal the gaps. One central object marks the command post or fire pit. Just 7 objects — negligible server load, maximum threat.",
  },
  {
    id: "lw_fuel_depot",
    category: "⚡ Lightweight",
    icon: "⛽",
    name: "Fuel Depot",
    tagline: "Two big storage tanks, two cylindrical pumps, a zigzag barrier approach, and flanking guards. 10 objects.",
    shape: "fuel_depot",
    params: { size: 10 },
    frameObj: "Land_GasTank_Big",
    fillObj: "Land_GasTank_Cylindrical",
    ...KRASN, posX: 11930, posZ: 12580,
    frameCount: 10, fillCount: 10,
    objectNotes: "Frame: 2 big gas tanks + 2 cylindrical pump tanks behind the canopy, with 3 staggered concrete barriers defending the approach and 2 guard positions on the flanks — 10 objects total. Fill mode swaps everything to cylindrical tanks for a tighter industrial look.",
  },
  {
    id: "lw_sniper_nest",
    category: "⚡ Lightweight",
    icon: "🪨",
    name: "Sniper's Rock Nest",
    tagline: "Irregular pentagon of boulders at ground level with two elevated firing rocks and a concealed approach. 8 objects.",
    shape: "sniper_nest",
    params: { radius: 4, height: 3 },
    frameObj: "DZ\\rocks_bliss\\rock_monolith1.p3d",
    fillObj: "DZ\\rocks_bliss\\rock_spike1.p3d",
    ...KRASN, posX: 12050, posZ: 12540,
    frameCount: 8, fillCount: 8,
    objectNotes: "5 large rock monoliths form an irregular base pentagon — varied radius breaks the man-made pattern. 2 elevated monoliths at 3m height give the sniper a raised firing platform. 1 rear rock marks the concealed exit route. Fill mode uses jagged rock spikes for a more dramatic, hostile look.",
  },
  {
    id: "lw_farmstead",
    category: "⚡ Lightweight",
    icon: "🏡",
    name: "Rural Farmstead",
    tagline: "House footprint, barn, silo, well, and a fence-post perimeter. 16 objects.",
    shape: "farmstead",
    params: { size: 14 },
    frameObj: "Land_Wall_Brick_4m_DE",
    fillObj: "Land_Wall_Concrete_4m_DE",
    ...KRASN, posX: 11880, posZ: 12520,
    frameCount: 16, fillCount: 16,
    objectNotes: "4 brick walls define the house corners. 4 larger walls define the barn (offset to the right). 1 silo position, 1 well, and 6 perimeter fence-post walls round out the compound at 16 objects. Fill mode hardens everything to concrete — now it's a fortified homestead rather than a farm.",
  },
  {
    id: "lw_survivor_camp",
    category: "⚡ Lightweight",
    icon: "🔥",
    name: "Survivor's Camp",
    tagline: "Central fireplace, four tent positions (N/E/S/W), a supply cache corner, and two lookout posts. 10 objects.",
    shape: "survivor_camp",
    params: { radius: 6 },
    frameObj: "Land_Mil_Tent_Small_DE",
    fillObj: "Barrel_Blue",
    ...KRASN, posX: 11960, posZ: 12510,
    frameCount: 10, fillCount: 10,
    objectNotes: "10 objects. Frame: small military tents at all 10 positions — one at centre as the community tent, four around it, a cluster of three supply tents, two perimeter lookouts. Fill: replaces tents with blue barrels to show the supply cache layout. The fire in the middle is implied by the central object.",
  },
  {
    id: "lw_bunker_line",
    category: "⚡ Lightweight",
    icon: "🪖",
    name: "Bunker Defence Line",
    tagline: "Two parallel sandbag walls forming a covered approach channel, with a command bunker and two flanking positions. 11 objects.",
    shape: "bunker_line",
    params: { length: 20, width: 6 },
    frameObj: "Land_Sandbag_Wall_DE",
    fillObj: "Land_Bunker_DE",
    ...KRASN, posX: 12000, posZ: 12560,
    frameCount: 11, fillCount: 11,
    objectNotes: "4+4 sandbag wall sections create a parallel-channel approach — infantry can advance under cover. 1 central command bunker anchors the far end. 2 flanking concrete bunkers extend the defensive line. 11 objects total. Fill mode replaces sandbag walls with concrete bunkers for a hardened fortress look.",
  },
  {
    id: "lw_power_relay",
    category: "⚡ Lightweight",
    icon: "⚡",
    name: "Power Relay Station",
    tagline: "Three power-line towers in a row, two storage tanks, three distribution substations. 8 objects.",
    shape: "power_relay",
    params: { spacing: 12 },
    frameObj: "Land_PowerLine_Tower_DE",
    fillObj: "Land_Tank_SmallConcrete_Round",
    ...KRASN, posX: 11920, posZ: 12560,
    frameCount: 8, fillCount: 8,
    objectNotes: "Three tall power-line towers march in a row — instantly recognisable as an electrical relay station or transmission line. Two concrete tanks sit behind (fuel or transformer housings). Three small substation boxes face the front. Just 8 objects. Fill swaps towers for concrete tanks — a pure industrial tank farm.",
  },
  {
    id: "lw_radio_outpost",
    category: "⚡ Lightweight",
    icon: "📡",
    name: "Radio Outpost",
    tagline: "Central radio mast with three guy-wire anchor points and two instrument sheds. 6 objects — absolute minimum footprint.",
    shape: "radio_outpost",
    params: { radius: 8 },
    frameObj: "Land_RadioTower_1_DE",
    fillObj: "Land_Mil_Tent_Small_DE",
    ...KRASN, posX: 12030, posZ: 12500,
    frameCount: 6, fillCount: 6,
    objectNotes: "The lightest build in the collection at just 6 objects. One radio tower stands central. Three towers mark the 120° guy-wire anchor triangle around it. Two smaller towers represent instrument sheds or relay boxes. Fill switches to military tents — operational camp around the mast.",
  },
  {
    id: "lw_guard_post",
    category: "⚡ Lightweight",
    icon: "🛡️",
    name: "Guard Post",
    tagline: "Compact road-side guard post: narrow zigzag, two sandbag nests, rear towers. 9 objects. Fits a single road lane.",
    shape: "checkpoint",
    params: { width: 6, depth: 5 },
    frameObj: "Land_Sandbag_Round_DE",
    fillObj: "Land_Mil_Guardhouse_DE",
    ...KRASN, posX: 11890, posZ: 12550,
    frameCount: 9, fillCount: 9,
    objectNotes: "Same generator as the full checkpoint but scaled down to width:6/depth:5 — now it fits a single road lane or server entrance. Frame uses rounded sandbag positions for a casual, organic-looking post. Fill mode places guardhouses at all 9 points for a proper staffed checkpoint feel.",
  },
  {
    id: "lw_tank_trap_line",
    category: "⚡ Lightweight",
    icon: "🦔",
    name: "Tank Trap Line",
    tagline: "Anti-armour barrier line: Czech hedgehogs on the flanks, HESCO barriers down the channel, command bunker at the end. 11 objects.",
    shape: "bunker_line",
    params: { length: 15, width: 4 },
    frameObj: "Land_TankTrap_DE",
    fillObj: "Land_HBarrier_5m_DE",
    ...KRASN, posX: 11950, posZ: 12470,
    frameCount: 11, fillCount: 11,
    objectNotes: "Czech hedgehog tank traps line both walls — any vehicle pushing through will be channelled and slowed. 1 command bunker anchors the far end. 2 HESCO barrier flankers provide infantry cover. Fill swaps hedgehogs for 5m HESCO barriers — a hardened vehicle lane or server gate. 11 objects.",
  },

  // ─── 🤖 Transformers — Movie-accurate Cybertronian mechs ─────────────────
  {
    id: "tf_bumblebee",
    category: "🤖 Transformers",
    icon: "🟡",
    name: "Bumblebee",
    tagline: "Chevy Camaro Autobot. Compact & fearless. 12m tall. 140 yellow barrels in full humanoid mech form — door wings, shoulder wheel arches, visor helm.",
    shape: "tf_bumblebee",
    params: { scale: 1 },
    frameObj: "Barrel_Yellow",
    fillObj: "Barrel_Yellow",
    extraFrame: "ArmBandYellow",
    ...NWAF, posX: 4630, posZ: 10490,
    objectNotes: "Pure yellow barrel army — every point is a Barrel_Yellow, giving that iconic Bumblebee colour. Door wing panels, Camaro shoulder wheel arches, hood chest plate stripe, and twin antennae are all explicitly shaped in the point cloud. Frame mode traces the clean robot silhouette; Fill packs density into the whole mech. Add ArmBandYellow at each point for finer interior detail on console.",
  },
  {
    id: "tf_optimus",
    category: "🤖 Transformers",
    icon: "🔴",
    name: "Optimus Prime",
    tagline: "Peterbilt 379 Autobot Commander. 16m tall — tallest mech in the roster. Truck grille chest, smoke stacks, iconic bucket helmet.",
    shape: "tf_optimus",
    params: { scale: 1 },
    frameObj: "StaticObj_Container_1D",
    fillObj: "StaticObj_Container_1C",
    extraFrame: "Land_Wreck_V3S_DE",
    ...NWAF, posX: 4760, posZ: 10490,
    objectNotes: "Shipping Container 1D (red/grey) traces the hulking frame — the enormous chest grille, broad shoulders, and smoke stacks are all point-perfect. Container 1C fills the interior with mass. The truck bumper row at the feet and fuel tank cylinders at the hips nail the semi-truck transformation aesthetic. Frame this at NWAF runway for maximum cinematic impact.",
  },
  {
    id: "tf_ironhide",
    category: "🤖 Transformers",
    icon: "⚫",
    name: "Ironhide",
    tagline: "GMC Topkick off-road weapons specialist. Bulkiest Autobot. Dual forearm Vulcan cannons, armoured thighs, wheel-well shins.",
    shape: "tf_ironhide",
    params: { scale: 1 },
    frameObj: "Land_Container_1Bo_DE",
    fillObj: "Land_Wreck_BTR_DE",
    extraFrame: "Land_TankTrap_DE",
    ...NWAF, posX: 4500, posZ: 10490,
    objectNotes: "Dark Container 1Bo gives Ironhide his black military look — the widest chest on the roster (6m). BTR wreck pieces fill the interior with heavy armour-plate mass. Czech hedgehog tank traps at the dual cannon muzzles punch out perfectly from the forearm. Armour-plate overlays on thighs and wheel wells are all individually placed point clusters.",
  },
  {
    id: "tf_jazz",
    category: "🤖 Transformers",
    icon: "⚪",
    name: "Jazz",
    tagline: "Pontiac Solstice Autobot. Slender & fast — smallest adult Autobot. Racing stripe chest, rear spoiler, athletic proportions.",
    shape: "tf_jazz",
    params: { scale: 1 },
    frameObj: "StaticObj_Container_1C",
    fillObj: "Land_Wreck_sed01_aban1_black_DE",
    extraFrame: "Land_BarrierConcrete_01_DE",
    ...NWAF, posX: 4630, posZ: 10360,
    objectNotes: "Silver Container 1C traces Jazz's sleek, athletic silhouette — the narrowest chest (4.2m) with a distinctive Solstice racing stripe across the sternum. Sedan wreck pieces fill the interior with sporty urban debris. The rear spoiler is its own point cluster arching over the back. Concrete barriers add detail to the ankle spoiler extensions. Built for speed, this is your eye-candy centrepiece.",
  },
  {
    id: "tf_ratchet",
    category: "🤖 Transformers",
    icon: "🟢",
    name: "Ratchet",
    tagline: "Hummer H2 Autobot medic. Square-jawed rescue mech. Roof-rack sensor array, medical cross, heavy shoulder pad sections.",
    shape: "tf_ratchet",
    params: { scale: 1 },
    frameObj: "Land_HBarrier_5m_DE",
    fillObj: "Land_HBarrier_10m_DE",
    extraFrame: "Land_Wreck_offroad02_aban1_DE",
    ...NWAF, posX: 4890, posZ: 10490,
    objectNotes: "HESCO 5m barriers trace Ratchet's boxy, blocky frame — the Hummer H2 roofline turned into armoured shoulder sections looming over a wide medical-cross chest. HESCO 10m barriers fill the interior with mass and depth. Offroad wreck pieces at the roof-rack sensor array add the perfect Ratchet rescue-vehicle detail. A wide, reassuring silhouette that dominates any spawn zone.",
  },
  {
    id: "tf_megatron",
    category: "🤖 Transformers",
    icon: "🩶",
    name: "Megatron",
    tagline: "Cybertronian jet / tank Decepticon leader. 15m tall alien mech. Massive right-arm fusion cannon, alien angular head, jet-stub wings on back.",
    shape: "tf_megatron",
    params: { scale: 1 },
    frameObj: "Land_TankTrap_DE",
    fillObj: "Land_Wreck_T72_DE",
    extraFrame: "Land_Wreck_BTR_DE",
    ...NWAF, posX: 4370, posZ: 10490,
    objectNotes: "Czech hedgehog tank traps trace Megatron's spiky, alien-armoured silhouette — angular chest spines, the enormous fusion cannon housing off the right shoulder, and lateral face-spikes on the alien head are all point-perfect. T72 tank wrecks fill the interior with heavy armour. BTR APC wrecks mark the fusion cannon muzzle ring. A menacing enemy centrepiece — face him against your Optimus Prime.",
  },
  {
    id: "tf_starscream",
    category: "🤖 Transformers",
    icon: "🩵",
    name: "Starscream",
    tagline: "F-22 Raptor Decepticon air commander. Lean body, massive swept delta wings (6m each), jet cockpit chest, vertical tail fins, missile pods.",
    shape: "tf_starscream",
    params: { scale: 1 },
    frameObj: "Land_BarrierConcrete_01_DE",
    fillObj: "Land_Wreck_heli_MI8_DE",
    extraFrame: "Land_BarrierConcrete_02_DE",
    ...NWAF, posX: 4630, posZ: 10230,
    objectNotes: "Concrete barriers trace Starscream's lean grey-blue frame — the swept F-22 delta wings dominate at 6m per side, the jet cockpit nose protrudes from the chest, and vertical tail fins rise from the shoulders. MI-8 helicopter wreck pieces fill the interior with aviation mass. Leg-mounted missile pods and seeker-jet crown ridge complete the treacherous air-commander look. Place him on the NWAF runway with wings spread for maximum impact.",
  },
];
