// ─── COMPLETED BUILDS ────────────────────────────────────────────────────────
// Coordinates calibrated for real Chernarus+ map locations (Section 15, Fix 4).
// ─────────────────────────────────────────────────────────────────────────────

export interface CompletedBuild {
  id: string; category: string; icon: string; name: string; tagline: string; shape: string; 
  params: Record<string, number>; frameObj: string; fillObj: string; extraFrame?: string; extraFill?: string;
  autoOrient?: boolean; posX: number; posY: number; posZ: number; objectNotes: string; interiorType: "open" | "structure"; lootTheme: string;
  frameCount?: number; fillCount?: number;
  objects_final?: any[];
}

const NWAF  = { posX: 4050,  posY: 400, posZ: 10450 }; // NWAF elevated ~400m
const KRASN = { posX: 11950, posY: 142, posZ: 12500 }; // Krasno ~142m
const BALOTA = { posX: 8220, posY: 470, posZ: 9010  }; // Balota airfield ~470m
const STARY  = { posX: 5800, posY: 470, posZ: 8200  }; // Stary Sobor ~470m
const TISY   = { posX: 600,  posY: 503, posZ: 13690 }; // Tisy Military ~503m
const UNDERGROUND = { posY: 3.0 }; // Real subterranean floor for bunkers

export const COMPLETED_BUILDS: CompletedBuild[] = [
  // --- MONUMENTS (20) ---
  { id: "eiffel_tower", category: "Monuments", icon: "🗼", name: "Eiffel Tower", tagline: "Parisian lattice masterpiece.", shape: "eiffel_tower", params: { width: 60, height: 120 }, frameObj: "staticobj_misc_timbers_log4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Lattice structure.", interiorType: "open", lootTheme: "Military" },
  { id: "colosseum", category: "Monuments", icon: "🏛️", name: "The Colosseum", tagline: "Flavian Amphitheatre of Rome.", shape: "colosseum", params: { width: 100, height: 35, tiers: 4 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Travertine limestone, 4 tiered arched galleries, 188m×156m ellipse, arena floor, velarium supports. A-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "pyramid_giza", category: "Monuments", icon: "📐", name: "Pyramid of Giza", tagline: "Ancient Egyptian wonder.", shape: "pyramid_giza", params: { width: 120 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Tura limestone casing, 230m base, 138m height, true pyramid geometry. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "taj_mahal", category: "Monuments", icon: "🕌", name: "Taj Mahal", tagline: "Ivory-white marble mausoleum.", shape: "taj_mahal", params: { radius: 30 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Makrana white marble, central dome 73m, 4 minarets, chahar bagh garden, reflecting pool. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "stonehenge", category: "Monuments", icon: "🪨", name: "Stonehenge", tagline: "Prehistoric stone circle.", shape: "stonehenge", params: { radius: 25 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Sarsen bluestone megaliths, outer ring r=25m, trilithon horseshoe, altar stone. A-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "big_ben", category: "Monuments", icon: "🕰️", name: "Big Ben", tagline: "The Great Bell of Westminster.", shape: "big_ben", params: { height: 96 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_wall_stone", ...NWAF, objectNotes: "Victorian Gothic limestone. Four 7m clock faces, open belfry arches, 4 corner pinnacle spirelets, 22m square spire.", interiorType: "structure", lootTheme: "Residential" },
  { id: "statue_liberty", category: "Monuments", icon: "🗽", name: "Statue of Liberty", tagline: "Symbol of freedom.", shape: "statue_liberty", params: { height: 93 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "6-point Fort Wood star base, 3-stage granite pedestal 47m, copper-green robed figure, 7-spike crown, torch arm to 93m. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "leaning_tower", category: "Monuments", icon: "🇮🇹", name: "Tower of Pisa", tagline: "Unintended tilt of Italy.", shape: "leaning_pisa", params: { height: 56 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "8-tier Romanesque colonnade r=7.75m, 14 columns per tier, 4° tilt baked via shear transform, Carrara marble. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "arc_triomphe", category: "Monuments", icon: "🇫🇷", name: "Arc de Triomphe", tagline: "Napoleonic victory arch.", shape: "arc_triomphe", params: { height: 50 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Lutetian limestone, 50m×45m×22m, twin piers, single 29m Roman arch, barrel vault soffit, Neoclassical attic frieze. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "parthenon", category: "Monuments", icon: "🏛️", name: "The Parthenon", tagline: "Temple of Athena on the Acropolis.", shape: "parthenon", params: { height: 14 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Pentelic marble, 69.5×30.9m stylobate, 8×17 Doric peristyle (46 cols), cella naos, Pheidias frieze band, gabled pediments. S-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "burj_khalifa", category: "Monuments", icon: "🏙️", name: "Burj Khalifa", tagline: "World's tallest spire.", shape: "skyscraper", params: { width: 60, height: 828, floors: 160 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Ultra-tall spire.", interiorType: "structure", lootTheme: "Luxury" },
  { id: "empire_state", category: "Monuments", icon: "🗽", name: "Empire State", tagline: "Art Deco high-rise.", shape: "skyscraper", params: { width: 50, height: 381, floors: 102 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Indiana limestone/granite Art Deco setback tower, 102 floors, mooring mast spire to 443m. B-TIER.", interiorType: "structure", lootTheme: "Industrial" },
  { id: "cn_tower", category: "Monuments", icon: "🇨🇦", name: "CN Tower", tagline: "Toronto skyline icon.", shape: "cn_tower", params: { height: 300 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Trillium 3-buttress base, round shaft, SkyPod donut ring at mid-height, antenna mast. A-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "space_needle", category: "Monuments", icon: "🗼", name: "Space Needle", tagline: "Observation tower of Seattle.", shape: "space_needle", params: { height: 184 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "3 curved tripod legs to y=50, slim shaft, 42m flying-saucer disc at y=138 with observation rim, spire to 184m. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "london_eye", category: "Monuments", icon: "🎡", name: "London Eye", tagline: "Giant observation wheel.", shape: "torus", params: { majorR: 67, minorR: 4, majorSegs: 32 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Vertical ring.", interiorType: "open", lootTheme: "Military" },
  { id: "christ_redeemer", category: "Monuments", icon: "⛪", name: "Christ the Redeemer", tagline: "Art Deco statue of Jesus.", shape: "christ_redeemer", params: { height: 38 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Art Deco soapstone, 9.5m pedestal with chapel, tapering torso, 28m arm span with droop, head dome. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "petra_treasury", category: "Monuments", icon: "🏜️", name: "Petra Treasury", tagline: "Rock-cut temple facade.", shape: "wall_arc", params: { width: 25, height: 40 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Nabataean rose sandstone, 40m facade, Corinthian columns, broken pediment, carved urn at apex. B-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "sagrada_familia", category: "Monuments", icon: "⛪", name: "Sagrada Família", tagline: "Gaudí’s unfinished symphony.", shape: "sagrada_familia", params: { height: 86 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_wall_stone", ...BALOTA, objectNotes: "Gaudí organic spires, cruciform nave, 12 apostle spires, 4 evangelist, Mary tower, Christ spire 86m (1:2 scale), surface ribs. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "sydney_opera", category: "Monuments", icon: "🇦🇺", name: "Sydney Opera House", tagline: "Expressionist shell structure.", shape: "sydney_opera", params: { width: 120 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Jørn Utzon shells, granite podium 100×60m, Concert Hall 67m peak, Opera 59m, 5-shell ribs, Bennelong Steps. S-TIER.", interiorType: "structure", lootTheme: "Luxury" },
  { id: "golden_gate", category: "Monuments", icon: "🌉", name: "Golden Gate Bridge", tagline: "Suspension bridge span.", shape: "golden_gate_bridge", params: { width: 300, height: 100 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "International Orange painted steel, twin 227m towers, 1280m main span suspension bridge. B-TIER.", interiorType: "open", lootTheme: "Industrial" },

  // --- SCI-FI / MOVIES (20) ---
  { id: "death_star", category: "Sci-Fi / Movies", icon: "🚀", name: "Death Star", tagline: "Moon-sized space station.", shape: "deathstar", params: { radius: 44, latSegs: 18, lonSegs: 36, dishRadius: 12, dishDepth: 6, dishLat: 25 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Imperial grey durasteel hull, concave superlaser dish, equatorial trench, tractor beam towers. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "stark_tower", category: "Sci-Fi / Movies", icon: "⚡", name: "Tony Stark Tower", tagline: "Avengers headquarter tower.", shape: "tony_stark_tower", params: { height: 140 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Helipad top.", interiorType: "structure", lootTheme: "Luxury" },
  { id: "helms_deep", category: "Sci-Fi / Movies", icon: "🛡️", name: "Helm's Deep", tagline: "Rohan's mountain fortress.", shape: "helms_deep", params: { width: 100 }, frameObj: "staticobj_castle_wall3", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Grey limestone fortress, curved Deeping Wall, Hornburg tower, postern gate, Glittering Caves entrance. A-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "minas_tirith", category: "Sci-Fi / Movies", icon: "🏰", name: "Minas Tirith", tagline: "The White City of Gondor.", shape: "minas_tirith", params: { width: 120, height: 100 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Minas Anor white stone, 7 concentric tiers rising to Citadel, Tower of Ecthelion, Pelennor Fields base. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "barad_dur", category: "Sci-Fi / Movies", icon: "👁️", name: "Barad-dûr", tagline: "Tower of the Dark Lord.", shape: "barad_dur", params: { width: 50, height: 200 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Black Mordor volcanic stone, massive buttressed base, Eye of Sauron crown, iron spikes and chains. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "millennium_falcon", category: "Sci-Fi / Movies", icon: "🛸", name: "Millennium Falcon", tagline: "Fastest hunk of junk.", shape: "millennium_falcon", params: { radius: 32 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "YT-1300f Corellian freighter, disc hull with offset cockpit, Quadex power core, escape pods, dorsal gun. S-TIER.", interiorType: "open", lootTheme: "Industrial" },
  { id: "star_destroyer", category: "Sci-Fi / Movies", icon: "📐", name: "Star Destroyer", tagline: "Imperial wedge cruiser.", shape: "star_destroyer", params: { width: 100, length: 200 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Imperial-class 1600m wedge, dorsal superstructure spine, 3-bubble sensor array, hangar bays, quad turbolasers. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "hogwarts", category: "Sci-Fi / Movies", icon: "🧙", name: "Hogwarts Castle", tagline: "School of Witchcraft.", shape: "hogwarts", params: { width: 150 }, frameObj: "staticobj_castle_wall3", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Scottish Gothic castle, Great Hall peaked roof, Astronomy Tower 70m, 3 corner towers with conical caps, viaduct bridge with arches, central courtyard. S-TIER.", interiorType: "structure", lootTheme: "Historical" },
  { id: "azkaban_prison", category: "Sci-Fi / Movies", icon: "⛓️", name: "Azkaban Prison", tagline: "Wizarding jail in the sea.", shape: "azkaban_prison", params: { width: 40, height: 100 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Bleak North Sea island fortress, oppressive grey stone, iron-barred cells, Dementor-haunted battlements. A-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "tardis", category: "Sci-Fi / Movies", icon: "🟦", name: "TARDIS", tagline: "Time and Relative Dimension.", shape: "tardis", params: { height: 20 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "British police box — blue tall cabinet with pitched cap, finial lamp, and mid-band panel divider. S-TIER.", interiorType: "open", lootTheme: "SciFi" },
  { id: "stargate", category: "Sci-Fi / Movies", icon: "🌀", name: "Stargate", tagline: "Ancient ring portal.", shape: "stargate_portal", params: { radius: 25 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Vertical ring portal with 9 chevrons, 3-layer ring depth, event horizon disk fill. S-TIER.", interiorType: "open", lootTheme: "SciFi" },
  { id: "atat_walker", category: "Sci-Fi / Movies", icon: "🤖", name: "AT-AT Walker", tagline: "Imperial All Terrain Armored Transport.", shape: "atat_walker", params: { height: 35 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "4-legged giant walker, box hull, forward neck, head cockpit with dual laser cannons. S-TIER.", interiorType: "structure", lootTheme: "Military" },
  { id: "starship_enterprise", category: "Sci-Fi / Movies", icon: "🖖", name: "Starship Enterprise", tagline: "NCC-1701 — to boldly go.", shape: "starship_enterprise", params: { width: 100 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Saucer section, engineering hull, neck, deflector pylons and twin warp nacelles. S-TIER.", interiorType: "open", lootTheme: "SciFi" },
  { id: "king_kong_empire", category: "Sci-Fi / Movies", icon: "🦍", name: "King Kong — Empire State", tagline: "Big ape atop NYC's icon.", shape: "king_kong_empire", params: { height: 180 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Stepped Art Deco tower, setbacks every 40m, mooring mast spire, giant ape silhouette at apex. S-TIER.", interiorType: "structure", lootTheme: "Industrial" },
  { id: "fortress_of_solitude", category: "Sci-Fi / Movies", icon: "🧊", name: "Fortress of Solitude", tagline: "Superman's Arctic sanctum.", shape: "fortress_of_solitude", params: { width: 60, seed: 7331 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "30 jagged crystal spires of varying heights + towering central mega-crystal. S-TIER.", interiorType: "open", lootTheme: "SciFi" },
  { id: "eye_of_sauron", category: "Sci-Fi / Movies", icon: "👁️", name: "Eye of Sauron", tagline: "The lidless flaming eye.", shape: "eye_of_sauron", params: { height: 90, towerWidth: 28, eyeRadius: 22 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Tapering Barad-dûr spire with 2 outer spikes, floating ring-eye disk of concentric rings at apex. S-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "black_hole", category: "Sci-Fi / Movies", icon: "🕳️", name: "Black Hole", tagline: "Event horizon accretion disk.", shape: "black_hole", params: { radius: 35, arcs: 8 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Swirling 8-arm accretion disk, central event horizon solid sphere core. S-TIER.", interiorType: "open", lootTheme: "SciFi" },
  { id: "borg_cube", category: "Sci-Fi / Movies", icon: "⬛", name: "Borg Cube", tagline: "Resistance is futile.", shape: "borg_cube", params: { width: 100, height: 100 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "3km³ dark grey tech-organic hull, 6-face Borg circuitry grid, assimilation tube channels, interior accessible. A-TIER.", interiorType: "structure", lootTheme: "SciFi" },
  { id: "bladerunner_hq", category: "Sci-Fi / Movies", icon: "🌃", name: "Tyrell HQ", tagline: "Cyberpunk pyramid.", shape: "pyramid_giza", params: { width: 200, height: 100 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Brutalist pyramid.", interiorType: "structure", lootTheme: "Luxury" },
  { id: "tron_city", category: "Sci-Fi / Movies", icon: "🟦", name: "Tron City Core", tagline: "Digital frontier nexus.", shape: "helix", params: { radius: 60, height: 200 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Neon grid.", interiorType: "open", lootTheme: "SciFi" },
  { id: "matrix_zion", category: "Sci-Fi / Movies", icon: "🔌", name: "Zion Dock", tagline: "Humanity's last stand.", shape: "zion_dock", params: { radius: 100 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Underground hangar.", interiorType: "structure", lootTheme: "Industrial" },
  { id: "citadel_mass", category: "Sci-Fi / Movies", icon: "🛰️", name: "The Citadel (ME)", tagline: "Council space station.", shape: "skyscraper", params: { width: 80, height: 400 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Presidium ring.", interiorType: "structure", lootTheme: "Luxury" },
  { id: "halo_control", category: "Sci-Fi / Movies", icon: "😇", name: "Halo Control Room", tagline: "Forerunner installation.", shape: "halo_control_room", params: { width: 100, height: 80 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Forerunner alloy grey-teal, recessed pyramid with central holographic index pedestal, energy bridge approach. A-TIER.", interiorType: "structure", lootTheme: "SciFi" },
  { id: "nakatomi", category: "Sci-Fi / Movies", icon: "🏢", name: "Nakatomi Plaza", tagline: "Yipee Ki Yay.", shape: "nakatomi_plaza", params: { width: 30, height: 140 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Die Hard tower.", interiorType: "structure", lootTheme: "Residential" },
  { id: "jurassic_gate", category: "Sci-Fi / Movies", icon: "🦖", name: "Jurassic Gate", tagline: "Welcome to the Park.", shape: "jurassic_park_gate", params: { width: 35, height: 30 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Torched wood pillars.", interiorType: "open", lootTheme: "Historical" },
  { id: "xwing", category: "Sci-Fi / Movies", icon: "🚀", name: "X-Wing Fighter", tagline: "Rebel Alliance starfighter.", shape: "xwing", params: { length: 13 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Incom T-65B, 13m fuselage, 4 S-foils open attack position, 4 Incom 4L4 fusial engines, cockpit canopy, R2-D2 astromech socket. S-TIER.", interiorType: "open", lootTheme: "Military" },

  // --- MILITARY / FOBS ---
  { id: "missile_silo", category: "Military", icon: "🚀", name: "Missile Silo", tagline: "Underground launch pad.", shape: "tunnel_circle", params: { radius: 10, height: 50 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Deep vertical tube.", interiorType: "structure", lootTheme: "Military" },
  { id: "bunker_complex", category: "Military", icon: "🏢", name: "Bunker Complex", tagline: "Hardened command center.", shape: "bunker_complex", params: { length: 80 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", posX: KRASN.posX, posY: UNDERGROUND.posY, posZ: KRASN.posZ, objectNotes: "Reinforced concrete.", interiorType: "structure", lootTheme: "Military" },
  { id: "military_fob", category: "Military", icon: "⛺", name: "Military FOB", tagline: "Forward Operating Base.", shape: "military_fob", params: { width: 60 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Double HESCO perimeter, inner tents and command post.", interiorType: "open", lootTheme: "Military" },
  { id: "checkpoint_charlie_build", category: "Military", icon: "🛑", name: "Checkpoint Charlie", tagline: "Cold War border crossing.", shape: "checkpoint_charlie", params: { width: 30 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Zigzag roadblocks, guard tower, barriers.", interiorType: "open", lootTheme: "Military" },
  { id: "trench_line", category: "Military", icon: "🪖", name: "Trench Network", tagline: "WW1 defensive trench system.", shape: "trench_network", params: { width: 120 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Zigzag trenches with communication branches.", interiorType: "open", lootTheme: "Military" },
  { id: "normandy_beach", category: "Military", icon: "🏖️", name: "Normandy Bunkers", tagline: "D-Day Atlantic Wall fortifications.", shape: "normandy_bunkers", params: { width: 120 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Hexagonal pillboxes, dragon's teeth hedgehogs.", interiorType: "structure", lootTheme: "Military" },

  // --- FANTASY / FICTIONAL ---
  { id: "the_wall_got", category: "Sci-Fi / Movies", icon: "🧊", name: "The Wall (GoT)", tagline: "700ft ice barrier — The Night's Watch.", shape: "the_wall_game_of_thrones", params: { width: 120, height: 60 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Ice wall 120m long, 60m tall, 20m thick base tapering to 5m at top, winch elevator disks every 20m. S-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "crop_circle", category: "Sci-Fi / Movies", icon: "🌾", name: "Crop Circle", tagline: "Mysterious alien formation.", shape: "crop_circle", params: { width: 80 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Concentric rings with 6 radial spoke lines, alien geometry. A-TIER.", interiorType: "open", lootTheme: "SciFi" },

  // --- GAMES / FANTASY ---
  { id: "peach_castle", category: "Games", icon: "🍑", name: "Peach's Castle", tagline: "Nintendo's iconic mushroom castle.", shape: "peach_castle", params: { radius: 20 }, frameObj: "staticobj_wall_stone2", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "Central cylindrical core 30m, 4 outer corner towers with tapering conical roofs, drawbridge. S-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "celtic_ring", category: "Games", icon: "🪨", name: "Celtic Ring Fort", tagline: "Iron Age circular stone ringfort.", shape: "celtic_ring", params: { radius: 30, height: 8, stoneCount: 24, archCount: 6 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "24 standing uprights forming outer ring, 6 arch-gate posts outside the ring perimeter. A-TIER.", interiorType: "open", lootTheme: "Historical" },
  { id: "orbital_station", category: "Sci-Fi / Movies", icon: "🛸", name: "Orbital Station", tagline: "Space ring station.", shape: "orbital_station", params: { radius: 40 }, frameObj: "staticobj_wall_milcnc_4", fillObj: "staticobj_platform1_block", ...NWAF, objectNotes: "Outer ring band, central hub cylinder, 4 spoke corridors connecting ring to hub. A-TIER.", interiorType: "structure", lootTheme: "SciFi" },

  // --- CIVILIAN / URBAN ---
  { id: "police_station_build", category: "Civilian", icon: "🚔", name: "Police Station", tagline: "Law enforcement HQ.", shape: "police_station", params: { width: 30, depth: 40, height: 8 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...KRASN, objectNotes: "Main block with entrance gap, perimeter wall, holding cells wing. Urban spawn.", interiorType: "structure", lootTheme: "Residential" },
  { id: "hospital_build", category: "Civilian", icon: "🏥", name: "General Hospital", tagline: "Fully equipped medical facility.", shape: "hospital", params: { width: 50, depth: 70, height: 16 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...STARY, objectNotes: "L-shaped main wing, ambulance bay, rooftop helipad, 4 floors, perimeter fence. S-TIER civilian.", interiorType: "structure", lootTheme: "Medical" },
  { id: "supermarket_build", category: "Civilian", icon: "🛒", name: "Supermarket", tagline: "Big-box retail with loading bay.", shape: "supermarket", params: { width: 60, depth: 40, height: 8 }, frameObj: "staticobj_wall_cncsmall_8", fillObj: "staticobj_platform1_block", ...BALOTA, objectNotes: "Large flat-roof retail store, loading dock rear, canopy entrance, car park. A-TIER.", interiorType: "structure", lootTheme: "Residential" },
  { id: "log_cabin_build", category: "Civilian", icon: "🪵", name: "Log Cabin", tagline: "Rustic woodland retreat.", shape: "log_cabin", params: { width: 12, depth: 16, height: 6 }, frameObj: "staticobj_wall_stone", fillObj: "staticobj_platform1_block", ...TISY, objectNotes: "Horizontal log stacking, pitched roof, porch.", interiorType: "structure", lootTheme: "Residential" },
];
