// ─── DayZ Loot Database ───────────────────────────────────────────────────────
// Classnames verified against DayZ 1.25 vanilla types.xml (Bohemia GitHub)
// Usage tags match DayZ CE spawn zone categories.

export interface DayzLootEntry {
  classname: string;
  displayName: string;
  category: string;
  subcategory: string;
  tags: string[];
  nominal?: number;
  usage?: string[];
}

export const DAYZ_LOOT_DB: DayzLootEntry[] = [
  // ── Rifles ────────────────────────────────────────────────────────────────
  { classname: "AKM",              displayName: "AKM",                      category: "Weapons", subcategory: "Rifles",   tags: ["assault","762x39","military"],    nominal: 3,  usage: ["Military"] },
  { classname: "AK101",            displayName: "AK-101",                   category: "Weapons", subcategory: "Rifles",   tags: ["assault","556x45","military"],    nominal: 3,  usage: ["Military"] },
  { classname: "AK74",             displayName: "AK-74",                    category: "Weapons", subcategory: "Rifles",   tags: ["assault","545x39","military"],    nominal: 3,  usage: ["Military"] },
  { classname: "AKS74U",           displayName: "AKS-74U",                  category: "Weapons", subcategory: "Rifles",   tags: ["assault","545x39","military"],    nominal: 2,  usage: ["Military"] },
  { classname: "M4A1",             displayName: "M4-A1",                    category: "Weapons", subcategory: "Rifles",   tags: ["assault","556x45","military"],    nominal: 3,  usage: ["Military"] },
  { classname: "FAL",              displayName: "FAL",                      category: "Weapons", subcategory: "Rifles",   tags: ["battle","762x51","military"],     nominal: 2,  usage: ["Military"] },
  { classname: "VSD",              displayName: "VSD",                      category: "Weapons", subcategory: "Rifles",   tags: ["dmr","762x54","military"],        nominal: 1,  usage: ["Military"] },
  { classname: "CR527",            displayName: "CR 527",                   category: "Weapons", subcategory: "Rifles",   tags: ["bolt","762x39","civilian"],       nominal: 5,  usage: ["Hunting","Farm"] },
  { classname: "CZ527",            displayName: "CZ 527",                   category: "Weapons", subcategory: "Rifles",   tags: ["bolt","762x39","civilian"],       nominal: 5,  usage: ["Hunting","Farm"] },
  { classname: "Repeater",         displayName: "Repeater Carbine",         category: "Weapons", subcategory: "Rifles",   tags: ["lever","357mag","civilian"],      nominal: 4,  usage: ["Hunting","Town"] },
  { classname: "SKS",              displayName: "SKS",                      category: "Weapons", subcategory: "Rifles",   tags: ["semi","762x39","civilian"],       nominal: 4,  usage: ["Hunting","Town"] },
  { classname: "SG5K",             displayName: "SG5-K",                    category: "Weapons", subcategory: "Rifles",   tags: ["smg","9x19","military"],          nominal: 2,  usage: ["Military"] },
  { classname: "LAR",              displayName: "LAR",                      category: "Weapons", subcategory: "Rifles",   tags: ["semi","762x51","military"],       nominal: 2,  usage: ["Military"] },
  { classname: "KA_M",             displayName: "KA-M",                     category: "Weapons", subcategory: "Rifles",   tags: ["assault","762x39","military"],    nominal: 2,  usage: ["Military"] },
  { classname: "KA_101",           displayName: "KA-101",                   category: "Weapons", subcategory: "Rifles",   tags: ["assault","556x45","military"],    nominal: 2,  usage: ["Military"] },
  { classname: "KA_74",            displayName: "KA-74",                    category: "Weapons", subcategory: "Rifles",   tags: ["assault","545x39","military"],    nominal: 2,  usage: ["Military"] },
  { classname: "KAS74U",           displayName: "KAS-74U",                  category: "Weapons", subcategory: "Rifles",   tags: ["assault","545x39","military"],    nominal: 2,  usage: ["Military"] },
  { classname: "ASVAL",            displayName: "AS VAL",                   category: "Weapons", subcategory: "Rifles",   tags: ["assault","9x39","military"],      nominal: 1,  usage: ["Military"] },
  { classname: "VSS",              displayName: "VSS Vintorez",             category: "Weapons", subcategory: "Rifles",   tags: ["dmr","9x39","military"],          nominal: 1,  usage: ["Military"] },
  { classname: "Tundra",           displayName: "Tundra",                   category: "Weapons", subcategory: "Rifles",   tags: ["bolt","308win","civilian"],       nominal: 3,  usage: ["Hunting"] },
  { classname: "BK133",            displayName: "BK-133",                   category: "Weapons", subcategory: "Rifles",   tags: ["shotgun","12ga","military"],      nominal: 3,  usage: ["Military"] },
  // ── Snipers ───────────────────────────────────────────────────────────────
  { classname: "SVD",              displayName: "SVD",                      category: "Weapons", subcategory: "Snipers",  tags: ["sniper","762x54","military"],     nominal: 1,  usage: ["Military"] },
  { classname: "Mosin9130",        displayName: "Mosin 91/30",              category: "Weapons", subcategory: "Snipers",  tags: ["bolt","762x54","civilian"],       nominal: 4,  usage: ["Hunting","Town"] },
  { classname: "Winchester70",     displayName: "Winchester Model 70",      category: "Weapons", subcategory: "Snipers",  tags: ["bolt","308win","civilian"],       nominal: 3,  usage: ["Hunting"] },
  { classname: "Blaze95",          displayName: "Blaze 95 Double Rifle",    category: "Weapons", subcategory: "Snipers",  tags: ["double","762x51","civilian"],     nominal: 2,  usage: ["Hunting"] },
  { classname: "CZ550",            displayName: "CZ 550",                   category: "Weapons", subcategory: "Snipers",  tags: ["bolt","308win","civilian"],       nominal: 3,  usage: ["Hunting"] },
  { classname: "CZ61",             displayName: "CZ 61 Skorpion",           category: "Weapons", subcategory: "Snipers",  tags: ["smg","32acp","civilian"],         nominal: 3,  usage: ["Town"] },
  { classname: "SVAL",             displayName: "SVAL",                     category: "Weapons", subcategory: "Snipers",  tags: ["dmr","9x39","military"],          nominal: 1,  usage: ["Military"] },
  // ── Shotguns ──────────────────────────────────────────────────────────────
  { classname: "IZH43",            displayName: "IZH-43",                   category: "Weapons", subcategory: "Shotguns", tags: ["shotgun","12ga","civilian"],      nominal: 5,  usage: ["Hunting","Farm","Town"] },
  { classname: "MP133",            displayName: "MP-133",                   category: "Weapons", subcategory: "Shotguns", tags: ["shotgun","12ga","civilian"],      nominal: 5,  usage: ["Hunting","Farm","Town"] },
  { classname: "Saiga",            displayName: "Saiga",                    category: "Weapons", subcategory: "Shotguns", tags: ["shotgun","12ga","military"],      nominal: 3,  usage: ["Military","Town"] },
  { classname: "KA_S",             displayName: "KA-S",                     category: "Weapons", subcategory: "Shotguns", tags: ["shotgun","12ga","military"],      nominal: 2,  usage: ["Military"] },
  // ── SMGs ──────────────────────────────────────────────────────────────────
  { classname: "UMP45",            displayName: "UMP-45",                   category: "Weapons", subcategory: "SMGs",     tags: ["smg","45acp","military"],         nominal: 3,  usage: ["Military"] },
  { classname: "MP5K",             displayName: "MP5-K",                    category: "Weapons", subcategory: "SMGs",     tags: ["smg","9x19","military"],          nominal: 3,  usage: ["Military"] },
  { classname: "PP19",             displayName: "PP-19 Bizon",              category: "Weapons", subcategory: "SMGs",     tags: ["smg","9x19","military"],          nominal: 2,  usage: ["Military"] },
  { classname: "Scorpion",         displayName: "Scorpion",                 category: "Weapons", subcategory: "SMGs",     tags: ["smg","380acp","civilian"],        nominal: 4,  usage: ["Town"] },
  // ── Pistols ───────────────────────────────────────────────────────────────
  { classname: "Glock19",          displayName: "Glock 19",                 category: "Weapons", subcategory: "Pistols",  tags: ["pistol","9x19","civilian"],       nominal: 6,  usage: ["Town","Police"] },
  { classname: "Makarov",          displayName: "Makarov",                  category: "Weapons", subcategory: "Pistols",  tags: ["pistol","9x18","military"],       nominal: 5,  usage: ["Military","Police"] },
  { classname: "CZ75",             displayName: "CZ 75",                    category: "Weapons", subcategory: "Pistols",  tags: ["pistol","9x19","civilian"],       nominal: 5,  usage: ["Town","Police"] },
  { classname: "Deagle",           displayName: "Desert Eagle",             category: "Weapons", subcategory: "Pistols",  tags: ["pistol","357mag","civilian"],     nominal: 2,  usage: ["Town"] },
  { classname: "FNX45",            displayName: "FNX-45",                   category: "Weapons", subcategory: "Pistols",  tags: ["pistol","45acp","military"],      nominal: 3,  usage: ["Military","Police"] },
  { classname: "P1",               displayName: "P1",                       category: "Weapons", subcategory: "Pistols",  tags: ["pistol","9x19","civilian"],       nominal: 5,  usage: ["Town","Police"] },
  { classname: "Magnum",           displayName: ".357 Magnum",              category: "Weapons", subcategory: "Pistols",  tags: ["pistol","357mag","civilian"],     nominal: 3,  usage: ["Town","Hunting"] },
  { classname: "CR75",             displayName: "CR-75",                    category: "Weapons", subcategory: "Pistols",  tags: ["pistol","9x19","civilian"],       nominal: 5,  usage: ["Town","Police"] },
  // ── Melee ─────────────────────────────────────────────────────────────────
  { classname: "Hatchet",          displayName: "Hatchet",                  category: "Weapons", subcategory: "Melee",    tags: ["melee","axe","tool"],             nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "FirefighterAxe",   displayName: "Fire Axe",                 category: "Weapons", subcategory: "Melee",    tags: ["melee","axe","fire"],             nominal: 4,  usage: ["Town","Industrial"] },
  { classname: "BaseballBat",      displayName: "Baseball Bat",             category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","civilian"],       nominal: 5,  usage: ["Town"] },
  { classname: "Bat_Nails",        displayName: "Nailed Baseball Bat",      category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","civilian"],       nominal: 2,  usage: ["Town"] },
  { classname: "Machete",          displayName: "Machete",                  category: "Weapons", subcategory: "Melee",    tags: ["melee","blade","civilian"],       nominal: 4,  usage: ["Hunting","Farm"] },
  { classname: "KitchenKnife",     displayName: "Kitchen Knife",            category: "Weapons", subcategory: "Melee",    tags: ["melee","blade","civilian"],       nominal: 8,  usage: ["Town","Farm"] },
  { classname: "HuntingKnife",     displayName: "Hunting Knife",            category: "Weapons", subcategory: "Melee",    tags: ["melee","blade","hunting"],        nominal: 6,  usage: ["Hunting","Farm"] },
  { classname: "Crowbar",          displayName: "Crowbar",                  category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","tool"],           nominal: 5,  usage: ["Industrial","Town"] },
  { classname: "Sledgehammer",     displayName: "Sledgehammer",             category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","tool"],           nominal: 3,  usage: ["Industrial"] },
  { classname: "Pitchfork",        displayName: "Pitchfork",                category: "Weapons", subcategory: "Melee",    tags: ["melee","blade","farm"],           nominal: 4,  usage: ["Farm"] },
  { classname: "Shovel",           displayName: "Shovel",                   category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","tool"],           nominal: 5,  usage: ["Farm","Town"] },
  { classname: "Pickaxe",          displayName: "Pickaxe",                  category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","tool"],           nominal: 3,  usage: ["Industrial"] },
  { classname: "Pipe",             displayName: "Pipe",                     category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","civilian"],       nominal: 5,  usage: ["Industrial","Town"] },
  { classname: "Sword",            displayName: "Sword",                    category: "Weapons", subcategory: "Melee",    tags: ["melee","blade","rare"],           nominal: 1,  usage: ["Town"] },
  { classname: "Bat_Baseball",     displayName: "Baseball Bat",             category: "Weapons", subcategory: "Melee",    tags: ["melee","blunt","civilian"],       nominal: 5,  usage: ["Town"] },
  // ── Magazines ─────────────────────────────────────────────────────────────
  { classname: "Mag_STANAG_30Rnd",       displayName: "STANAG 30rnd Mag",         category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","556x45","m4","ak101"],    nominal: 8,  usage: ["Military"] },
  { classname: "Mag_STANAG_60Rnd",       displayName: "STANAG 60rnd Mag",         category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","556x45","m4"],            nominal: 3,  usage: ["Military"] },
  { classname: "Mag_AK101_30Rnd",        displayName: "AK-101 30rnd Mag",         category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","556x45","ak101"],         nominal: 6,  usage: ["Military"] },
  { classname: "Mag_AKM_30Rnd",          displayName: "AKM 30rnd Mag",            category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","762x39","akm"],           nominal: 8,  usage: ["Military"] },
  { classname: "Mag_AKM_Drum75Rnd",      displayName: "AKM Drum 75rnd",           category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","762x39","akm","drum"],    nominal: 2,  usage: ["Military"] },
  { classname: "Mag_AK74_30Rnd",         displayName: "AK-74 30rnd Mag",          category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","545x39","ak74"],          nominal: 8,  usage: ["Military"] },
  { classname: "Mag_AK74_45Rnd",         displayName: "AK-74 45rnd Mag",          category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","545x39","ak74"],          nominal: 4,  usage: ["Military"] },
  { classname: "Mag_SVD_10Rnd",          displayName: "SVD 10rnd Mag",            category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","762x54","svd"],           nominal: 3,  usage: ["Military"] },
  { classname: "Mag_FAL_20Rnd",          displayName: "FAL 20rnd Mag",            category: "Magazines", subcategory: "Rifle Mags",   tags: ["mag","762x51","fal"],           nominal: 4,  usage: ["Military"] },
  { classname: "Mag_UMP_25Rnd",          displayName: "UMP-45 25rnd Mag",         category: "Magazines", subcategory: "SMG Mags",     tags: ["mag","45acp","ump"],            nominal: 5,  usage: ["Military"] },
  { classname: "Mag_MP5_30Rnd",          displayName: "MP5 30rnd Mag",            category: "Magazines", subcategory: "SMG Mags",     tags: ["mag","9x19","mp5"],             nominal: 5,  usage: ["Military"] },
  { classname: "Mag_PP19_64Rnd",         displayName: "PP-19 64rnd Mag",          category: "Magazines", subcategory: "SMG Mags",     tags: ["mag","9x19","pp19"],            nominal: 3,  usage: ["Military"] },
  { classname: "Mag_Glock_15Rnd",        displayName: "Glock 15rnd Mag",          category: "Magazines", subcategory: "Pistol Mags",  tags: ["mag","9x19","glock"],           nominal: 8,  usage: ["Town","Police"] },
  { classname: "Mag_Glock_17Rnd",        displayName: "Glock 17rnd Mag",          category: "Magazines", subcategory: "Pistol Mags",  tags: ["mag","9x19","glock"],           nominal: 5,  usage: ["Town","Police"] },
  { classname: "Mag_FNX45_15Rnd",        displayName: "FNX-45 15rnd Mag",         category: "Magazines", subcategory: "Pistol Mags",  tags: ["mag","45acp","fnx45"],          nominal: 5,  usage: ["Military","Police"] },
  { classname: "Mag_CZ75_15Rnd",         displayName: "CZ 75 15rnd Mag",          category: "Magazines", subcategory: "Pistol Mags",  tags: ["mag","9x19","cz75"],            nominal: 6,  usage: ["Town","Police"] },
  { classname: "Mag_Makarov_8Rnd",       displayName: "Makarov 8rnd Mag",         category: "Magazines", subcategory: "Pistol Mags",  tags: ["mag","9x18","makarov"],         nominal: 6,  usage: ["Military","Police"] },
  { classname: "Mag_Saiga_5Rnd",         displayName: "Saiga 5rnd Mag",           category: "Magazines", subcategory: "Shotgun Mags", tags: ["mag","12ga","saiga"],           nominal: 4,  usage: ["Military"] },
  { classname: "Mag_Saiga_8Rnd",         displayName: "Saiga 8rnd Mag",           category: "Magazines", subcategory: "Shotgun Mags", tags: ["mag","12ga","saiga"],           nominal: 3,  usage: ["Military"] },
  // ── Ammo ──────────────────────────────────────────────────────────────────
  { classname: "Ammo_762x39",            displayName: "7.62x39mm Rounds",         category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","762x39","akm","skr"],    nominal: 10, usage: ["Military","Hunting"] },
  { classname: "Ammo_556x45",            displayName: "5.56x45mm Rounds",         category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","556x45","m4","ak101"],   nominal: 10, usage: ["Military"] },
  { classname: "Ammo_545x39",            displayName: "5.45x39mm Rounds",         category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","545x39","ak74"],         nominal: 10, usage: ["Military"] },
  { classname: "Ammo_762x51",            displayName: "7.62x51mm Rounds",         category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","762x51","fal","blaze"],  nominal: 8,  usage: ["Military","Hunting"] },
  { classname: "Ammo_762x54",            displayName: "7.62x54mm Rounds",         category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","762x54","svd","mosin"],  nominal: 8,  usage: ["Military","Hunting"] },
  { classname: "Ammo_308Win",            displayName: ".308 Win Rounds",          category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","308win","winchester"],   nominal: 8,  usage: ["Hunting"] },
  { classname: "Ammo_9x39",             displayName: "9x39mm Rounds",            category: "Ammo", subcategory: "Rifle Ammo",   tags: ["ammo","9x39","asval","vss"],    nominal: 5,  usage: ["Military"] },
  { classname: "Ammo_9x19",             displayName: "9x19mm Rounds",            category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","9x19","glock","mp5"],    nominal: 12, usage: ["Town","Police","Military"] },
  { classname: "Ammo_9x18",             displayName: "9x18mm Rounds",            category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","9x18","makarov"],        nominal: 10, usage: ["Military","Police"] },
  { classname: "Ammo_45ACP",            displayName: ".45 ACP Rounds",           category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","45acp","ump","fnx45"],   nominal: 8,  usage: ["Military"] },
  { classname: "Ammo_357",              displayName: ".357 Magnum Rounds",       category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","357mag","magnum","deagle"], nominal: 6, usage: ["Town","Hunting"] },
  { classname: "Ammo_380",              displayName: ".380 ACP Rounds",          category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","380acp","scorpion"],     nominal: 8,  usage: ["Town"] },
  { classname: "Ammo_12ga",             displayName: "12ga Buckshot",            category: "Ammo", subcategory: "Shotgun Ammo", tags: ["ammo","12ga","shotgun"],        nominal: 10, usage: ["Hunting","Farm","Town"] },
  { classname: "Ammo_12gaSlug",         displayName: "12ga Slug",               category: "Ammo", subcategory: "Shotgun Ammo", tags: ["ammo","12ga","slug","shotgun"], nominal: 6,  usage: ["Hunting"] },
  { classname: "Ammo_32ACP",            displayName: ".32 ACP Rounds",          category: "Ammo", subcategory: "Pistol Ammo",  tags: ["ammo","32acp","cz61"],          nominal: 8,  usage: ["Town"] },
  // ── Explosives ────────────────────────────────────────────────────────────
  { classname: "RGD5Grenade",           displayName: "RGD-5 Grenade",           category: "Ammo", subcategory: "Explosives",   tags: ["grenade","explosive","military"], nominal: 2, usage: ["Military"] },
  { classname: "M67Grenade",            displayName: "M67 Grenade",             category: "Ammo", subcategory: "Explosives",   tags: ["grenade","explosive","military"], nominal: 2, usage: ["Military"] },
  { classname: "FlashGrenade",          displayName: "Flash Grenade",           category: "Ammo", subcategory: "Explosives",   tags: ["grenade","flash","military"],   nominal: 2,  usage: ["Military"] },
  { classname: "SmokeGrenade_White",    displayName: "Smoke Grenade (White)",   category: "Ammo", subcategory: "Explosives",   tags: ["smoke","grenade","signal"],     nominal: 3,  usage: ["Military"] },
  { classname: "SmokeGrenade_Red",      displayName: "Smoke Grenade (Red)",     category: "Ammo", subcategory: "Explosives",   tags: ["smoke","grenade","signal"],     nominal: 2,  usage: ["Military"] },
  { classname: "SmokeGrenade_Green",    displayName: "Smoke Grenade (Green)",   category: "Ammo", subcategory: "Explosives",   tags: ["smoke","grenade","signal"],     nominal: 2,  usage: ["Military"] },
  { classname: "SmokeGrenade_Yellow",   displayName: "Smoke Grenade (Yellow)",  category: "Ammo", subcategory: "Explosives",   tags: ["smoke","grenade","signal"],     nominal: 2,  usage: ["Military"] },
  { classname: "Flare",                 displayName: "Flare",                   category: "Ammo", subcategory: "Explosives",   tags: ["flare","signal","light"],       nominal: 4,  usage: ["Military","Town"] },
  { classname: "MineExplosive",         displayName: "Land Mine",               category: "Ammo", subcategory: "Explosives",   tags: ["mine","explosive","military"],  nominal: 1,  usage: ["Military"] },
  // ── Weapon Attachments ────────────────────────────────────────────────────
  { classname: "ACOGOptic",             displayName: "ACOG Optic",              category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","military"],   nominal: 3,  usage: ["Military"] },
  { classname: "PSO1Optic",             displayName: "PSO-1 Optic",             category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","military"],   nominal: 3,  usage: ["Military"] },
  { classname: "PUScopeOptic",          displayName: "PU Scope",                category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","mosin"],      nominal: 3,  usage: ["Hunting","Military"] },
  { classname: "KashtanOptic",          displayName: "Kashtan Optic",           category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","military"],   nominal: 2,  usage: ["Military"] },
  { classname: "RailgunOptic",          displayName: "Railgun Optic",           category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","military"],   nominal: 2,  usage: ["Military"] },
  { classname: "IronSight",             displayName: "Iron Sight",              category: "Attachments", subcategory: "Optics",    tags: ["optic","ironsight"],          nominal: 5,  usage: ["Military","Town"] },
  { classname: "HuntingOptic",          displayName: "Hunting Scope",           category: "Attachments", subcategory: "Optics",    tags: ["optic","scope","hunting"],    nominal: 4,  usage: ["Hunting"] },
  { classname: "Compensator",           displayName: "Compensator",             category: "Attachments", subcategory: "Muzzle",    tags: ["muzzle","compensator"],       nominal: 4,  usage: ["Military"] },
  { classname: "SuppressorPistol",      displayName: "Pistol Suppressor",       category: "Attachments", subcategory: "Muzzle",    tags: ["muzzle","suppressor","pistol"], nominal: 2, usage: ["Military"] },
  { classname: "SuppressorRifle",       displayName: "Rifle Suppressor",        category: "Attachments", subcategory: "Muzzle",    tags: ["muzzle","suppressor","rifle"], nominal: 2, usage: ["Military"] },
  { classname: "FlashHider",            displayName: "Flash Hider",             category: "Attachments", subcategory: "Muzzle",    tags: ["muzzle","flashhider"],        nominal: 4,  usage: ["Military"] },
  { classname: "BayonetKnife",          displayName: "Bayonet",                 category: "Attachments", subcategory: "Muzzle",    tags: ["bayonet","melee","military"], nominal: 3,  usage: ["Military"] },
  { classname: "Flashlight",            displayName: "Flashlight",              category: "Attachments", subcategory: "Underbarrel", tags: ["light","flashlight"],       nominal: 5,  usage: ["Town","Military"] },
  { classname: "Foregrip",              displayName: "Foregrip",                category: "Attachments", subcategory: "Underbarrel", tags: ["grip","foregrip"],          nominal: 4,  usage: ["Military"] },
  { classname: "Bipod",                 displayName: "Bipod",                   category: "Attachments", subcategory: "Underbarrel", tags: ["bipod","stability"],        nominal: 3,  usage: ["Military","Hunting"] },
  { classname: "ButtstockAK",           displayName: "AK Buttstock",            category: "Attachments", subcategory: "Stock",     tags: ["stock","ak"],                 nominal: 4,  usage: ["Military"] },
  { classname: "ButtstockM4",           displayName: "M4 Buttstock",            category: "Attachments", subcategory: "Stock",     tags: ["stock","m4"],                 nominal: 4,  usage: ["Military"] },
  { classname: "PistolSuppressor",      displayName: "Pistol Suppressor",       category: "Attachments", subcategory: "Muzzle",    tags: ["muzzle","suppressor"],        nominal: 2,  usage: ["Military"] },
  // ── Clothing — Jackets ────────────────────────────────────────────────────
  { classname: "GorkaEJacket_Black",     displayName: "Gorka E Jacket (Black)",   category: "Clothing", subcategory: "Jackets",  tags: ["jacket","military","gorka"],    nominal: 5,  usage: ["Military"] },
  { classname: "GorkaEJacket_Camo",      displayName: "Gorka E Jacket (Camo)",    category: "Clothing", subcategory: "Jackets",  tags: ["jacket","military","gorka"],    nominal: 5,  usage: ["Military"] },
  { classname: "TTSKOJacket",            displayName: "TTSKO Jacket",             category: "Clothing", subcategory: "Jackets",  tags: ["jacket","military","camo"],     nominal: 5,  usage: ["Military"] },
  { classname: "BDUJacket",             displayName: "BDU Jacket",               category: "Clothing", subcategory: "Jackets",  tags: ["jacket","military","bdu"],      nominal: 5,  usage: ["Military"] },
  { classname: "HunterJacket_Brown",     displayName: "Hunter Jacket (Brown)",    category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","hunter"],   nominal: 6,  usage: ["Hunting","Farm"] },
  { classname: "RainCoat_Green",         displayName: "Rain Coat (Green)",        category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","rain"],     nominal: 6,  usage: ["Town","Farm"] },
  { classname: "RainCoat_Yellow",        displayName: "Rain Coat (Yellow)",       category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","rain"],     nominal: 6,  usage: ["Town","Farm"] },
  { classname: "DenimJacket_Black",      displayName: "Denim Jacket (Black)",     category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","denim"],    nominal: 7,  usage: ["Town"] },
  { classname: "DenimJacket_Blue",       displayName: "Denim Jacket (Blue)",      category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","denim"],    nominal: 7,  usage: ["Town"] },
  { classname: "LeatherJacket_Black",    displayName: "Leather Jacket (Black)",   category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","leather"],  nominal: 4,  usage: ["Town"] },
  { classname: "FirefighterJacket",      displayName: "Firefighter Jacket",       category: "Clothing", subcategory: "Jackets",  tags: ["jacket","civilian","fire"],     nominal: 3,  usage: ["Industrial","Town"] },
  { classname: "PolicejacketPB",         displayName: "Police Jacket",            category: "Clothing", subcategory: "Jackets",  tags: ["jacket","police"],              nominal: 3,  usage: ["Police"] },
  { classname: "MedicalScrubsTop_Green", displayName: "Medical Scrubs Top",       category: "Clothing", subcategory: "Jackets",  tags: ["jacket","medical","scrubs"],    nominal: 3,  usage: ["Medic"] },
  // ── Clothing — Pants ──────────────────────────────────────────────────────
  { classname: "GorkaEPants_Black",      displayName: "Gorka E Pants (Black)",    category: "Clothing", subcategory: "Pants",    tags: ["pants","military","gorka"],     nominal: 5,  usage: ["Military"] },
  { classname: "TTSKOPants",             displayName: "TTSKO Pants",              category: "Clothing", subcategory: "Pants",    tags: ["pants","military","camo"],      nominal: 5,  usage: ["Military"] },
  { classname: "BDUPants",              displayName: "BDU Pants",                category: "Clothing", subcategory: "Pants",    tags: ["pants","military","bdu"],       nominal: 5,  usage: ["Military"] },
  { classname: "HunterPants_Brown",      displayName: "Hunter Pants (Brown)",     category: "Clothing", subcategory: "Pants",    tags: ["pants","civilian","hunter"],    nominal: 6,  usage: ["Hunting","Farm"] },
  { classname: "JeansPants_Black",       displayName: "Jeans (Black)",            category: "Clothing", subcategory: "Pants",    tags: ["pants","civilian","jeans"],     nominal: 8,  usage: ["Town"] },
  { classname: "JeansPants_Blue",        displayName: "Jeans (Blue)",             category: "Clothing", subcategory: "Pants",    tags: ["pants","civilian","jeans"],     nominal: 8,  usage: ["Town"] },
  { classname: "CargoPants_Black",       displayName: "Cargo Pants (Black)",      category: "Clothing", subcategory: "Pants",    tags: ["pants","civilian","cargo"],     nominal: 6,  usage: ["Town"] },
  { classname: "MedicalScrubsPants",     displayName: "Medical Scrubs Pants",     category: "Clothing", subcategory: "Pants",    tags: ["pants","medical","scrubs"],     nominal: 3,  usage: ["Medic"] },
  { classname: "PolicePants",            displayName: "Police Pants",             category: "Clothing", subcategory: "Pants",    tags: ["pants","police"],               nominal: 3,  usage: ["Police"] },
  // ── Clothing — Boots ──────────────────────────────────────────────────────
  { classname: "SoldierBoots_Black",     displayName: "Soldier Boots (Black)",    category: "Clothing", subcategory: "Boots",    tags: ["boots","military"],             nominal: 5,  usage: ["Military"] },
  { classname: "HikingBootsLow_Brown",   displayName: "Hiking Boots (Brown)",     category: "Clothing", subcategory: "Boots",    tags: ["boots","civilian","hiking"],    nominal: 6,  usage: ["Hunting","Town"] },
  { classname: "HikingBootsLow_Beige",   displayName: "Hiking Boots (Beige)",     category: "Clothing", subcategory: "Boots",    tags: ["boots","civilian","hiking"],    nominal: 6,  usage: ["Hunting","Town"] },
  { classname: "WorkingBoots_Brown",     displayName: "Working Boots (Brown)",    category: "Clothing", subcategory: "Boots",    tags: ["boots","civilian","work"],      nominal: 6,  usage: ["Industrial","Farm"] },
  { classname: "CombatBoots_Black",      displayName: "Combat Boots (Black)",     category: "Clothing", subcategory: "Boots",    tags: ["boots","military","combat"],    nominal: 4,  usage: ["Military","Police"] },
  { classname: "WelliesBoots_Black",     displayName: "Wellies (Black)",          category: "Clothing", subcategory: "Boots",    tags: ["boots","civilian","rubber"],    nominal: 5,  usage: ["Farm","Town"] },
  // ── Clothing — Headgear ───────────────────────────────────────────────────
  { classname: "HelmetSteelProtector",   displayName: "Steel Protector Helmet",   category: "Clothing", subcategory: "Headgear", tags: ["helmet","military"],            nominal: 4,  usage: ["Military"] },
  { classname: "HelmetMoto",             displayName: "Moto Helmet",              category: "Clothing", subcategory: "Headgear", tags: ["helmet","civilian","moto"],     nominal: 4,  usage: ["Town"] },
  { classname: "HelmetBallistic",        displayName: "Ballistic Helmet",         category: "Clothing", subcategory: "Headgear", tags: ["helmet","military","ballistic"], nominal: 3, usage: ["Military"] },
  { classname: "BalaclavaKnit_Black",    displayName: "Knit Balaclava (Black)",   category: "Clothing", subcategory: "Headgear", tags: ["mask","balaclava"],             nominal: 5,  usage: ["Military","Town"] },
  { classname: "BalaclavaKnit_Green",    displayName: "Knit Balaclava (Green)",   category: "Clothing", subcategory: "Headgear", tags: ["mask","balaclava"],             nominal: 5,  usage: ["Military","Town"] },
  { classname: "GasMask",               displayName: "Gas Mask",                 category: "Clothing", subcategory: "Headgear", tags: ["mask","gas","military"],        nominal: 3,  usage: ["Military","Industrial"] },
  { classname: "BaseballCap_Black",      displayName: "Baseball Cap (Black)",     category: "Clothing", subcategory: "Headgear", tags: ["cap","civilian"],               nominal: 8,  usage: ["Town"] },
  { classname: "WoolHat_Beige",          displayName: "Wool Hat (Beige)",         category: "Clothing", subcategory: "Headgear", tags: ["hat","civilian","wool"],        nominal: 8,  usage: ["Town","Farm"] },
  { classname: "BoonieHat_Camo",         displayName: "Boonie Hat (Camo)",        category: "Clothing", subcategory: "Headgear", tags: ["hat","military","boonie"],      nominal: 5,  usage: ["Military","Hunting"] },
  { classname: "FirefighterHelmet",      displayName: "Firefighter Helmet",       category: "Clothing", subcategory: "Headgear", tags: ["helmet","civilian","fire"],     nominal: 3,  usage: ["Industrial","Town"] },
  { classname: "PoliceHelmet",           displayName: "Police Helmet",            category: "Clothing", subcategory: "Headgear", tags: ["helmet","police"],              nominal: 3,  usage: ["Police"] },
  { classname: "NVGoggles",             displayName: "Night Vision Goggles",     category: "Clothing", subcategory: "Headgear", tags: ["nvg","military","rare"],        nominal: 1,  usage: ["Military"] },
  // ── Clothing — Vests ──────────────────────────────────────────────────────
  { classname: "PlateCarrierVest",       displayName: "Plate Carrier Vest",       category: "Clothing", subcategory: "Vests",    tags: ["vest","military","plate"],      nominal: 3,  usage: ["Military"] },
  { classname: "PressVest_Black",        displayName: "Press Vest (Black)",       category: "Clothing", subcategory: "Vests",    tags: ["vest","civilian","press"],      nominal: 4,  usage: ["Town"] },
  { classname: "HunterVest",            displayName: "Hunter Vest",              category: "Clothing", subcategory: "Vests",    tags: ["vest","civilian","hunter"],     nominal: 5,  usage: ["Hunting","Farm"] },
  { classname: "PoliceVest",            displayName: "Police Vest",              category: "Clothing", subcategory: "Vests",    tags: ["vest","police"],                nominal: 3,  usage: ["Police"] },
  { classname: "SmershVest",            displayName: "Smersh Vest",              category: "Clothing", subcategory: "Vests",    tags: ["vest","military","smersh"],     nominal: 3,  usage: ["Military"] },
  // ── Clothing — Gloves ─────────────────────────────────────────────────────
  { classname: "TacticalGloves_Black",   displayName: "Tactical Gloves (Black)", category: "Clothing", subcategory: "Gloves",   tags: ["gloves","military","tactical"], nominal: 5,  usage: ["Military"] },
  { classname: "WorkingGloves_Yellow",   displayName: "Working Gloves (Yellow)", category: "Clothing", subcategory: "Gloves",   tags: ["gloves","civilian","work"],     nominal: 6,  usage: ["Industrial","Farm"] },
  { classname: "LeatherGloves",          displayName: "Leather Gloves",          category: "Clothing", subcategory: "Gloves",   tags: ["gloves","civilian","leather"],  nominal: 6,  usage: ["Town"] },
  // ── Backpacks ─────────────────────────────────────────────────────────────
  { classname: "TaloonBag_Blue",         displayName: "Taloon Bag (Blue)",        category: "Containers", subcategory: "Backpacks", tags: ["backpack","civilian"],       nominal: 5,  usage: ["Town","Farm"] },
  { classname: "HuntingBag",            displayName: "Hunting Bag",              category: "Containers", subcategory: "Backpacks", tags: ["backpack","civilian","hunting"], nominal: 4, usage: ["Hunting"] },
  { classname: "MountainBag_Green",      displayName: "Mountain Bag (Green)",    category: "Containers", subcategory: "Backpacks", tags: ["backpack","civilian"],       nominal: 4,  usage: ["Town","Hunting"] },
  { classname: "AssaultBag_Black",       displayName: "Assault Bag (Black)",     category: "Containers", subcategory: "Backpacks", tags: ["backpack","military"],       nominal: 3,  usage: ["Military"] },
  { classname: "SmershBag",             displayName: "Smersh Bag",               category: "Containers", subcategory: "Backpacks", tags: ["backpack","military","smersh"], nominal: 3, usage: ["Military"] },
  { classname: "DrybagBackpack_Blue",    displayName: "Drybag Backpack (Blue)",  category: "Containers", subcategory: "Backpacks", tags: ["backpack","civilian","dry"],  nominal: 4,  usage: ["Town"] },
  { classname: "FieldBackpack_Camo",     displayName: "Field Backpack (Camo)",   category: "Containers", subcategory: "Backpacks", tags: ["backpack","military","field"], nominal: 3, usage: ["Military"] },
  { classname: "CoyoteBag_Camo",         displayName: "Coyote Bag (Camo)",       category: "Containers", subcategory: "Backpacks", tags: ["backpack","military"],       nominal: 3,  usage: ["Military"] },
  { classname: "PoliceBag",             displayName: "Police Bag",               category: "Containers", subcategory: "Backpacks", tags: ["backpack","police"],         nominal: 3,  usage: ["Police"] },
  // ── Food ──────────────────────────────────────────────────────────────────
  { classname: "RiceBag",               displayName: "Rice Bag",                 category: "Food", subcategory: "Dry Food",   tags: ["food","rice","dry"],            nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "FlourBag",              displayName: "Flour Bag",                category: "Food", subcategory: "Dry Food",   tags: ["food","flour","dry"],           nominal: 6,  usage: ["Town","Farm"] },
  { classname: "PastaBag",              displayName: "Pasta Bag",                category: "Food", subcategory: "Dry Food",   tags: ["food","pasta","dry"],           nominal: 6,  usage: ["Town","Farm"] },
  { classname: "BakedBeansCan",         displayName: "Baked Beans Can",          category: "Food", subcategory: "Canned",     tags: ["food","canned","beans"],        nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "TunaCan",              displayName: "Tuna Can",                  category: "Food", subcategory: "Canned",     tags: ["food","canned","tuna"],         nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "SardinesCan",           displayName: "Sardines Can",             category: "Food", subcategory: "Canned",     tags: ["food","canned","sardines"],     nominal: 8,  usage: ["Town","Farm"] },
  { classname: "SpaghettiCan",          displayName: "Spaghetti Can",            category: "Food", subcategory: "Canned",     tags: ["food","canned","spaghetti"],    nominal: 8,  usage: ["Town","Farm"] },
  { classname: "PeachesCan",            displayName: "Peaches Can",              category: "Food", subcategory: "Canned",     tags: ["food","canned","peaches"],      nominal: 6,  usage: ["Town","Farm"] },
  { classname: "TomatoSoupCan",         displayName: "Tomato Soup Can",          category: "Food", subcategory: "Canned",     tags: ["food","canned","soup"],         nominal: 6,  usage: ["Town","Farm"] },
  { classname: "Apple",                 displayName: "Apple",                    category: "Food", subcategory: "Fruit",      tags: ["food","fruit","apple"],         nominal: 10, usage: ["Farm","Hunting"] },
  { classname: "Pear",                  displayName: "Pear",                     category: "Food", subcategory: "Fruit",      tags: ["food","fruit","pear"],          nominal: 10, usage: ["Farm","Hunting"] },
  { classname: "Plum",                  displayName: "Plum",                     category: "Food", subcategory: "Fruit",      tags: ["food","fruit","plum"],          nominal: 10, usage: ["Farm","Hunting"] },
  { classname: "Tomato",               displayName: "Tomato",                   category: "Food", subcategory: "Vegetables", tags: ["food","vegetable","tomato"],    nominal: 8,  usage: ["Farm"] },
  { classname: "Zucchini",             displayName: "Zucchini",                 category: "Food", subcategory: "Vegetables", tags: ["food","vegetable","zucchini"],  nominal: 8,  usage: ["Farm"] },
  { classname: "Pumpkin",              displayName: "Pumpkin",                  category: "Food", subcategory: "Vegetables", tags: ["food","vegetable","pumpkin"],   nominal: 6,  usage: ["Farm"] },
  { classname: "WaterBottle",          displayName: "Water Bottle",             category: "Food", subcategory: "Drinks",     tags: ["drink","water","bottle"],       nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "Canteen",              displayName: "Canteen",                  category: "Food", subcategory: "Drinks",     tags: ["drink","water","canteen"],      nominal: 6,  usage: ["Military","Hunting"] },
  { classname: "SodaCan_Pipsi",        displayName: "Pipsi Can",               category: "Food", subcategory: "Drinks",     tags: ["drink","soda","pipsi"],         nominal: 6,  usage: ["Town"] },
  { classname: "SodaCan_Cola",         displayName: "Cola Can",                category: "Food", subcategory: "Drinks",     tags: ["drink","soda","cola"],          nominal: 6,  usage: ["Town"] },
  { classname: "SodaCan_Spite",        displayName: "Spite Can",               category: "Food", subcategory: "Drinks",     tags: ["drink","soda","spite"],         nominal: 6,  usage: ["Town"] },
  { classname: "Vodka",                displayName: "Vodka",                   category: "Food", subcategory: "Drinks",     tags: ["drink","alcohol","vodka"],      nominal: 4,  usage: ["Town","Farm"] },
  { classname: "Whiskey",              displayName: "Whiskey",                 category: "Food", subcategory: "Drinks",     tags: ["drink","alcohol","whiskey"],    nominal: 3,  usage: ["Town"] },
  // ── Medical ───────────────────────────────────────────────────────────────
  { classname: "FirstAidKit",          displayName: "First Aid Kit",           category: "Medical", subcategory: "Kits",       tags: ["medical","fak","kit"],          nominal: 4,  usage: ["Medic","Town","Military"] },
  { classname: "Bandage_Clean",        displayName: "Bandage (Clean)",         category: "Medical", subcategory: "Bandages",   tags: ["medical","bandage"],            nominal: 10, usage: ["Medic","Town","Military","Hunting"] },
  { classname: "BandageDressing",      displayName: "Bandage Dressing",        category: "Medical", subcategory: "Bandages",   tags: ["medical","bandage","dressing"], nominal: 8,  usage: ["Medic","Town","Military"] },
  { classname: "Rag",                  displayName: "Rag",                     category: "Medical", subcategory: "Bandages",   tags: ["medical","rag","craft"],        nominal: 12, usage: ["Town","Farm"] },
  { classname: "Morphine",             displayName: "Morphine Auto-Injector",  category: "Medical", subcategory: "Injectors",  tags: ["medical","morphine","fracture"], nominal: 4, usage: ["Medic","Military"] },
  { classname: "Epinephrine",          displayName: "Epinephrine Pen",         category: "Medical", subcategory: "Injectors",  tags: ["medical","epi","shock"],        nominal: 4,  usage: ["Medic","Military"] },
  { classname: "SalineIV_500",         displayName: "Saline IV Bag (500ml)",   category: "Medical", subcategory: "IV",         tags: ["medical","saline","blood"],     nominal: 3,  usage: ["Medic"] },
  { classname: "BloodBag_Empty",       displayName: "Blood Bag (Empty)",       category: "Medical", subcategory: "IV",         tags: ["medical","blood","transfusion"], nominal: 3, usage: ["Medic"] },
  { classname: "Tetracycline",         displayName: "Tetracycline Pills",      category: "Medical", subcategory: "Pills",      tags: ["medical","tetracycline","infection"], nominal: 4, usage: ["Medic","Town"] },
  { classname: "CharcoalTablets",      displayName: "Charcoal Tablets",        category: "Medical", subcategory: "Pills",      tags: ["medical","charcoal","poisoning"], nominal: 4, usage: ["Medic","Town"] },
  { classname: "VitaminBottle",        displayName: "Vitamin Bottle",          category: "Medical", subcategory: "Pills",      tags: ["medical","vitamins"],           nominal: 5,  usage: ["Medic","Town"] },
  { classname: "Splint",               displayName: "Splint",                  category: "Medical", subcategory: "Misc",       tags: ["medical","splint","fracture"],  nominal: 4,  usage: ["Medic","Town"] },
  { classname: "Defibrillator",        displayName: "Defibrillator",           category: "Medical", subcategory: "Misc",       tags: ["medical","defib","rare"],       nominal: 1,  usage: ["Medic"] },
  { classname: "BloodTestKit",         displayName: "Blood Test Kit",          category: "Medical", subcategory: "Misc",       tags: ["medical","blood","test"],       nominal: 3,  usage: ["Medic"] },
  { classname: "Thermometer",          displayName: "Thermometer",             category: "Medical", subcategory: "Misc",       tags: ["medical","thermometer"],        nominal: 4,  usage: ["Medic","Town"] },
  { classname: "Iodine",               displayName: "Iodine",                  category: "Medical", subcategory: "Misc",       tags: ["medical","iodine","disinfect"], nominal: 5,  usage: ["Medic","Town"] },
  { classname: "DisinfectantSpray",    displayName: "Disinfectant Spray",      category: "Medical", subcategory: "Misc",       tags: ["medical","disinfect"],          nominal: 4,  usage: ["Medic","Town"] },
  // ── Tools ─────────────────────────────────────────────────────────────────
  { classname: "Hacksaw",              displayName: "Hacksaw",                 category: "Tools", subcategory: "Saws",       tags: ["tool","saw","hacksaw"],         nominal: 5,  usage: ["Industrial","Town"] },
  { classname: "Hammer",               displayName: "Hammer",                  category: "Tools", subcategory: "Hand Tools", tags: ["tool","hammer","base building"], nominal: 6, usage: ["Industrial","Town","Farm"] },
  { classname: "Screwdriver",          displayName: "Screwdriver",             category: "Tools", subcategory: "Hand Tools", tags: ["tool","screwdriver"],           nominal: 6,  usage: ["Industrial","Town"] },
  { classname: "Pliers",               displayName: "Pliers",                  category: "Tools", subcategory: "Hand Tools", tags: ["tool","pliers"],                nominal: 5,  usage: ["Industrial","Town"] },
  { classname: "Wrench",               displayName: "Wrench",                  category: "Tools", subcategory: "Hand Tools", tags: ["tool","wrench","vehicle"],      nominal: 5,  usage: ["Industrial","Town"] },
  { classname: "Rope",                 displayName: "Rope",                    category: "Tools", subcategory: "Materials",  tags: ["tool","rope","craft"],          nominal: 6,  usage: ["Town","Farm","Hunting"] },
  { classname: "WireCoil",             displayName: "Wire Coil",               category: "Tools", subcategory: "Materials",  tags: ["tool","wire","fence","base"],   nominal: 4,  usage: ["Industrial","Farm"] },
  { classname: "Nails",                displayName: "Nails",                   category: "Tools", subcategory: "Materials",  tags: ["tool","nails","base building"], nominal: 6,  usage: ["Industrial","Town","Farm"] },
  { classname: "Duct_Tape",            displayName: "Duct Tape",               category: "Tools", subcategory: "Materials",  tags: ["tool","tape","repair","craft"], nominal: 6,  usage: ["Industrial","Town"] },
  { classname: "Epoxy",                displayName: "Epoxy Putty",             category: "Tools", subcategory: "Materials",  tags: ["tool","epoxy","repair"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "Sewing_Kit",           displayName: "Sewing Kit",              category: "Tools", subcategory: "Materials",  tags: ["tool","sewing","repair","clothing"], nominal: 5, usage: ["Town","Farm"] },
  { classname: "Sharpening_Stone",     displayName: "Sharpening Stone",        category: "Tools", subcategory: "Materials",  tags: ["tool","sharpen","knife"],       nominal: 5,  usage: ["Hunting","Farm"] },
  { classname: "Matches",              displayName: "Matches",                 category: "Tools", subcategory: "Fire",       tags: ["tool","fire","matches"],        nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "Lighter",              displayName: "Lighter",                 category: "Tools", subcategory: "Fire",       tags: ["tool","fire","lighter"],        nominal: 8,  usage: ["Town","Farm","Hunting"] },
  { classname: "Torch",                displayName: "Torch",                   category: "Tools", subcategory: "Fire",       tags: ["tool","fire","torch"],          nominal: 5,  usage: ["Town","Hunting"] },
  { classname: "Flashlight",           displayName: "Flashlight",              category: "Tools", subcategory: "Light",      tags: ["tool","light","flashlight"],    nominal: 6,  usage: ["Town","Military"] },
  { classname: "HeadTorch",            displayName: "Head Torch",              category: "Tools", subcategory: "Light",      tags: ["tool","light","headtorch"],     nominal: 5,  usage: ["Town","Military","Hunting"] },
  { classname: "CombinationLock",      displayName: "Combination Lock",        category: "Tools", subcategory: "Security",   tags: ["tool","lock","base building"],  nominal: 3,  usage: ["Town","Industrial"] },
  { classname: "PadLock",              displayName: "Padlock",                 category: "Tools", subcategory: "Security",   tags: ["tool","lock","base building"],  nominal: 3,  usage: ["Town","Industrial"] },
  { classname: "TireRepairKit",        displayName: "Tire Repair Kit",         category: "Tools", subcategory: "Vehicle",    tags: ["tool","tire","vehicle"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "BarbedWire",           displayName: "Barbed Wire",             category: "Tools", subcategory: "Security",   tags: ["tool","wire","base building"],  nominal: 3,  usage: ["Industrial","Military"] },
  // ── Vehicle Parts ─────────────────────────────────────────────────────────
  { classname: "CanisterGasoline",     displayName: "Gasoline Jerry Can",      category: "Vehicle Parts", subcategory: "Fluids",    tags: ["vehicle","fuel","gasoline"],  nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "CanisterOil",          displayName: "Oil Canister",            category: "Vehicle Parts", subcategory: "Fluids",    tags: ["vehicle","oil"],              nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "CarBattery",           displayName: "Car Battery",             category: "Vehicle Parts", subcategory: "Parts",     tags: ["vehicle","battery","car"],    nominal: 3,  usage: ["Industrial","Town"] },
  { classname: "TruckBattery",         displayName: "Truck Battery",           category: "Vehicle Parts", subcategory: "Parts",     tags: ["vehicle","battery","truck"],  nominal: 2,  usage: ["Industrial"] },
  { classname: "SparkPlug",            displayName: "Spark Plug",              category: "Vehicle Parts", subcategory: "Parts",     tags: ["vehicle","sparkplug"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "CarRadiator",          displayName: "Car Radiator",            category: "Vehicle Parts", subcategory: "Parts",     tags: ["vehicle","radiator"],         nominal: 3,  usage: ["Industrial","Town"] },
  { classname: "CivSedanWheel",        displayName: "Sedan Wheel",             category: "Vehicle Parts", subcategory: "Wheels",    tags: ["vehicle","wheel","sedan"],    nominal: 3,  usage: ["Industrial","Town"] },
  { classname: "Offroad_02_Wheel",     displayName: "Offroad Wheel",           category: "Vehicle Parts", subcategory: "Wheels",    tags: ["vehicle","wheel","offroad"],  nominal: 3,  usage: ["Industrial"] },
  { classname: "Truck_01_Wheel",       displayName: "Truck Wheel",             category: "Vehicle Parts", subcategory: "Wheels",    tags: ["vehicle","wheel","truck"],    nominal: 2,  usage: ["Industrial"] },
  { classname: "CarKey",               displayName: "Car Key",                 category: "Vehicle Parts", subcategory: "Parts",     tags: ["vehicle","key","car"],        nominal: 3,  usage: ["Town","Industrial"] },
  // ── Electronics & Navigation ──────────────────────────────────────────────
  { classname: "Compass",              displayName: "Compass",                 category: "Electronics", subcategory: "Navigation", tags: ["nav","compass"],              nominal: 5,  usage: ["Military","Hunting","Town"] },
  { classname: "Map",                  displayName: "Map",                     category: "Electronics", subcategory: "Navigation", tags: ["nav","map"],                  nominal: 5,  usage: ["Military","Hunting","Town"] },
  { classname: "GPS",                  displayName: "GPS Receiver",            category: "Electronics", subcategory: "Navigation", tags: ["nav","gps","military"],       nominal: 2,  usage: ["Military"] },
  { classname: "Binoculars",           displayName: "Binoculars",              category: "Electronics", subcategory: "Navigation", tags: ["nav","binoculars","optic"],   nominal: 4,  usage: ["Military","Hunting"] },
  { classname: "Radio",                displayName: "Portable Radio",          category: "Electronics", subcategory: "Communication", tags: ["radio","communication"],    nominal: 4,  usage: ["Military","Town"] },
  { classname: "Walkie_Talkie",        displayName: "Walkie Talkie",           category: "Electronics", subcategory: "Communication", tags: ["radio","walkie","communication"], nominal: 4, usage: ["Military","Town"] },
  { classname: "Battery9V",            displayName: "9V Battery",              category: "Electronics", subcategory: "Batteries",  tags: ["battery","9v","electronics"], nominal: 6,  usage: ["Town","Industrial"] },
  { classname: "BatteryD",             displayName: "D Battery",               category: "Electronics", subcategory: "Batteries",  tags: ["battery","d","electronics"],  nominal: 6,  usage: ["Town","Industrial"] },
  // ── Base Building ─────────────────────────────────────────────────────────
  { classname: "WoodenLog",            displayName: "Wooden Log",              category: "Base Building", subcategory: "Materials", tags: ["base","log","wood","craft"],  nominal: 0,  usage: ["Farm","Hunting"] },
  { classname: "WoodenPlank",          displayName: "Wooden Plank",            category: "Base Building", subcategory: "Materials", tags: ["base","plank","wood"],        nominal: 0,  usage: ["Farm","Town"] },
  { classname: "MetalWire",            displayName: "Metal Wire",              category: "Base Building", subcategory: "Materials", tags: ["base","wire","metal"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "MetalPlate",           displayName: "Metal Plate",             category: "Base Building", subcategory: "Materials", tags: ["base","plate","metal"],       nominal: 3,  usage: ["Industrial"] },
  { classname: "Nails",                displayName: "Nails",                   category: "Base Building", subcategory: "Materials", tags: ["base","nails","wood"],        nominal: 6,  usage: ["Industrial","Town","Farm"] },
  { classname: "FenceKit",             displayName: "Fence Kit",               category: "Base Building", subcategory: "Kits",      tags: ["base","fence","kit"],         nominal: 3,  usage: ["Industrial","Farm"] },
  { classname: "WatchtowerKit",        displayName: "Watchtower Kit",          category: "Base Building", subcategory: "Kits",      tags: ["base","watchtower","kit"],    nominal: 2,  usage: ["Military","Industrial"] },
  { classname: "TerritoryFlagKit",     displayName: "Territory Flag Kit",      category: "Base Building", subcategory: "Kits",      tags: ["base","flag","territory"],    nominal: 2,  usage: ["Military","Town"] },
  // ── Misc / Crafting ───────────────────────────────────────────────────────
  { classname: "Knife",                displayName: "Knife",                   category: "Misc", subcategory: "Crafting",   tags: ["craft","knife","tool"],         nominal: 6,  usage: ["Town","Hunting","Farm"] },
  { classname: "Scissors",             displayName: "Scissors",                category: "Misc", subcategory: "Crafting",   tags: ["craft","scissors","tool"],      nominal: 5,  usage: ["Town","Farm"] },
  { classname: "Burlap_Sack",          displayName: "Burlap Sack",             category: "Misc", subcategory: "Crafting",   tags: ["craft","sack","bag"],           nominal: 5,  usage: ["Farm","Town"] },
  { classname: "Plastic_Bottle",       displayName: "Plastic Bottle",          category: "Misc", subcategory: "Crafting",   tags: ["craft","bottle","plastic"],     nominal: 6,  usage: ["Town","Farm"] },
  { classname: "Notebook",             displayName: "Notebook",                category: "Misc", subcategory: "Books",      tags: ["book","notebook","misc"],       nominal: 5,  usage: ["Town"] },
  { classname: "Book",                 displayName: "Book",                    category: "Misc", subcategory: "Books",      tags: ["book","misc"],                  nominal: 5,  usage: ["Town"] },
  { classname: "Spraypaint_Black",     displayName: "Spray Paint (Black)",     category: "Misc", subcategory: "Crafting",   tags: ["craft","paint","spray"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "Spraypaint_Green",     displayName: "Spray Paint (Green)",     category: "Misc", subcategory: "Crafting",   tags: ["craft","paint","spray"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "Spraypaint_Red",       displayName: "Spray Paint (Red)",       category: "Misc", subcategory: "Crafting",   tags: ["craft","paint","spray"],        nominal: 4,  usage: ["Industrial","Town"] },
  { classname: "Handcuffs",            displayName: "Handcuffs",               category: "Misc", subcategory: "Misc",       tags: ["misc","handcuffs","police"],    nominal: 3,  usage: ["Police","Military"] },
  { classname: "HandcuffsKey",         displayName: "Handcuff Key",            category: "Misc", subcategory: "Misc",       tags: ["misc","key","handcuffs"],       nominal: 3,  usage: ["Police","Military"] },
  { classname: "Lockpick",             displayName: "Lockpick",                category: "Misc", subcategory: "Misc",       tags: ["misc","lockpick","tool"],       nominal: 2,  usage: ["Town"] },
  { classname: "Fishing_Hook",         displayName: "Fishing Hook",            category: "Misc", subcategory: "Fishing",    tags: ["fishing","hook","craft"],       nominal: 5,  usage: ["Hunting","Farm"] },
  { classname: "Fishing_Line",         displayName: "Fishing Line",            category: "Misc", subcategory: "Fishing",    tags: ["fishing","line","craft"],       nominal: 4,  usage: ["Hunting","Farm"] },
  { classname: "FishingRod",           displayName: "Fishing Rod",             category: "Misc", subcategory: "Fishing",    tags: ["fishing","rod"],                nominal: 3,  usage: ["Hunting","Farm"] },
  { classname: "BearTrap",             displayName: "Bear Trap",               category: "Misc", subcategory: "Traps",      tags: ["trap","bear","hunting"],        nominal: 3,  usage: ["Hunting","Farm"] },
  { classname: "MouseTrap",            displayName: "Mouse Trap",              category: "Misc", subcategory: "Traps",      tags: ["trap","mouse","craft"],         nominal: 4,  usage: ["Farm","Town"] },
  { classname: "Seed_Tomato",          displayName: "Tomato Seeds",            category: "Misc", subcategory: "Farming",    tags: ["farm","seed","tomato"],         nominal: 5,  usage: ["Farm"] },
  { classname: "Seed_Zucchini",        displayName: "Zucchini Seeds",          category: "Misc", subcategory: "Farming",    tags: ["farm","seed","zucchini"],       nominal: 5,  usage: ["Farm"] },
  { classname: "Seed_Pumpkin",         displayName: "Pumpkin Seeds",           category: "Misc", subcategory: "Farming",    tags: ["farm","seed","pumpkin"],        nominal: 5,  usage: ["Farm"] },
];

// ── Derived exports ────────────────────────────────────────────────────────────
export const DAYZ_LOOT_CATEGORIES = [...new Set(DAYZ_LOOT_DB.map(e => e.category))];
export const DAYZ_LOOT_SUBCATEGORIES = [...new Set(DAYZ_LOOT_DB.map(e => e.subcategory))];

/** Items suitable for build/vehicle loot (excludes base building materials, farming seeds) */
export const BUILD_LOOT_ITEMS = DAYZ_LOOT_DB.filter(e =>
  !["Base Building", "Misc"].includes(e.category) ||
  (e.category === "Misc" && !["Farming", "Books"].includes(e.subcategory))
);

/** Items by build type for themed loot placement */
export const LOOT_BY_TYPE = {
  military:  DAYZ_LOOT_DB.filter(e => e.usage?.includes("Military")),
  civilian:  DAYZ_LOOT_DB.filter(e => e.usage?.some(u => ["Town","Farm","Hunting"].includes(u))),
  medical:   DAYZ_LOOT_DB.filter(e => e.usage?.includes("Medic") || e.category === "Medical"),
  industrial:DAYZ_LOOT_DB.filter(e => e.usage?.includes("Industrial") || e.category === "Vehicle Parts"),
  mixed:     DAYZ_LOOT_DB.filter(e => ["Weapons","Ammo","Medical","Food","Tools"].includes(e.category)),
};
