export interface DayzObject {
  value: string;
  label: string;
  group: string;
}

export const DAYZ_OBJECTS: DayzObject[] = [

  // ─── Arena & Castle Walls ─────────────────────────────────────────────────
  { value: "Land_Castle_Wall_3m_DE",      label: "Castle Stone Wall 3m ★ BEST ARENA WALL",   group: "Arena & Castle Walls" },
  { value: "Land_Castle_Wall_6m_DE",      label: "Castle Stone Wall 6m (tall)",               group: "Arena & Castle Walls" },
  { value: "Land_Castle_Gate_DE",         label: "Castle Gate Archway",                        group: "Arena & Castle Walls" },
  { value: "Land_Castle_Bastion_DE",      label: "Castle Bastion Section",                     group: "Arena & Castle Walls" },
  { value: "Land_Castle_Tower_Round_DE",  label: "Castle Round Tower",                         group: "Arena & Castle Walls" },
  { value: "Land_Castle_Tower_Square_DE", label: "Castle Square Tower",                        group: "Arena & Castle Walls" },
  { value: "Land_Wall_Stone_3m_DE",       label: "Stone Ruin Wall 3m",                         group: "Arena & Castle Walls" },
  { value: "Land_Wall_Stone_6m_DE",       label: "Stone Ruin Wall 6m",                         group: "Arena & Castle Walls" },
  { value: "Land_Wall_Stone_Corner_DE",   label: "Stone Ruin Corner",                          group: "Arena & Castle Walls" },
  { value: "Land_Wall_Stone_Gate_DE",     label: "Stone Ruin Gate",                            group: "Arena & Castle Walls" },
  { value: "Land_Wall_Concrete_4m_DE",    label: "Concrete Wall 4m ★ BEST MODERN",            group: "Arena & Castle Walls" },
  { value: "Land_Wall_Concrete_8m_DE",    label: "Concrete Wall 8m (long run)",                group: "Arena & Castle Walls" },
  { value: "Land_Wall_Brick_4m_DE",       label: "Brick Wall 4m",                              group: "Arena & Castle Walls" },
  { value: "Land_Wall_Brick_8m_DE",       label: "Brick Wall 8m",                              group: "Arena & Castle Walls" },
  { value: "Land_HBarrier_5m_DE",         label: "HESCO Barrier 5m ★ BEST MILITARY",          group: "Arena & Castle Walls" },
  { value: "Land_HBarrier_10m_DE",        label: "HESCO Barrier 10m (long)",                   group: "Arena & Castle Walls" },
  { value: "Land_HBarrier_Corner_DE",     label: "HESCO Barrier Corner",                       group: "Arena & Castle Walls" },
  { value: "Land_BarrierConcrete_01_DE",  label: "Jersey Barrier Long ★ CLASSIC",             group: "Arena & Castle Walls" },
  { value: "Land_BarrierConcrete_02_DE",  label: "Jersey Barrier Short",                       group: "Arena & Castle Walls" },
  { value: "Land_Fence_Palisade_4m_DE",   label: "Wooden Palisade 4m",                         group: "Arena & Castle Walls" },
  { value: "Land_Fence_Palisade_8m_DE",   label: "Wooden Palisade 8m",                         group: "Arena & Castle Walls" },
  { value: "Land_Fence_Palisade_Gate_DE", label: "Palisade Gate",                              group: "Arena & Castle Walls" },
  { value: "Land_Sandbag_Wall_DE",        label: "Sandbag Wall",                               group: "Arena & Castle Walls" },
  { value: "Land_Sandbag_Corner_DE",      label: "Sandbag Corner",                             group: "Arena & Castle Walls" },
  { value: "Land_BarbedWire_01_DE",       label: "Barbed Wire (wall topper)",                  group: "Arena & Castle Walls" },

  // ─── Wall Gates & Fence Gates ─────────────────────────────────────────────
  { value: "Land_Wall_Gate_FenG",           label: "Chain Gate Green (closed)",                group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenG_Open",      label: "Chain Gate Green (open)",                  group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenG_Big",       label: "Chain Gate Green Big (closed) ★",         group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenG_Big_L",     label: "Chain Gate Green Big Left leaf",           group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenG_Big_R",     label: "Chain Gate Green Big Right leaf",          group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenG_Big_Open",  label: "Chain Gate Green Big (open)",              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR",           label: "Chain Gate Red (closed)",                  group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR_Open",      label: "Chain Gate Red (open)",                    group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR_Big",       label: "Chain Gate Red Big (closed)",              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR_Big_L",     label: "Chain Gate Red Big Left leaf",             group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR_Big_R",     label: "Chain Gate Red Big Right leaf",            group: "Gates & Fences" },
  { value: "Land_Wall_Gate_FenR_Big_Open",  label: "Chain Gate Red Big (open)",               group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Fen2_L",         label: "Chain Gate 2 Left leaf",                   group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Fen2_R",         label: "Chain Gate 2 Right leaf",                  group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind1_L",         label: "Industrial Gate 1 Left leaf",              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind1_R",         label: "Industrial Gate 1 Right leaf",             group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2A_L",        label: "Industrial Gate 2A Left leaf",             group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2A_R",        label: "Industrial Gate 2A Right leaf",            group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2B_L",        label: "Industrial Gate 2B Left leaf",             group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2B_R",        label: "Industrial Gate 2B Right leaf",            group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2Rail_L",     label: "Industrial Rail Gate Left",                group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Ind2Rail_R",     label: "Industrial Rail Gate Right",               group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Village",        label: "Village Gate ★ Civilian look",            group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Camp",           label: "Camp Gate (military camp)",                group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Wood1",          label: "Wood Gate 1",                              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Wood2",          label: "Wood Gate 2",                              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Wood3",          label: "Wood Gate 3",                              group: "Gates & Fences" },
  { value: "Land_Wall_Gate_Wood4",          label: "Wood Gate 4",                              group: "Gates & Fences" },
  { value: "Land_Fence_Barbed",             label: "Barbed Wire Fence",                        group: "Gates & Fences" },
  { value: "Land_Fence_Barbed_Wire",        label: "Barbed Wire Coil",                         group: "Gates & Fences" },
  { value: "Land_Prison_Wall_Large",        label: "Prison Wall Large ★",                     group: "Gates & Fences" },
  { value: "Land_Dam_Concrete_20_Floodgate",label: "Dam Floodgate (huge)",                    group: "Gates & Fences" },
  { value: "Land_Castle_Wall1_20",          label: "Castle Wall Type1 20m",                   group: "Gates & Fences" },
  { value: "Land_Castle_Wall1_Corner1",     label: "Castle Wall Type1 Corner",                group: "Gates & Fences" },
  { value: "Land_Castle_Wall2_30",          label: "Castle Wall Type2 30m (tall)",             group: "Gates & Fences" },
  { value: "Land_Castle_Wall2_Corner1",     label: "Castle Wall Type2 Corner",                group: "Gates & Fences" },
  { value: "Land_Castle_WallS_10",          label: "Castle Wall Short 10m",                   group: "Gates & Fences" },
  { value: "Land_Castle_WallS_5_D",         label: "Castle Wall Short 5m (damaged)",           group: "Gates & Fences" },

  // ─── Military Buildings ────────────────────────────────────────────────────
  { value: "Land_Mil_Barracks1",             label: "Military Barracks 1 (Officer)",          group: "Military Buildings" },
  { value: "Land_Mil_Barracks2",             label: "Military Barracks 2 (Single Room)",      group: "Military Buildings" },
  { value: "Land_Mil_Barracks3",             label: "Military Barracks 3 (Narrow)",           group: "Military Buildings" },
  { value: "Land_Mil_Barracks4",             label: "Military Barracks 4 (L-Shaped)",         group: "Military Buildings" },
  { value: "Land_Mil_Barracks5",             label: "Military Barracks 5 (Prison)",           group: "Military Buildings" },
  { value: "Land_Mil_Barracks6",             label: "Military Barracks 6 (Two-Storey)",       group: "Military Buildings" },
  { value: "Land_Mil_Barracks_Round",        label: "Military Barracks Round (Regimental)",   group: "Military Buildings" },
  { value: "Land_Mil_Barracks_HQ_DE",        label: "Military Barracks HQ (newer _DE)",       group: "Military Buildings" },
  { value: "Land_Mil_Barracks_DE",           label: "Military Barracks (newer _DE)",          group: "Military Buildings" },
  { value: "Land_Mil_Guardhouse1",           label: "Military Guardhouse 1",                  group: "Military Buildings" },
  { value: "Land_Mil_Guardhouse2",           label: "Military Guardhouse 2",                  group: "Military Buildings" },
  { value: "Land_Mil_Guardhouse_DE",         label: "Military Guardhouse (newer _DE)",        group: "Military Buildings" },
  { value: "Land_Mil_GuardShed",             label: "Military Guard Shed (small outpost)",    group: "Military Buildings" },
  { value: "Land_Mil_Tower_Small",           label: "Military Tower Small",                   group: "Military Buildings" },
  { value: "Land_Mil_GuardTower",            label: "Military Guard Tower ★",                group: "Military Buildings" },
  { value: "Land_Mil_WatchtowerL_DE",        label: "Mil Watchtower Low (_DE)",              group: "Military Buildings" },
  { value: "Land_Mil_WatchtowerH_DE",        label: "Mil Watchtower High (_DE)",             group: "Military Buildings" },
  { value: "Land_Mil_Fortified_Nest_Big",    label: "Fortified Nest Big (MG position)",      group: "Military Buildings" },
  { value: "Land_Mil_Fortified_Nest_Small",  label: "Fortified Nest Small",                  group: "Military Buildings" },
  { value: "Land_Mil_Fortified_Nest_Watchtower", label: "Fortified Watchtower",              group: "Military Buildings" },
  { value: "Land_Mil_ATC_Small",             label: "ATC Tower Small (Airport)",             group: "Military Buildings" },
  { value: "Land_Mil_ATC_Big",               label: "ATC Tower Big (Main airport) ★",       group: "Military Buildings" },
  { value: "Land_Mil_Airfield_HQ",           label: "Airfield Headquarters Building",         group: "Military Buildings" },
  { value: "Land_Mil_AircraftShelter",       label: "Aircraft Shelter (hardened)",           group: "Military Buildings" },
  { value: "Land_Mil_CamoNet_Roof_east",     label: "Camo Net Roof (East style)",            group: "Military Buildings" },
  { value: "Land_Mil_ReinforcedTank1",       label: "Reinforced Tank 1 (concrete shelter)",  group: "Military Buildings" },
  { value: "Land_Mil_ReinforcedTank2",       label: "Reinforced Tank 2 (concrete shelter)",  group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big_DE",           label: "Military Tent Big (_DE)",               group: "Military Buildings" },
  { value: "Land_Mil_Tent_Small_DE",         label: "Military Tent Small (_DE)",             group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big1_1",           label: "Mil Tent Big Type 1 Variant 1",         group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big1_2",           label: "Mil Tent Big Type 1 Variant 2",         group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big2_1",           label: "Mil Tent Big Type 2 Variant 1",         group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big3",             label: "Mil Tent Big Type 3",                   group: "Military Buildings" },
  { value: "Land_Mil_Tent_Big4",             label: "Mil Tent Big Type 4",                   group: "Military Buildings" },
  { value: "Land_Bunker_DE",                 label: "Concrete Bunker",                        group: "Military Buildings" },
  { value: "Land_Bunker_Small_DE",           label: "Concrete Bunker Small",                 group: "Military Buildings" },

  // ─── Airfield Structures ─────────────────────────────────────────────────
  { value: "Land_Airfield_Hangar_Green",       label: "Airfield Hangar Green ★",           group: "Airfield Structures" },
  { value: "Land_Airfield_ServiceHangar_R",    label: "Service Hangar Right",               group: "Airfield Structures" },
  { value: "Land_Airfield_ServiceHangar_L",    label: "Service Hangar Left",                group: "Airfield Structures" },
  { value: "Land_Airfield_Radar_Tall",         label: "Airfield Radar Tall",                group: "Airfield Structures" },
  { value: "Land_Airfield_Small_Control",      label: "Small Airfield Control Tower",       group: "Airfield Structures" },
  { value: "Land_Airfield_Small_Hangar",       label: "Small Airfield Hangar",              group: "Airfield Structures" },

  // ─── Tisy Military Base Specific ─────────────────────────────────────────
  { value: "Land_Tisy_Barracks",              label: "Tisy Barracks (Regimental) ★",      group: "Tisy Military Base" },
  { value: "Land_Tisy_HQ",                   label: "Tisy Headquarters Building",          group: "Tisy Military Base" },
  { value: "Land_Tisy_KitchenRoom",          label: "Tisy Kitchen Block",                  group: "Tisy Military Base" },
  { value: "Land_Tisy_Garages",              label: "Tisy Garages Row",                    group: "Tisy Military Base" },
  { value: "Land_Tisy_RadarPlatform_Top",    label: "Tisy Radar Platform Top",             group: "Tisy Military Base" },
  { value: "Land_Tisy_RadarB_Base",          label: "Tisy Radar B Base",                   group: "Tisy Military Base" },
  { value: "Land_Tisy_RadarB_Antenna",       label: "Tisy Radar Antenna",                  group: "Tisy Military Base" },
  { value: "Land_Tisy_Base_cooler",          label: "Tisy Base Cooler Unit",               group: "Tisy Military Base" },

  // ─── Crates & Storage ────────────────────────────────────────────────────
  { value: "WoodenCrate",                    label: "Wooden Crate ★ best loot/obstacle",  group: "Crates & Storage" },
  { value: "WoodenCrateSmall",               label: "Wooden Crate Small",                 group: "Crates & Storage" },
  { value: "PalletBox_DE",                   label: "Pallet Box (stackable) ★",           group: "Crates & Storage" },
  { value: "Pallet_EP1",                     label: "Wooden Pallet (flat)",               group: "Crates & Storage" },
  { value: "GarbageContainer_Yellow_DE",     label: "Garbage Container Yellow",           group: "Crates & Storage" },
  { value: "GarbageContainer_Green_DE",      label: "Garbage Container Green",            group: "Crates & Storage" },
  { value: "Barrel_Blue",                    label: "Barrel Blue",                        group: "Crates & Storage" },
  { value: "Barrel_Green",                   label: "Barrel Green",                       group: "Crates & Storage" },
  { value: "Barrel_Yellow",                  label: "Barrel Yellow",                      group: "Crates & Storage" },
  { value: "Barrel_Red",                     label: "Barrel Red",                         group: "Crates & Storage" },
  { value: "Land_GasTank_Cylindrical",       label: "Gas Tank (cylinder)",                group: "Crates & Storage" },
  { value: "Land_GasTank_Big",               label: "Gas Tank (big)",                     group: "Crates & Storage" },

  // ─── Steps & Access ──────────────────────────────────────────────────────
  { value: "Land_PierLadder_DE",             label: "Pier Ladder (climb) ★ best step",   group: "Steps & Access" },
  { value: "Land_Stairs_Concrete_DE",        label: "Concrete Stairs (set)",              group: "Steps & Access" },
  { value: "Land_Concrete_Step_DE",          label: "Concrete Step (single)",             group: "Steps & Access" },
  { value: "Land_BarrierConcrete_02_DE",     label: "Jersey Barrier Short (use as step)", group: "Steps & Access" },
  { value: "Land_BarrierConcrete_01_DE",     label: "Jersey Barrier Long (ground level)", group: "Steps & Access" },
  { value: "Land_Platform_Mil_DE",           label: "Military Platform",                  group: "Steps & Access" },
  { value: "Land_Pier_DE",                   label: "Pier Section (raised walkway)",      group: "Steps & Access" },
  { value: "Land_Pier_Long_DE",              label: "Pier Section Long (ramp/walkway)",   group: "Steps & Access" },
  { value: "Land_Ladder",                    label: "Ladder (standalone)",                group: "Steps & Access" },
  { value: "Land_Ladder_Half",               label: "Ladder Half-height",                 group: "Steps & Access" },

  // ─── Containers ──────────────────────────────────────────────────────────
  { value: "StaticObj_Container_1D",         label: "Shipping Container 1D",              group: "Containers" },
  { value: "StaticObj_Container_1C",         label: "Shipping Container 1C",              group: "Containers" },
  { value: "Land_Container_1Bo_DE",          label: "Container 1Bo (dark)",               group: "Containers" },
  { value: "Land_Container_1Aoh_DE",         label: "Container 1Aoh",                     group: "Containers" },
  { value: "Land_Container_1Aoh",            label: "Container 1Aoh (classic)",           group: "Containers" },
  { value: "Land_Container_1Bo",             label: "Container 1Bo (classic dark)",       group: "Containers" },
  { value: "Land_Container_1Mo",             label: "Container 1Mo (military olive)",     group: "Containers" },
  { value: "Land_Container_1Moh",            label: "Container 1Moh (mil open-top)",      group: "Containers" },

  // ─── Wrecks & Abandoned Vehicles ─────────────────────────────────────────
  { value: "Land_Wreck_V3S_DE",              label: "Wreck V3S Truck",                    group: "Wrecks" },
  { value: "Land_Wreck_Ural_DE",             label: "Wreck Ural Truck",                   group: "Wrecks" },
  { value: "Land_Wreck_Ikarus_DE",           label: "Wreck Ikarus Bus",                   group: "Wrecks" },
  { value: "Land_Wreck_Ikarus",              label: "Wreck Ikarus Bus (classic)",         group: "Wrecks" },
  { value: "Land_Train_Wagon_Box_DE",        label: "Train Wagon Box (_DE)",              group: "Wrecks" },
  { value: "Land_Train_Wagon_Box_Mil_DE",    label: "Train Wagon Mil (_DE)",              group: "Wrecks" },
  { value: "Land_Train_Wagon_Box",           label: "Train Wagon Box (cargo)",            group: "Wrecks" },
  { value: "Land_Train_Wagon_Tanker",        label: "Train Wagon Tanker",                 group: "Wrecks" },
  { value: "Land_Train_742_Blue",            label: "Train Locomotive Blue",              group: "Wrecks" },
  { value: "Land_Train_742_Red",             label: "Train Locomotive Red",               group: "Wrecks" },
  { value: "Land_Wreck_Trailer_Closed_DE",   label: "Trailer Closed",                     group: "Wrecks" },
  { value: "Land_Wreck_hb01_aban1_blue_DE",  label: "Wreck Hatchback Blue",              group: "Wrecks" },
  { value: "Land_Wreck_sed01_aban1_black_DE",label: "Wreck Sedan Black",                 group: "Wrecks" },
  { value: "Land_Wreck_offroad02_aban1_DE",  label: "Wreck M1025 (Offroad_02)",          group: "Wrecks" },
  { value: "Land_Boat_Small9_DE",            label: "Boat (static — not driveable)",      group: "Wrecks" },
  { value: "Land_Wreck_T72_DE",              label: "Wreck T72 Tank",                     group: "Wrecks" },
  { value: "Land_Wreck_BTR_DE",              label: "Wreck BTR APC",                      group: "Wrecks" },
  { value: "Land_Wreck_heli_MI8_DE",         label: "Wreck MI-8 Helicopter",             group: "Wrecks" },
  { value: "Land_Wreck_C130J",               label: "Wreck C-130J Hercules ★",          group: "Wrecks" },
  { value: "Land_Wreck_Uaz",                 label: "Wreck UAZ Jeep",                     group: "Wrecks" },
  { value: "Land_Wreck_Lada_Green",          label: "Wreck Lada Green",                   group: "Wrecks" },
  { value: "Land_Wreck_Lada_Red",            label: "Wreck Lada Red",                     group: "Wrecks" },
  { value: "Land_Wreck_Volha_Blue",          label: "Wreck Volha Blue (Sedan)",           group: "Wrecks" },
  { value: "Land_Wreck_Volha_Grey",          label: "Wreck Volha Grey",                   group: "Wrecks" },
  { value: "Land_Wreck_Volha_Police",        label: "Wreck Volha Police Car",             group: "Wrecks" },
  { value: "Land_Wreck_hb01_aban1_police",   label: "Wreck Hatchback Police",            group: "Wrecks" },
  { value: "Land_Wreck_hb01_aban2_police",   label: "Wreck Hatchback Police 2",          group: "Wrecks" },
  { value: "Land_Wreck_sed01_aban1_police",  label: "Wreck Sedan Police",                group: "Wrecks" },
  { value: "Land_Wreck_S1023_Blue",          label: "Wreck S1023 Van Blue",              group: "Wrecks" },
  { value: "Land_Wreck_S1023_Beige",         label: "Wreck S1023 Van Beige",             group: "Wrecks" },
  { value: "Land_Wreck_Caravan_MGreen",      label: "Wreck Caravan Metal Green",         group: "Wrecks" },
  { value: "Land_Wreck_Caravan_MRust",       label: "Wreck Caravan Metal Rust",          group: "Wrecks" },
  { value: "Land_Wreck_Caravan_WBrown",      label: "Wreck Caravan Wood Brown",          group: "Wrecks" },
  { value: "Land_Wreck_Caravan_WGreen",      label: "Wreck Caravan Wood Green",          group: "Wrecks" },
  { value: "Wreck_UH1Y",                     label: "Wreck UH-1Y Venom Helicopter",      group: "Wrecks" },
  { value: "Wreck_Mi8",                      label: "Wreck Mi-8 Hip Helicopter",          group: "Wrecks" },

  // ─── Boats & Ships ───────────────────────────────────────────────────────
  { value: "Land_Boat_Small1",               label: "Small Boat 1 (rowboat)",             group: "Boats & Ships" },
  { value: "Land_Boat_Small2",               label: "Small Boat 2",                       group: "Boats & Ships" },
  { value: "Land_Boat_Small3",               label: "Small Boat 3",                       group: "Boats & Ships" },
  { value: "Land_Boathouse",                 label: "Boathouse (full building) ★",       group: "Boats & Ships" },
  { value: "Land_Lighthouse",                label: "Lighthouse ★ iconic",              group: "Boats & Ships" },
  { value: "Land_Ship_Big_FrontA",           label: "Ship Bow Section A",                 group: "Boats & Ships" },
  { value: "Land_Ship_Big_FrontB",           label: "Ship Bow Section B",                 group: "Boats & Ships" },
  { value: "Land_Ship_Big_BackA",            label: "Ship Stern Section A",               group: "Boats & Ships" },
  { value: "Land_Ship_Big_BackB",            label: "Ship Stern Section B",               group: "Boats & Ships" },
  { value: "Land_Ship_Big_Castle",           label: "Ship Castle/Bridge Section",         group: "Boats & Ships" },
  { value: "Land_Pier_Crane_A",              label: "Pier Crane A",                       group: "Boats & Ships" },
  { value: "Land_Pier_Crane_B",              label: "Pier Crane B",                       group: "Boats & Ships" },

  // ─── Industrial Buildings ─────────────────────────────────────────────────
  { value: "Land_CementWorks_ExpeditionA",   label: "Cement Works A (large hall) ★",    group: "Industrial Buildings" },
  { value: "Land_CementWorks_ExpeditionB",   label: "Cement Works B",                    group: "Industrial Buildings" },
  { value: "Land_CementWorks_ExpeditionC",   label: "Cement Works C",                    group: "Industrial Buildings" },
  { value: "Land_CementWorks_Hall",          label: "Cement Works Hall",                 group: "Industrial Buildings" },
  { value: "Land_CementWorks_Hall1",         label: "Cement Works Hall 1",               group: "Industrial Buildings" },
  { value: "Land_CementWorks_Hall2_Brick",   label: "Cement Works Hall 2 Brick",         group: "Industrial Buildings" },
  { value: "Land_CementWorks_Hall2_Grey",    label: "Cement Works Hall 2 Grey",          group: "Industrial Buildings" },
  { value: "Land_CementWorks_MillA",         label: "Cement Works Mill A",               group: "Industrial Buildings" },
  { value: "Land_CementWorks_MillB",         label: "Cement Works Mill B",               group: "Industrial Buildings" },
  { value: "Land_CementWorks_MillC",         label: "Cement Works Mill C",               group: "Industrial Buildings" },
  { value: "Land_CementWorks_RotFurnace",    label: "Cement Works Rotary Furnace",       group: "Industrial Buildings" },
  { value: "Land_CementWorks_SiloBig1A",     label: "Cement Works Silo ★",             group: "Industrial Buildings" },
  { value: "Land_Cementworks_Conveyorhall",  label: "Cement Works Conveyor Hall",        group: "Industrial Buildings" },
  { value: "Land_CoalPlant_Main",            label: "Coal Plant Main ★",               group: "Industrial Buildings" },
  { value: "Land_Quarry_Main",               label: "Quarry Main Building ★",          group: "Industrial Buildings" },
  { value: "Land_Construction_Building",     label: "Construction Building",             group: "Industrial Buildings" },
  { value: "Land_Construction_Crane",        label: "Construction Crane",                group: "Industrial Buildings" },
  { value: "Land_Construction_House1",       label: "Construction House 1",              group: "Industrial Buildings" },
  { value: "Land_Construction_House2",       label: "Construction House 2",              group: "Industrial Buildings" },
  { value: "Land_Factory_Lathes",            label: "Factory Lathes (workshop) ★",     group: "Industrial Buildings" },
  { value: "Land_Factory_Small",             label: "Factory Small",                     group: "Industrial Buildings" },
  { value: "Land_Mine_Building",             label: "Mine Building",                     group: "Industrial Buildings" },
  { value: "Land_Sawmill_Building",          label: "Sawmill Building ★",              group: "Industrial Buildings" },
  { value: "Land_Sawmill_Illuminanttower",   label: "Sawmill Illuminant Tower",          group: "Industrial Buildings" },
  { value: "Land_Workshop1",                 label: "Workshop 1",                        group: "Industrial Buildings" },
  { value: "Land_Workshop2",                 label: "Workshop 2",                        group: "Industrial Buildings" },
  { value: "Land_Workshop3",                 label: "Workshop 3",                        group: "Industrial Buildings" },
  { value: "Land_Workshop4",                 label: "Workshop 4",                        group: "Industrial Buildings" },
  { value: "Land_Workshop5",                 label: "Workshop 5",                        group: "Industrial Buildings" },
  { value: "Land_Repair_Center",             label: "Repair Center (vehicle)",           group: "Industrial Buildings" },
  { value: "Land_Water_Station",             label: "Water Station",                     group: "Industrial Buildings" },
  { value: "Land_Guardhouse",                label: "Guardhouse (civilian)",             group: "Industrial Buildings" },
  { value: "Land_Garage_Big",                label: "Garage Big ★",                    group: "Industrial Buildings" },
  { value: "Land_Garage_Row_Big",            label: "Garage Row Big (multiple)",         group: "Industrial Buildings" },
  { value: "Land_Garage_Row_Small",          label: "Garage Row Small",                  group: "Industrial Buildings" },
  { value: "Land_Garage_Office",             label: "Garage Office (admin)",             group: "Industrial Buildings" },
  { value: "Land_Garage_Small",              label: "Garage Small",                      group: "Industrial Buildings" },
  { value: "Land_Power_Station",             label: "Power Station Building ★",        group: "Industrial Buildings" },
  { value: "Land_Power_Transformer_Build",   label: "Power Transformer Building",        group: "Industrial Buildings" },
  { value: "Land_Shed_Closed",               label: "Shed Closed (dark interior)",       group: "Industrial Buildings" },
  { value: "Land_Tank_Big",                  label: "Industrial Tank Big",               group: "Industrial Buildings" },
  { value: "Land_Tank_Medium_Stairs",        label: "Industrial Tank Medium w/ Stairs",  group: "Industrial Buildings" },
  { value: "Land_Tank_SmallConcrete_Round",  label: "Concrete Tank Round (small)",       group: "Industrial Buildings" },
  { value: "Land_Misc_Scaffolding",          label: "Scaffolding Structure",             group: "Industrial Buildings" },

  // ─── Farm Buildings ───────────────────────────────────────────────────────
  { value: "Land_Barn_Brick1",               label: "Barn Brick 1 ★",                  group: "Farm Buildings" },
  { value: "Land_Barn_Brick2",               label: "Barn Brick 2",                     group: "Farm Buildings" },
  { value: "Land_Barn_Wood1",                label: "Barn Wood 1",                      group: "Farm Buildings" },
  { value: "Land_Barn_Wood2",                label: "Barn Wood 2",                      group: "Farm Buildings" },
  { value: "Land_Barn_Metal_Big",            label: "Barn Metal Big ★",               group: "Farm Buildings" },
  { value: "Land_Farm_CowshedA",             label: "Farm Cowshed A",                   group: "Farm Buildings" },
  { value: "Land_Farm_CowshedB",             label: "Farm Cowshed B",                   group: "Farm Buildings" },
  { value: "Land_Farm_CowshedC",             label: "Farm Cowshed C",                   group: "Farm Buildings" },
  { value: "Land_Farm_Hopper",               label: "Farm Hopper / Grain Elevator",     group: "Farm Buildings" },
  { value: "Land_Farm_Watertower",           label: "Farm Water Tower (big)",           group: "Farm Buildings" },
  { value: "Land_Farm_WaterTower_Small",     label: "Farm Water Tower Small",           group: "Farm Buildings" },
  { value: "Land_SiloFarm_DE",               label: "Farm Silo (_DE)",                  group: "Farm Buildings" },
  { value: "Land_Silo_DE",                   label: "Industrial Silo (_DE)",            group: "Farm Buildings" },

  // ─── Smokestacks & Towers ─────────────────────────────────────────────────
  { value: "Land_Smokestack_Big",            label: "Smokestack Big ★ landmark",       group: "Smokestacks & Towers" },
  { value: "Land_Smokestack_Brick",          label: "Smokestack Brick",                 group: "Smokestacks & Towers" },
  { value: "Land_Smokestack_Metal",          label: "Smokestack Metal",                 group: "Smokestacks & Towers" },
  { value: "Land_Smokestack_Medium",         label: "Smokestack Medium",                group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC1",                 label: "Tower TC1 (cooling tower)",        group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC2_Base",            label: "Tower TC2 Base",                   group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC2_Mid",             label: "Tower TC2 Mid section",            group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC2_Top",             label: "Tower TC2 Top",                    group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC3_Red",             label: "Tower TC3 Red",                    group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC3_Grey",            label: "Tower TC3 Grey",                   group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC4_Base",            label: "Tower TC4 Base",                   group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC4_Mid",             label: "Tower TC4 Mid",                    group: "Smokestacks & Towers" },
  { value: "Land_Tower_TC4_Top",             label: "Tower TC4 Top",                    group: "Smokestacks & Towers" },
  { value: "Land_RadioTower_1_DE",           label: "Radio Tower (_DE) ★",             group: "Smokestacks & Towers" },
  { value: "Land_Radio_building",            label: "Radio Station Building",            group: "Smokestacks & Towers" },
  { value: "Land_Radio_PanelBig",            label: "Radio Panel Big",                  group: "Smokestacks & Towers" },
  { value: "Land_Radio_PanelPAS",            label: "Radio Panel PAS",                  group: "Smokestacks & Towers" },
  { value: "Land_WaterTower_01_DE",          label: "Water Tower 1 (_DE) ★",          group: "Smokestacks & Towers" },
  { value: "Land_WaterTower_02_DE",          label: "Water Tower 2 (_DE)",              group: "Smokestacks & Towers" },
  { value: "Land_PowerLine_Tower_DE",        label: "Power Line Tower (_DE)",           group: "Smokestacks & Towers" },
  { value: "Land_Power_Pole_Conc1_Amp",      label: "Concrete Power Pole 1",           group: "Smokestacks & Towers" },
  { value: "Land_Power_Pole_Conc4_Lamp_Amp", label: "Concrete Power Pole with Lamp",   group: "Smokestacks & Towers" },
  { value: "Land_Power_Pole_Wood1_Amp",      label: "Wooden Power Pole",               group: "Smokestacks & Towers" },
  { value: "Land_Power_Pole_Wood1_Lamp_Amp", label: "Wooden Power Pole with Lamp",     group: "Smokestacks & Towers" },
  { value: "Land_CraneGrond_DE",             label: "Ground Crane (_DE)",               group: "Smokestacks & Towers" },
  { value: "Land_Cableway_Base",             label: "Cableway Base Station",            group: "Smokestacks & Towers" },
  { value: "Land_Cableway_Tower",            label: "Cableway Support Tower",           group: "Smokestacks & Towers" },
  { value: "Land_Cableway_Tower_Slope",      label: "Cableway Tower (sloped terrain)",  group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_BuildR",           label: "Big Pipe Building R",              group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_BuildL",           label: "Big Pipe Building L",              group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_CornerL",          label: "Big Pipe Corner Left",             group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_CornerR",          label: "Big Pipe Corner Right",            group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_Ground1",          label: "Big Pipe Ground Section 1",        group: "Smokestacks & Towers" },
  { value: "Land_Pipe_Big_Ground2",          label: "Big Pipe Ground Section 2",        group: "Smokestacks & Towers" },

  // ─── Rail Structures ─────────────────────────────────────────────────────
  { value: "Land_Rail_Station_Big",          label: "Rail Station Big ★",             group: "Rail Structures" },
  { value: "Land_Rail_Station_Small",        label: "Rail Station Small",              group: "Rail Structures" },
  { value: "Land_Rail_Warehouse_Small",      label: "Rail Warehouse Small",            group: "Rail Structures" },
  { value: "StaticObj_Rail_Platform_Segment",label: "Rail Platform Segment",           group: "Rail Structures" },

  // ─── Civilian Houses & Apartments ────────────────────────────────────────
  { value: "Land_HouseBlock_1F1",            label: "Apartment Block 1F Type 1",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_1F2",            label: "Apartment Block 1F Type 2",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_1F3",            label: "Apartment Block 1F Type 3",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_1F4",            label: "Apartment Block 1F Type 4",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_1F_Corner",      label: "Apartment Block 1F Corner",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F1",            label: "Apartment Block 2F Type 1",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F2",            label: "Apartment Block 2F Type 2",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F3",            label: "Apartment Block 2F Type 3",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F4",            label: "Apartment Block 2F Type 4",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F5",            label: "Apartment Block 2F Type 5",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F6",            label: "Apartment Block 2F Type 6",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F7",            label: "Apartment Block 2F Type 7",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F8",            label: "Apartment Block 2F Type 8",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F9",            label: "Apartment Block 2F Type 9",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_2F_Corner",      label: "Apartment Block 2F Corner",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_3F1",            label: "Apartment Block 3F Type 1 ★",   group: "Civilian Buildings" },
  { value: "Land_HouseBlock_3F2",            label: "Apartment Block 3F Type 2",       group: "Civilian Buildings" },
  { value: "Land_HouseBlock_3F_Corner1",     label: "Apartment Block 3F Corner 1",     group: "Civilian Buildings" },
  { value: "Land_HouseBlock_3F_Corner2",     label: "Apartment Block 3F Corner 2",     group: "Civilian Buildings" },
  { value: "Land_HouseBlock_5F",             label: "Apartment Block 5F ★ Tallest",  group: "Civilian Buildings" },
  { value: "Land_House_1W01",                label: "House 1W01 (brick bungalow)",     group: "Civilian Buildings" },
  { value: "Land_House_1W02",                label: "House 1W02",                       group: "Civilian Buildings" },
  { value: "Land_House_1W03",                label: "House 1W03",                       group: "Civilian Buildings" },
  { value: "Land_House_1W04",                label: "House 1W04",                       group: "Civilian Buildings" },
  { value: "Land_House_1W05",                label: "House 1W05",                       group: "Civilian Buildings" },
  { value: "Land_House_1W06",                label: "House 1W06",                       group: "Civilian Buildings" },
  { value: "Land_House_1W07",                label: "House 1W07",                       group: "Civilian Buildings" },
  { value: "Land_House_1W08",                label: "House 1W08",                       group: "Civilian Buildings" },
  { value: "Land_House_1W09",                label: "House 1W09",                       group: "Civilian Buildings" },
  { value: "Land_House_1W10",                label: "House 1W10",                       group: "Civilian Buildings" },
  { value: "Land_House_1W11",                label: "House 1W11",                       group: "Civilian Buildings" },
  { value: "Land_House_1W12",                label: "House 1W12",                       group: "Civilian Buildings" },
  { value: "Land_House_2W01",                label: "House 2W01 (2-storey) ★",       group: "Civilian Buildings" },
  { value: "Land_House_2W02",                label: "House 2W02 (2-storey)",            group: "Civilian Buildings" },
  { value: "Land_House_2W03",                label: "House 2W03 (2-storey)",            group: "Civilian Buildings" },
  { value: "Land_House_2W04",                label: "House 2W04 (2-storey)",            group: "Civilian Buildings" },
  { value: "Land_House_2B01",                label: "House 2B01 (brick 2-storey)",      group: "Civilian Buildings" },
  { value: "Land_House_2B02",                label: "House 2B02 (brick 2-storey)",      group: "Civilian Buildings" },
  { value: "Land_House_2B03",                label: "House 2B03 (brick 2-storey)",      group: "Civilian Buildings" },
  { value: "Land_House_2B04",                label: "House 2B04 (brick 2-storey)",      group: "Civilian Buildings" },
  { value: "Land_House_1B01_Pub",            label: "Pub (brick building) ★",         group: "Civilian Buildings" },
  { value: "Land_Village_Pub",               label: "Village Pub",                      group: "Civilian Buildings" },
  { value: "Land_Tenement_Big",              label: "Tenement Big (old block) ★",     group: "Civilian Buildings" },
  { value: "Land_Tenement_Small",            label: "Tenement Small",                   group: "Civilian Buildings" },

  // ─── Civic & Public Buildings ─────────────────────────────────────────────
  { value: "Land_City_Hospital",             label: "City Hospital ★",                group: "Civic Buildings" },
  { value: "Land_Village_HealthCare",        label: "Village Healthcare Clinic",        group: "Civic Buildings" },
  { value: "Land_City_PoliceStation",        label: "City Police Station ★",          group: "Civic Buildings" },
  { value: "Land_Village_PoliceStation",     label: "Village Police Station",           group: "Civic Buildings" },
  { value: "Land_City_School",               label: "City School ★",                  group: "Civic Buildings" },
  { value: "Land_Office_Municipal1",         label: "Municipal Office 1",              group: "Civic Buildings" },
  { value: "Land_Office_Municipal2",         label: "Municipal Office 2",              group: "Civic Buildings" },
  { value: "Land_Office1",                   label: "Office Building 1",               group: "Civic Buildings" },
  { value: "Land_Office2",                   label: "Office Building 2",               group: "Civic Buildings" },
  { value: "Land_City_FireStation",          label: "City Fire Station ★",            group: "Civic Buildings" },
  { value: "Land_City_Store",                label: "City Store",                       group: "Civic Buildings" },
  { value: "Land_City_Store_WithStairs",     label: "City Store (with stairs)",         group: "Civic Buildings" },
  { value: "Land_Village_store",             label: "Village Store / General Store",    group: "Civic Buildings" },
  { value: "Land_City_Stand_FastFood",       label: "Fast Food Stand",                  group: "Civic Buildings" },
  { value: "Land_City_Stand_Grocery",        label: "Grocery Stand",                    group: "Civic Buildings" },
  { value: "Land_City_Stand_News1",          label: "News Stand 1",                     group: "Civic Buildings" },
  { value: "Land_City_Stand_News2",          label: "News Stand 2",                     group: "Civic Buildings" },
  { value: "Land_BusStation_building",       label: "Bus Station Building",             group: "Civic Buildings" },
  { value: "Land_BusStation_wall_bench",     label: "Bus Station Wall + Bench",         group: "Civic Buildings" },
  { value: "Land_BusStop_City",              label: "City Bus Stop",                    group: "Civic Buildings" },
  { value: "Land_BusStop_DE",                label: "Bus Stop (_DE)",                   group: "Civic Buildings" },
  { value: "Land_Prison_Main",               label: "Prison Main Building ★",         group: "Civic Buildings" },
  { value: "Land_Prison_Side",               label: "Prison Side Building",             group: "Civic Buildings" },

  // ─── Sheds & Small Structures ─────────────────────────────────────────────
  { value: "Land_Shed_W1",                   label: "Shed Wood 1 (tiny shed)",          group: "Sheds & Small Structures" },
  { value: "Land_Shed_W2",                   label: "Shed Wood 2",                      group: "Sheds & Small Structures" },
  { value: "Land_Shed_W3",                   label: "Shed Wood 3",                      group: "Sheds & Small Structures" },
  { value: "Land_Shed_W4",                   label: "Shed Wood 4 (tool shed)",          group: "Sheds & Small Structures" },
  { value: "Land_Shed_W4_DE",                label: "Shed W4 (_DE)",                    group: "Sheds & Small Structures" },
  { value: "Land_Shed_W5",                   label: "Shed Wood 5",                      group: "Sheds & Small Structures" },
  { value: "Land_Shed_W6",                   label: "Shed Wood 6",                      group: "Sheds & Small Structures" },
  { value: "Land_Shed_M1",                   label: "Shed Metal 1",                     group: "Sheds & Small Structures" },
  { value: "Land_Shed_M3",                   label: "Shed Metal 3",                     group: "Sheds & Small Structures" },
  { value: "Land_Shed_M4",                   label: "Shed Metal 4 (corrugated) ★",    group: "Sheds & Small Structures" },
  { value: "Land_Shed_Ind_DE",               label: "Industrial Shed (_DE)",            group: "Sheds & Small Structures" },
  { value: "Land_Camp_House_white",           label: "Camp House White (hunter cabin)", group: "Sheds & Small Structures" },
  { value: "Land_Camp_House_brown",           label: "Camp House Brown",                group: "Sheds & Small Structures" },
  { value: "Land_Camp_House_red",             label: "Camp House Red",                  group: "Sheds & Small Structures" },
  { value: "Land_Misc_DeerStand1",            label: "Deer Stand 1 (tall hunting stand)",group: "Sheds & Small Structures" },
  { value: "Land_Misc_DeerStand2",            label: "Deer Stand 2",                    group: "Sheds & Small Structures" },
  { value: "Land_Misc_FeedShack",             label: "Feed Shack (small roadside)",     group: "Sheds & Small Structures" },
  { value: "Land_Misc_DogHouse",              label: "Dog House",                       group: "Sheds & Small Structures" },
  { value: "Land_Misc_Greenhouse",            label: "Greenhouse",                      group: "Sheds & Small Structures" },
  { value: "Land_Misc_Toilet_Mobile",         label: "Mobile Toilet (portapotty)",      group: "Sheds & Small Structures" },
  { value: "Land_Misc_Toilet_Dry",            label: "Dry Toilet (outhouse)",           group: "Sheds & Small Structures" },
  { value: "Land_Misc_TrailRoof_Big",         label: "Trail Shelter Large (hiking)",    group: "Sheds & Small Structures" },
  { value: "Land_Misc_TrailRoof_Small",       label: "Trail Shelter Small (hiking)",    group: "Sheds & Small Structures" },
  { value: "Land_FuelStation_Build",          label: "Fuel Station Building ★",        group: "Sheds & Small Structures" },
  { value: "Land_FuelStation_Feed",           label: "Fuel Station Feed Pump",          group: "Sheds & Small Structures" },
  { value: "Land_PetrolStation_Canopy",       label: "Petrol Station Canopy",           group: "Sheds & Small Structures" },

  // ─── Special & Iconic Structures ─────────────────────────────────────────
  { value: "Land_Castle_Bergfrit",            label: "Castle Bergfrit Tower ★",        group: "Special Structures" },
  { value: "Land_Castle_Donjon",              label: "Castle Donjon Keep",              group: "Special Structures" },
  { value: "Land_Castle_Gate",               label: "Castle Gate (map object)",         group: "Special Structures" },
  { value: "Land_Castle_Stairs",             label: "Castle Stairs Section",            group: "Special Structures" },
  { value: "Land_Castle_Stairs_nolc",        label: "Castle Stairs (no LC)",            group: "Special Structures" },
  { value: "Land_Castle_Bastion",            label: "Castle Bastion (tower corner)",    group: "Special Structures" },
  { value: "Land_Castle_Bastion_nolc",       label: "Castle Bastion (no LC)",           group: "Special Structures" },
  { value: "Land_Church1_Yellow",            label: "Church Yellow ★",                group: "Special Structures" },
  { value: "Land_Church2_2",                 label: "Church 2 (variant 2)",             group: "Special Structures" },
  { value: "Land_Church3",                   label: "Church 3",                         group: "Special Structures" },
  { value: "Land_Chapel",                    label: "Chapel (small)",                   group: "Special Structures" },
  { value: "Land_Hotel",                     label: "Hotel Building ★",               group: "Special Structures" },
  { value: "Land_Hotel_Damaged",             label: "Hotel Damaged (ruined)",           group: "Special Structures" },
  { value: "Land_Lunapark_Ferris_wheel",     label: "Ferris Wheel ★ (Lunapark)",     group: "Special Structures" },
  { value: "Land_Lunapark_Carousel_Swan",    label: "Swan Carousel",                    group: "Special Structures" },
  { value: "Land_Lunapark_Autodrome",        label: "Autodrome Track (bumper cars)",    group: "Special Structures" },
  { value: "Land_Lunapark_Shooting_Gallery", label: "Shooting Gallery (fairground)",    group: "Special Structures" },
  { value: "Land_Dead_MassGrave",            label: "Mass Grave (atmospheric)",         group: "Special Structures" },
  { value: "Land_Monument_T34",              label: "Monument T-34 Tank",               group: "Special Structures" },
  { value: "Land_StaticObj_Monument_Wall",   label: "Monument Wall",                    group: "Special Structures" },
  { value: "StaticObj_Monument_Wall",        label: "Monument Wall (StaticObj)",        group: "Special Structures" },

  // ─── Military Props ──────────────────────────────────────────────────────
  { value: "Land_Sandbag_Round_DE",          label: "Sandbag Round (nest)",             group: "Military Props" },
  { value: "Land_BarrierConcrete_03_DE",     label: "Concrete Barrier 3 (_DE)",         group: "Military Props" },
  { value: "Land_TankTrap_DE",               label: "Tank Trap Czech Hedgehog",         group: "Military Props" },
  { value: "Land_BarbedWire_01_DE",          label: "Barbed Wire Line",                 group: "Military Props" },

  // ─── Rocks & Natural ─────────────────────────────────────────────────────
  { value: "DZ\\rocks_bliss\\stone10_moss.p3d",       label: "Stone Moss (medium)",     group: "Rocks & Natural" },
  { value: "DZ\\rocks_bliss\\stone9_moss.p3d",        label: "Stone Moss (large)",      group: "Rocks & Natural" },
  { value: "DZ\\rocks_bliss\\rock_monolith1.p3d",     label: "Rock Monolith 1",         group: "Rocks & Natural" },
  { value: "DZ\\rocks_bliss\\rock_spike1.p3d",        label: "Rock Spike 1",            group: "Rocks & Natural" },
  { value: "DZ\\rocks_bliss\\rock_monolith2.p3d",     label: "Rock Monolith 2",         group: "Rocks & Natural" },
  { value: "DZ\\rocks_bliss\\clutter_01.p3d",         label: "Rock Clutter Small",      group: "Rocks & Natural" },
  { value: "DZ\\rocks_sakhal\\rock_wall_01.p3d",      label: "Rock Wall Sakhal",        group: "Rocks & Natural" },
  { value: "DZ\\rocks_sakhal\\rock_monolith01.p3d",   label: "Rock Monolith Sakhal",    group: "Rocks & Natural" },

  // ─── Plants & Trees (bliss) ──────────────────────────────────────────────
  { value: "WoodenLog",                                                              label: "Wooden Log ★",             group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_fagussylvatica_3f_summer.p3d",               label: "Beech Tree (Summer)",      group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_pinussylvestris_2f_summer.p3d",              label: "Pine Tree (Summer)",       group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_pinussylvestris_dead_fallen_1.p3d",          label: "Fallen Pine Log",          group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_fagussylvatica_dead_fallen_1.p3d",           label: "Fallen Beech Log",         group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_betulapendula_dead_fallen_1.p3d",            label: "Fallen Birch Log",         group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\branch\\b_fagussylvatica_1s_summer.p3d",             label: "Beech Branch",             group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\branch\\b_pinussylvestris_1s_summer.p3d",            label: "Pine Branch",              group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\branch\\b_quercusrobur_1s_summer.p3d",              label: "Oak Branch",               group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\bush\\b_prunusspinosa_1s_summer.p3d",               label: "Blackthorn Bush",          group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_quercusrobur_2f_summer.p3d",                label: "Oak Tree (Summer)",        group: "Plants & Trees" },
  { value: "DZ\\plants_bliss\\tree\\t_betulapendula_2f_summer.p3d",               label: "Birch Tree (Summer)",      group: "Plants & Trees" },
  { value: "DZ\\plants_sakhal\\tree\\t_larixkaempferi_2f_summer.p3d",             label: "Larch Tree (Sakhal)",      group: "Plants & Trees" },
  { value: "DZ\\plants_sakhal\\tree\\t_abiessibirica_2f_summer.p3d",              label: "Fir Tree (Sakhal)",        group: "Plants & Trees" },

  // ─── Misc Props ──────────────────────────────────────────────────────────
  { value: "Land_Misc_Well_Pump_Yellow",     label: "Well Pump Yellow",                 group: "Misc Props" },
  { value: "Land_Misc_Well_Pump_Blue",       label: "Well Pump Blue",                   group: "Misc Props" },
  { value: "StaticObj_Lamp_Ind",             label: "Industrial Lamp",                  group: "Misc Props" },
  { value: "Land_Lamp_City1_amp",            label: "City Street Lamp",                 group: "Misc Props" },
  { value: "StaticObj_Furniture_shelf_DZ",   label: "Shelf Unit",                       group: "Misc Props" },
  { value: "Land_Misc_Fountain",             label: "Fountain (civic)",                 group: "Misc Props" },
  { value: "Land_Misc_FireHydrant",          label: "Fire Hydrant",                     group: "Misc Props" },

  // ─── Firearms (from types.xml FIREARMS section — 88 guns, all verified) ──
  { value: "AK74",                           label: "AK74",                             group: "Firearms" },
  { value: "AK74_Black",                     label: "AK74 Black",                       group: "Firearms" },
  { value: "AK74_Green",                     label: "AK74 Green",                       group: "Firearms" },
  { value: "AK101",                          label: "AK101",                            group: "Firearms" },
  { value: "AK101_Black",                    label: "AK101 Black",                      group: "Firearms" },
  { value: "AK101_Green",                    label: "AK101 Green",                      group: "Firearms" },
  { value: "AKM",                            label: "AKM",                              group: "Firearms" },
  { value: "AKS74U",                         label: "AKS74U",                           group: "Firearms" },
  { value: "AKS74U_Black",                   label: "AKS74U Black",                     group: "Firearms" },
  { value: "AKS74U_Green",                   label: "AKS74U Green",                     group: "Firearms" },
  { value: "ASVAL",                          label: "AS VAL",                           group: "Firearms" },
  { value: "Aug",                            label: "AUG A1",                           group: "Firearms" },
  { value: "AugShort",                       label: "AUG Short",                        group: "Firearms" },
  { value: "B95",                            label: "B95 Double-barrel",                group: "Firearms" },
  { value: "B95_Black",                      label: "B95 Black",                        group: "Firearms" },
  { value: "B95_Green",                      label: "B95 Green",                        group: "Firearms" },
  { value: "CZ527",                          label: "CZ 527",                           group: "Firearms" },
  { value: "CZ550",                          label: "CZ 550",                           group: "Firearms" },
  { value: "CZ61",                           label: "CZ 61 Scorpion",                   group: "Firearms" },
  { value: "CZ75",                           label: "CZ 75 Pistol",                     group: "Firearms" },
  { value: "Colt1911",                       label: "Colt 1911",                        group: "Firearms" },
  { value: "Engraved1911",                   label: "Engraved 1911",                    group: "Firearms" },
  { value: "Crossbow_Black",                 label: "Crossbow Black",                   group: "Firearms" },
  { value: "Crossbow_Wood",                  label: "Crossbow Wood",                    group: "Firearms" },
  { value: "Crossbow_Autumn",                label: "Crossbow Autumn",                  group: "Firearms" },
  { value: "Crossbow_Summer",                label: "Crossbow Summer",                  group: "Firearms" },
  { value: "Deagle",                         label: "Desert Eagle",                     group: "Firearms" },
  { value: "Deagle_Gold",                    label: "Desert Eagle Gold",                group: "Firearms" },
  { value: "Derringer_Black",                label: "Derringer Black",                  group: "Firearms" },
  { value: "Derringer_Grey",                 label: "Derringer Grey",                   group: "Firearms" },
  { value: "Derringer_Pink",                 label: "Derringer Pink",                   group: "Firearms" },
  { value: "FAL",                            label: "FAL",                              group: "Firearms" },
  { value: "FAMAS",                          label: "FAMAS",                            group: "Firearms" },
  { value: "FNX45",                          label: "FNX-45 Pistol",                   group: "Firearms" },
  { value: "Flaregun",                       label: "Flare Gun",                        group: "Firearms" },
  { value: "Glock19",                        label: "Glock 19",                         group: "Firearms" },
  { value: "Izh18",                          label: "IZH-18 Rifle",                    group: "Firearms" },
  { value: "Izh18Shotgun",                   label: "IZH-18 Shotgun",                  group: "Firearms" },
  { value: "Izh43Shotgun",                   label: "IZH-43 Double-barrel",            group: "Firearms" },
  { value: "Longhorn",                       label: "Longhorn Pistol",                  group: "Firearms" },
  { value: "M14",                            label: "M14",                              group: "Firearms" },
  { value: "M16A2",                          label: "M16A2",                            group: "Firearms" },
  { value: "M4A1",                           label: "M4A1",                             group: "Firearms" },
  { value: "M4A1_Black",                     label: "M4A1 Black",                       group: "Firearms" },
  { value: "M4A1_Green",                     label: "M4A1 Green",                       group: "Firearms" },
  { value: "M79",                            label: "M79 Grenade Launcher",             group: "Firearms" },
  { value: "MKII",                           label: "MK II Pistol",                     group: "Firearms" },
  { value: "MP5K",                           label: "MP5-K",                            group: "Firearms" },
  { value: "Magnum",                         label: "Magnum Revolver",                  group: "Firearms" },
  { value: "MakarovIJ70",                    label: "Makarov IJ-70",                   group: "Firearms" },
  { value: "Mosin9130",                      label: "Mosin 9130",                       group: "Firearms" },
  { value: "Mosin9130_Black",                label: "Mosin 9130 Black",                 group: "Firearms" },
  { value: "Mosin9130_Camo",                 label: "Mosin 9130 Camo",                  group: "Firearms" },
  { value: "Mosin9130_Green",                label: "Mosin 9130 Green",                 group: "Firearms" },
  { value: "Mp133Shotgun",                   label: "MP-133 Shotgun",                   group: "Firearms" },
  { value: "P1",                             label: "P1 Pistol",                        group: "Firearms" },
  { value: "PM73Rak",                        label: "PM-73 RAK",                        group: "Firearms" },
  { value: "PP19",                           label: "PP-19 Bizon",                      group: "Firearms" },
  { value: "R12",                            label: "R12 Revolver",                     group: "Firearms" },
  { value: "Repeater",                       label: "Repeater Rifle",                   group: "Firearms" },
  { value: "Ruger1022",                      label: "Ruger 10/22",                      group: "Firearms" },
  { value: "SKS",                            label: "SKS",                              group: "Firearms" },
  { value: "SKS_Green",                      label: "SKS Green",                        group: "Firearms" },
  { value: "SSG82",                          label: "SSG 82 Sniper",                    group: "Firearms" },
  { value: "SV98",                           label: "SV-98 Sniper",                     group: "Firearms" },
  { value: "SVD",                            label: "SVD Dragunov",                     group: "Firearms" },
  { value: "SVD_Wooden",                     label: "SVD Dragunov Wooden",              group: "Firearms" },
  { value: "Saiga",                          label: "Saiga Shotgun",                    group: "Firearms" },
  { value: "Scout",                          label: "Scout Rifle",                      group: "Firearms" },
  { value: "Scout_Chernarus",                label: "Scout Chernarus",                  group: "Firearms" },
  { value: "Scout_Livonia",                  label: "Scout Livonia",                    group: "Firearms" },
  { value: "UMP45",                          label: "UMP-45",                           group: "Firearms" },
  { value: "VSS",                            label: "VSS Vintorez",                     group: "Firearms" },
  { value: "Vikhr",                          label: "Vikhr 9x39",                       group: "Firearms" },
  { value: "Winchester70",                   label: "Winchester 70",                    group: "Firearms" },
  { value: "Winchester70_Black",             label: "Winchester 70 Black",              group: "Firearms" },
  { value: "Winchester70_Green",             label: "Winchester 70 Green",              group: "Firearms" },
  // Sawed-off variants
  { value: "SawedoffB95",                    label: "Sawed-off B95",                    group: "Firearms" },
  { value: "SawedoffFAMAS",                  label: "Sawed-off FAMAS",                  group: "Firearms" },
  { value: "SawedoffIzh18",                  label: "Sawed-off IZH-18",                group: "Firearms" },
  { value: "SawedoffIzh18Shotgun",           label: "Sawed-off IZH-18 Shotgun",        group: "Firearms" },
  { value: "SawedoffIzh43Shotgun",           label: "Sawed-off IZH-43",               group: "Firearms" },
  { value: "SawedoffMagnum",                 label: "Sawed-off Magnum",                 group: "Firearms" },
  { value: "SawedoffMosin9130",              label: "Sawed-off Mosin",                  group: "Firearms" },
  { value: "SawedoffMosin9130_Black",        label: "Sawed-off Mosin Black",            group: "Firearms" },
  { value: "SawedoffMosin9130_Camo",         label: "Sawed-off Mosin Camo",             group: "Firearms" },
  { value: "SawedoffMosin9130_Green",        label: "Sawed-off Mosin Green",            group: "Firearms" },

  // ─── Melee Weapons (from types.xml MELEE section — all verified) ──────────
  { value: "Sword",                          label: "Sword ★",                          group: "Melee" },
  { value: "Mace",                           label: "Mace ★",                           group: "Melee" },
  { value: "NorseHelm",                      label: "Norse Helm ★",                     group: "Melee" },
  { value: "GreatHelm",                      label: "Great Helm ★",                     group: "Melee" },
  { value: "BaseballBat",                    label: "Baseball Bat",                     group: "Melee" },
  { value: "NailedBaseballBat",              label: "Baseball Bat (Nailed)",            group: "Melee" },
  { value: "BarbedBaseballBat",              label: "Baseball Bat (Barbed)",            group: "Melee" },
  { value: "BoneKnife",                      label: "Bone Knife",                       group: "Melee" },
  { value: "BrassKnuckles_Dull",             label: "Brass Knuckles (Dull)",            group: "Melee" },
  { value: "BrassKnuckles_Shiny",            label: "Brass Knuckles (Shiny)",           group: "Melee" },
  { value: "Broom",                          label: "Broom",                            group: "Melee" },
  { value: "Broom_Birch",                    label: "Broom Birch",                      group: "Melee" },
  { value: "CanOpener",                      label: "Can Opener",                       group: "Melee" },
  { value: "Cleaver",                        label: "Cleaver",                          group: "Melee" },
  { value: "CombatKnife",                    label: "Combat Knife",                     group: "Melee" },
  { value: "CrudeMachete",                   label: "Crude Machete",                    group: "Melee" },
  { value: "FangeKnife",                     label: "Fange Knife",                      group: "Melee" },
  { value: "FireExtinguisher",               label: "Fire Extinguisher",                group: "Melee" },
  { value: "HuntingKnife",                   label: "Hunting Knife",                    group: "Melee" },
  { value: "KitchenKnife",                   label: "Kitchen Knife",                    group: "Melee" },
  { value: "KukriKnife",                     label: "Kukri Knife",                      group: "Melee" },
  { value: "LongWoodenStick",                label: "Long Wooden Stick",                group: "Melee" },
  { value: "Machete",                        label: "Machete",                          group: "Melee" },
  { value: "OrientalMachete",                label: "Oriental Machete",                 group: "Melee" },
  { value: "Pipe",                           label: "Metal Pipe",                       group: "Melee" },
  { value: "Pitchfork",                      label: "Pitchfork",                        group: "Melee" },
  { value: "PoliceBaton",                    label: "Police Baton",                     group: "Melee" },
  { value: "Sickle",                         label: "Sickle",                           group: "Melee" },
  { value: "SpearBone",                      label: "Bone Spear",                       group: "Melee" },
  { value: "SpearStone",                     label: "Stone Spear",                      group: "Melee" },
  { value: "SteakKnife",                     label: "Steak Knife",                      group: "Melee" },
  { value: "StoneKnife",                     label: "Stone Knife",                      group: "Melee" },
  { value: "TelescopicBaton",                label: "Telescopic Baton",                 group: "Melee" },

  // ─── Armbands ─────────────────────────────────────────────────────────────
  { value: "ArmBandBlack",                   label: "Armband Black ★ text fave",       group: "Armbands" },
  { value: "ArmBandBlue",                    label: "Armband Blue",                     group: "Armbands" },
  { value: "ArmBandGreen",                   label: "Armband Green",                    group: "Armbands" },
  { value: "ArmBandRed",                     label: "Armband Red",                      group: "Armbands" },
  { value: "ArmBandWhite",                   label: "Armband White",                    group: "Armbands" },
  { value: "ArmBandYellow",                  label: "Armband Yellow",                   group: "Armbands" },
  { value: "ArmBandOrange",                  label: "Armband Orange",                   group: "Armbands" },

  // ─── Airstrip Lights ─────────────────────────────────────────────────────
  { value: "StaticObj_Airfield_Light_PAPI1",         label: "PAPI Light ★ best for spelling",  group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Threshold_01",  label: "Threshold Light 1",               group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Threshold_02",  label: "Threshold Light 2",               group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Centreline_01", label: "Centreline Light 1",              group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Centreline_02", label: "Centreline Light 2",              group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Edge_01",       label: "Edge Light 1",                    group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Edge_02",       label: "Edge Light 2",                    group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Taxiway_01",    label: "Taxiway Light 1",                 group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Taxiway_02",    label: "Taxiway Light 2",                 group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Approach_01",   label: "Approach Light 1",               group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_Strobe_01",     label: "Strobe Light",                    group: "Airstrip Lights" },
  { value: "StaticObj_Airfield_Light_End_01",        label: "Runway End Light",                group: "Airstrip Lights" },

  // ─── Flat Objects (floors, pads, runways) ────────────────────────────────
  { value: "Land_Asphalt_01_F_10x10_DE",    label: "Asphalt 10x10",                   group: "Flat Objects" },
  { value: "Land_Asphalt_01_F_20x20_DE",    label: "Asphalt 20x20",                   group: "Flat Objects" },
  { value: "Land_Asphalt_01_F_5x5_DE",      label: "Asphalt 5x5",                     group: "Flat Objects" },
  { value: "Land_Asphalt_01_Cor_DE",        label: "Asphalt Corner",                   group: "Flat Objects" },
  { value: "Land_Asphalt_01_T_DE",          label: "Asphalt T-Junction",               group: "Flat Objects" },
  { value: "Land_Asphalt_01_Cross_DE",      label: "Asphalt Cross",                    group: "Flat Objects" },
  { value: "Land_Concrete_01_F_10x10_DE",   label: "Concrete 10x10",                  group: "Flat Objects" },
  { value: "Land_Concrete_01_F_20x20_DE",   label: "Concrete 20x20",                  group: "Flat Objects" },
  { value: "Land_Concrete_01_F_5x5_DE",     label: "Concrete 5x5",                    group: "Flat Objects" },
  { value: "Land_Concrete_01_Cor_DE",       label: "Concrete Corner",                  group: "Flat Objects" },
  { value: "Land_Concrete_01_T_DE",         label: "Concrete T-Junction",              group: "Flat Objects" },
  { value: "Land_Pier_DE",                  label: "Pier Section (flat)",              group: "Flat Objects" },
  { value: "Land_Pier_Long_DE",             label: "Pier Section Long",                group: "Flat Objects" },
  { value: "Land_Pier_Corner_DE",           label: "Pier Corner",                      group: "Flat Objects" },
  { value: "Land_Pier_T_DE",               label: "Pier T-Junction",                  group: "Flat Objects" },
  { value: "Land_Pier_Cross_DE",            label: "Pier Cross",                       group: "Flat Objects" },
  { value: "Land_Runway_01_F_DE",           label: "Runway Strip (flat)",              group: "Flat Objects" },
  { value: "Land_Runway_01_Line_DE",        label: "Runway Centre Line",               group: "Flat Objects" },
  { value: "Land_Runway_01_TH_DE",          label: "Runway Threshold Mark",            group: "Flat Objects" },
  { value: "Land_Runway_01_Cor_DE",         label: "Runway Corner",                    group: "Flat Objects" },
  { value: "Land_Pavement_01_F_10x10_DE",   label: "Pavement 10x10",                  group: "Flat Objects" },
  { value: "Land_Pavement_01_F_5x5_DE",     label: "Pavement 5x5",                    group: "Flat Objects" },
  { value: "Land_Pavement_01_Cor_DE",       label: "Pavement Corner",                  group: "Flat Objects" },
  { value: "Land_ConcreteSlab_01_DE",       label: "Concrete Slab 1",                  group: "Flat Objects" },
  { value: "Land_ConcreteSlab_02_DE",       label: "Concrete Slab 2",                  group: "Flat Objects" },
  { value: "Land_ConcreteSlab_03_DE",       label: "Concrete Slab 3 (large)",          group: "Flat Objects" },
  { value: "Land_GarageFloor_01_DE",        label: "Garage Floor",                     group: "Flat Objects" },
  { value: "Land_TarmacFloor_01_DE",        label: "Tarmac Floor",                     group: "Flat Objects" },
  { value: "Land_Puddle_01_DE",             label: "Puddle / Water Pool",              group: "Flat Objects" },
  { value: "Land_SandFloor_01_DE",          label: "Sand Floor Pad",                   group: "Flat Objects" },
  { value: "Land_GrassFloor_01_DE",         label: "Grass Floor Pad",                  group: "Flat Objects" },
  { value: "Land_MudFloor_01_DE",           label: "Mud Floor Pad",                    group: "Flat Objects" },

  // ─── Driveable Vehicles (from types.xml VEHICLES section) ───────────────
  { value: "Boat_01_Black",                 label: "Boat Black ★ driveable",           group: "Vehicles" },
  { value: "Boat_01_Blue",                  label: "Boat Blue",                         group: "Vehicles" },
  { value: "Boat_01_Camo",                  label: "Boat Camo",                         group: "Vehicles" },
  { value: "Boat_01_Orange",                label: "Boat Orange",                       group: "Vehicles" },
  { value: "CivilianSedan",                 label: "Civilian Sedan (default)",          group: "Vehicles" },
  { value: "CivilianSedan_Black",           label: "Civilian Sedan Black",              group: "Vehicles" },
  { value: "CivilianSedan_Wine",            label: "Civilian Sedan Wine",               group: "Vehicles" },
  { value: "Hatchback_02",                  label: "Hatchback 02 (default)",            group: "Vehicles" },
  { value: "Hatchback_02_Black",            label: "Hatchback 02 Black",                group: "Vehicles" },
  { value: "Hatchback_02_Blue",             label: "Hatchback 02 Blue",                 group: "Vehicles" },
  { value: "OffroadHatchback",              label: "Offroad Hatchback (default)",        group: "Vehicles" },
  { value: "OffroadHatchback_Blue",         label: "Offroad Hatchback Blue",             group: "Vehicles" },
  { value: "OffroadHatchback_White",        label: "Offroad Hatchback White",            group: "Vehicles" },
  { value: "Offroad_02",                    label: "Offroad 02 (M1025 Humvee type)",    group: "Vehicles" },
  { value: "Sedan_02",                      label: "Sedan 02 (default)",                group: "Vehicles" },
  { value: "Sedan_02_Grey",                 label: "Sedan 02 Grey",                     group: "Vehicles" },
  { value: "Sedan_02_Red",                  label: "Sedan 02 Red",                      group: "Vehicles" },
  { value: "Truck_01_Covered",              label: "Truck 01 Covered (default)",        group: "Vehicles" },
  { value: "Truck_01_Covered_Blue",         label: "Truck 01 Covered Blue",             group: "Vehicles" },
  { value: "Truck_01_Covered_Orange",       label: "Truck 01 Covered Orange",           group: "Vehicles" },

  // ─── Vehicle Parts (from types.xml VEHICLEPARTS section) ─────────────────
  // Shared parts
  { value: "CarBattery",                    label: "Car Battery",                       group: "Vehicle Parts" },
  { value: "TruckBattery",                  label: "Truck Battery",                     group: "Vehicle Parts" },
  { value: "CarRadiator",                   label: "Car Radiator",                      group: "Vehicle Parts" },
  { value: "HeadlightH7",                   label: "Headlight H7",                      group: "Vehicle Parts" },
  { value: "HeadlightH7_Box",              label: "Headlight H7 (boxed)",              group: "Vehicle Parts" },
  { value: "EngineOil",                     label: "Engine Oil",                        group: "Vehicle Parts" },
  { value: "CarTent",                       label: "Car Tent",                          group: "Vehicle Parts" },
  // CivilianSedan parts
  { value: "CivSedanDoors_Driver",          label: "CivSedan Door Driver",              group: "Vehicle Parts" },
  { value: "CivSedanDoors_CoDriver",        label: "CivSedan Door CoDriver",            group: "Vehicle Parts" },
  { value: "CivSedanDoors_BackLeft",        label: "CivSedan Door BackLeft",            group: "Vehicle Parts" },
  { value: "CivSedanDoors_BackRight",       label: "CivSedan Door BackRight",           group: "Vehicle Parts" },
  { value: "CivSedanHood",                  label: "CivSedan Hood",                     group: "Vehicle Parts" },
  { value: "CivSedanTrunk",                 label: "CivSedan Trunk",                    group: "Vehicle Parts" },
  { value: "CivSedanWheel",                 label: "CivSedan Wheel",                    group: "Vehicle Parts" },
  // OffroadHatchback (old Lada-type) parts
  { value: "HatchbackDoors_Driver",         label: "Hatchback Door Driver",             group: "Vehicle Parts" },
  { value: "HatchbackDoors_CoDriver",       label: "Hatchback Door CoDriver",           group: "Vehicle Parts" },
  { value: "HatchbackHood",                 label: "Hatchback Hood",                    group: "Vehicle Parts" },
  { value: "HatchbackTrunk",                label: "Hatchback Trunk",                   group: "Vehicle Parts" },
  { value: "HatchbackWheel",                label: "Hatchback Wheel",                   group: "Vehicle Parts" },
  // Hatchback_02 (golf-type) parts
  { value: "Hatchback_02_Door_1_1",         label: "Hatchback 02 Door FL",              group: "Vehicle Parts" },
  { value: "Hatchback_02_Door_1_2",         label: "Hatchback 02 Door FR",              group: "Vehicle Parts" },
  { value: "Hatchback_02_Door_2_1",         label: "Hatchback 02 Door RL",              group: "Vehicle Parts" },
  { value: "Hatchback_02_Door_2_2",         label: "Hatchback 02 Door RR",              group: "Vehicle Parts" },
  { value: "Hatchback_02_Hood",             label: "Hatchback 02 Hood",                 group: "Vehicle Parts" },
  { value: "Hatchback_02_Trunk",            label: "Hatchback 02 Trunk",                group: "Vehicle Parts" },
  { value: "Hatchback_02_Wheel",            label: "Hatchback 02 Wheel",                group: "Vehicle Parts" },
  // Offroad_02 parts
  { value: "Offroad_02_Door_1_1",           label: "Offroad 02 Door FL",                group: "Vehicle Parts" },
  { value: "Offroad_02_Door_1_2",           label: "Offroad 02 Door FR",                group: "Vehicle Parts" },
  { value: "Offroad_02_Door_2_1",           label: "Offroad 02 Door RL",                group: "Vehicle Parts" },
  { value: "Offroad_02_Door_2_2",           label: "Offroad 02 Door RR",                group: "Vehicle Parts" },
  { value: "Offroad_02_Hood",               label: "Offroad 02 Hood",                   group: "Vehicle Parts" },
  { value: "Offroad_02_Trunk",              label: "Offroad 02 Trunk",                  group: "Vehicle Parts" },
  { value: "Offroad_02_Wheel",              label: "Offroad 02 Wheel",                  group: "Vehicle Parts" },
  // Sedan_02 parts
  { value: "Sedan_02_Door_1_1",             label: "Sedan 02 Door FL",                  group: "Vehicle Parts" },
  { value: "Sedan_02_Door_1_2",             label: "Sedan 02 Door FR",                  group: "Vehicle Parts" },
  { value: "Sedan_02_Door_2_1",             label: "Sedan 02 Door RL",                  group: "Vehicle Parts" },
  { value: "Sedan_02_Door_2_2",             label: "Sedan 02 Door RR",                  group: "Vehicle Parts" },
  { value: "Sedan_02_Hood",                 label: "Sedan 02 Hood",                     group: "Vehicle Parts" },
  { value: "Sedan_02_Trunk",                label: "Sedan 02 Trunk",                    group: "Vehicle Parts" },
  { value: "Sedan_02_Wheel",                label: "Sedan 02 Wheel",                    group: "Vehicle Parts" },
  // Truck_01 parts
  { value: "Truck_01_Door_1_1",             label: "Truck 01 Door L",                   group: "Vehicle Parts" },
  { value: "Truck_01_Door_2_1",             label: "Truck 01 Door R",                   group: "Vehicle Parts" },
  { value: "Truck_01_Hood",                 label: "Truck 01 Hood",                     group: "Vehicle Parts" },
  { value: "Truck_01_Wheel",                label: "Truck 01 Wheel (single)",           group: "Vehicle Parts" },
  { value: "Truck_01_WheelDouble",          label: "Truck 01 Wheel (double rear)",      group: "Vehicle Parts" },

  // ─── Hay Bales & Stacked Crates ──────────────────────────────────────────
  // Source: DayZDisco Architecture Generator & Text Sign Maker object list
  { value: "HayBale",                        label: "Hay Bale (loose) ★ text fave",    group: "Hay Bales & Crates" },
  { value: "HayBale_Packed",                 label: "Hay Bale Packed (round)",          group: "Hay Bales & Crates" },
  { value: "HayBale_Packed_Stack",           label: "Hay Bale Packed Stack (2-high)",   group: "Hay Bales & Crates" },
  { value: "HayBale_Decayed",                label: "Hay Bale Decayed (rotted)",        group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_WoodenCrate",     label: "Wooden Crate (single)",            group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_WoodenCrate_3x",  label: "Wooden Crate Stack 3x",           group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_WoodenCrate_5x",  label: "Wooden Crate Stack 5x",           group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_Pallet",          label: "Wooden Pallet (flat)",             group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_BoxWooden",       label: "Wooden Box (big crate)",           group: "Hay Bales & Crates" },
  { value: "vaulting_box_small",             label: "Vaulting Box Small (gymnastics)",  group: "Hay Bales & Crates" },
  { value: "vaulting_box_large",             label: "Vaulting Box Large",               group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_WoodPile_Forest1",label: "Wood Pile Forest 1",              group: "Hay Bales & Crates" },
  { value: "StaticObj_Misc_WoodPile_Forest2",label: "Wood Pile Forest 2",              group: "Hay Bales & Crates" },

  // ─── Shipping Containers (Text Making) ───────────────────────────────────
  // Large shipping containers — great for spelling & landmarks
  { value: "StaticObj_Container_1D",         label: "Container Dark ★ BEST TEXT OBJ", group: "Shipping Containers" },
  { value: "StaticObj_Container_1C",         label: "Container Cargo (blue-grey)",     group: "Shipping Containers" },
  { value: "StaticObj_Container_1Nr",        label: "Container Numbered",              group: "Shipping Containers" },
  { value: "Land_Container_1D",              label: "Land Container Dark",             group: "Shipping Containers" },
  { value: "Land_Container_1C",              label: "Land Container Cargo",            group: "Shipping Containers" },
  { value: "ContainerBox_Yellow",            label: "Container Box Yellow (small)",    group: "Shipping Containers" },
  { value: "ContainerBox_Green",             label: "Container Box Green (small)",     group: "Shipping Containers" },
  { value: "ContainerBox_White",             label: "Container Box White (small)",     group: "Shipping Containers" },

  // ─── Elevated Roads & Bridges ─────────────────────────────────────────────
  // Source: DayZDisco Freeway Creator 2.0 — confirmed classnames
  { value: "Land_Pier_Floating_50m",         label: "Floating Pier 50m ★ FREEWAY",    group: "Roads & Bridges" },
  { value: "StaticObj_Bridge_Wood2",         label: "Wooden Bridge 20m",               group: "Roads & Bridges" },
  { value: "StaticObj_Ice_Sea_Square_50m",   label: "Ice Sea Platform 50m (Sakhal)",   group: "Roads & Bridges" },
  { value: "Land_Pier_Floating_DE",          label: "Floating Pier Section (DE)",       group: "Roads & Bridges" },
  { value: "Land_Bridge_Concrete_10m_DE",    label: "Concrete Bridge 10m",             group: "Roads & Bridges" },
  { value: "Land_Bridge_Concrete_20m_DE",    label: "Concrete Bridge 20m",             group: "Roads & Bridges" },
  { value: "Land_Bridge_Wood_10m_DE",        label: "Wooden Bridge 10m (DE)",          group: "Roads & Bridges" },
  { value: "Land_Road_Main_25m_DE",          label: "Road Section 25m (DE)",           group: "Roads & Bridges" },
  { value: "Land_Road_Main_Cor_DE",          label: "Road Corner (DE)",                group: "Roads & Bridges" },

  // ─── Text Maker Objects ───────────────────────────────────────────────────
  // Best objects for spelling visible from above (armbands, stars, speakers)
  // Source: DayZDisco Text Sign Maker 2.0 & Sign Maker 1.0
  { value: "StaticObj_Airfield_Light_PAPI1",        label: "PAPI Light ★ BEST ABOVE",         group: "Text Objects" },
  { value: "StaticObj_Airfield_Light_Strobe_01",    label: "Strobe Light (flashing)",          group: "Text Objects" },
  { value: "StaticObj_Airfield_Light_Centreline_01",label: "Centreline Light",                 group: "Text Objects" },
  { value: "ArmBandBlack",                          label: "Armband Black ★ wall text",        group: "Text Objects" },
  { value: "ArmBandYellow",                         label: "Armband Yellow",                   group: "Text Objects" },
  { value: "ArmBandRed",                            label: "Armband Red",                      group: "Text Objects" },
  { value: "ArmBandGreen",                          label: "Armband Green",                    group: "Text Objects" },
  { value: "ArmBandBlue",                           label: "Armband Blue",                     group: "Text Objects" },
  { value: "ArmBandOrange",                         label: "Armband Orange",                   group: "Text Objects" },
  { value: "ArmBandWhite",                          label: "Armband White",                    group: "Text Objects" },
  { value: "StaticObj_Container_1D",                label: "Container Dark (large letter)",    group: "Text Objects" },
  { value: "HayBale",                               label: "Hay Bale (medium letter)",         group: "Text Objects" },

  // ─── StaticObj Decor & Scenery ───────────────────────────────────────────
  // Source: Real bunker JSON files & DayZDisco Architecture Generator
  { value: "StaticObj_Roadblock_Bags_Long",    label: "Sandbag Roadblock Long",          group: "StaticObj Decor" },
  { value: "StaticObj_Roadblock_Pillbox",      label: "Sandbag Pillbox",                 group: "StaticObj Decor" },
  { value: "StaticObj_Mil_HBarrier_4m",        label: "HESCO Barrier 4m (StaticObj)",    group: "StaticObj Decor" },
  { value: "StaticObj_Mil_CamoNet_Big_nato",   label: "Camo Net Big NATO",               group: "StaticObj Decor" },
  { value: "StaticObj_Monument_War2",          label: "War Monument 2",                   group: "StaticObj Decor" },
  { value: "StaticObj_Monument_Soldiers",      label: "Soldiers Monument",               group: "StaticObj Decor" },
  { value: "StaticObj_Statue_General",         label: "General Statue",                  group: "StaticObj Decor" },
  { value: "StaticObj_Wall_IndCnc_10",         label: "Industrial Concrete Wall 10m",    group: "StaticObj Decor" },
  { value: "StaticObj_Wall_IndCnc3_2_4",       label: "Industrial Concrete Wall 3-2-4",  group: "StaticObj Decor" },
  { value: "StaticObj_Pipe_Small_Stairs",      label: "Small Pipe Stairs",               group: "StaticObj Decor" },
  { value: "StaticObj_Platform1_Stairs_Block", label: "Platform 1 Stairs Block",         group: "StaticObj Decor" },
  { value: "StaticObj_Garbage_Pile4",          label: "Garbage Pile 4",                  group: "StaticObj Decor" },
  { value: "StaticObj_Furniture_fireplace_grill", label: "Fireplace Grill",             group: "StaticObj Decor" },
  { value: "StaticObj_ammoboxes_single",       label: "Ammo Box Single (StaticObj)",     group: "StaticObj Decor" },
  { value: "StaticObj_Underground_Corridor_Main_Gate_L", label: "Underground Corridor Gate Left", group: "StaticObj Decor" },
  { value: "StaticObj_Underground_Corridor_Main_Gate_R", label: "Underground Corridor Gate Right", group: "StaticObj Decor" },
];

export const OBJECT_GROUPS = [...new Set(DAYZ_OBJECTS.map(o => o.group))];

export function formatInitC(
  objectClass: string,
  worldX: number,
  worldY: number,
  worldZ: number,
  pitch: number,
  yaw: number,
  roll: number,
  scale: number
): string {
  return `SpawnObject("${objectClass}", "${worldX.toFixed(3)} ${worldY.toFixed(3)} ${worldZ.toFixed(3)}", "${pitch.toFixed(6)} ${yaw.toFixed(6)} ${roll.toFixed(6)}", ${scale.toFixed(2)});`;
}

export function formatJSON(
  objectClass: string,
  worldX: number,
  worldY: number,
  worldZ: number,
  pitch: number,
  yaw: number,
  roll: number,
  scale: number,
  enableCEPersistency: number
): string {
  return JSON.stringify({
    name: objectClass,
    pos: [parseFloat(worldX.toFixed(6)), parseFloat(worldY.toFixed(6)), parseFloat(worldZ.toFixed(6))],
    ypr: [parseFloat(pitch.toFixed(6)), parseFloat(yaw.toFixed(6)), parseFloat(roll.toFixed(6))],
    scale: parseFloat(scale.toFixed(6)),
    enableCEPersistency,
    customString: ""
  }, null, 2);
}

export const HELPER_FUNC = `// SpawnObject helper — paste this in your init.c mission file
// Usage: SpawnObject("ClassName", "X Y Z", "Pitch Yaw Roll", Scale);
ref Object SpawnObject(string type, string pos, string ori, float scale) {
    vector vPos = pos.ToVector();
    vector vOri = ori.ToVector();
    Object obj = GetGame().CreateObjectEx(type, vPos, ECE_SETUP | ECE_UPDATEPATHGRAPH | ECE_CREATEPHYSICS);
    if (obj) {
        obj.SetOrientation(vOri);
        obj.SetScale(scale);
    }
    return obj;
}

`;
