/**
 * DankNitradoHelper — Nitrado console server setup guide.
 * Step-by-step interactive checklist for setting up a DayZ console server
 * on Nitrado. Tracks progress, shows exact file paths, and generates
 * a personalised setup summary.
 */
import { useState } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Step {
  id: string;
  phase: string;
  title: string;
  detail: string;
  path?: string;
  tip?: string;
  done: boolean;
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const INITIAL_STEPS: Omit<Step, "done">[] = [
  // Phase 1: Purchase & Setup
  { id: "p1s1", phase: "1. Purchase", title: "Buy a Nitrado DayZ console server", detail: "Go to nitrado.net → DayZ → select your platform (Xbox/PS5) and slot count.", tip: "10-slot servers are cheapest for testing. You can upgrade later." },
  { id: "p1s2", phase: "1. Purchase", title: "Wait for server provisioning", detail: "Nitrado takes 5–15 minutes to provision your server after purchase.", tip: "Check your email for the server ID." },
  { id: "p1s3", phase: "1. Purchase", title: "Note your server ID", detail: "Your server ID is shown in the Nitrado dashboard URL and in the server list.", path: "nitrado.net/en/gameserver/v2/dashboard/<SERVER_ID>" },

  // Phase 2: Basic Config
  { id: "p2s1", phase: "2. Basic Config", title: "Set server name and password", detail: "In Nitrado dashboard → Settings → General → set your server name and optional password.", tip: "Avoid special characters in the server name." },
  { id: "p2s2", phase: "2. Basic Config", title: "Set max players", detail: "Settings → General → Max Players. Match this to your slot count.", tip: "Setting higher than your slot count won't work." },
  { id: "p2s3", phase: "2. Basic Config", title: "Choose your map", detail: "Settings → General → Map. Options: ChernarusPlus, Livonia, Sakhal.", tip: "Changing map later will wipe all player data." },
  { id: "p2s4", phase: "2. Basic Config", title: "Set time zone / server time", detail: "Settings → General → Server Time. This affects in-game day/night cycle start time." },

  // Phase 3: File Manager
  { id: "p3s1", phase: "3. File Manager", title: "Open the Nitrado File Manager", detail: "Dashboard → Tools → File Browser. This is where all your mission files live.", tip: "The file browser can be slow — be patient." },
  { id: "p3s2", phase: "3. File Manager", title: "Navigate to your mission folder", detail: "Go to: /games/<id>/noftp/dayzxb_<map>/mpmissions/dayzOffline.<map>/", path: "/games/<id>/noftp/dayzxb_<map>/mpmissions/dayzOffline.<map>/" },
  { id: "p3s3", phase: "3. File Manager", title: "Upload types.xml", detail: "Upload your custom types.xml to the db/ subfolder.", path: "db/types.xml", tip: "Always keep a backup of the original types.xml before replacing." },
  { id: "p3s4", phase: "3. File Manager", title: "Upload globals.xml", detail: "Upload your globals.xml to the db/ subfolder.", path: "db/globals.xml" },
  { id: "p3s5", phase: "3. File Manager", title: "Upload cfggameplay.json (optional)", detail: "Upload cfggameplay.json to the mission root to enable gameplay flags.", path: "cfggameplay.json", tip: "Generated by DankGameplay Config tool." },
  { id: "p3s6", phase: "3. File Manager", title: "Upload cfgweather.xml (optional)", detail: "Upload cfgweather.xml to the mission root.", path: "cfgweather.xml", tip: "Generated by DankWeather Generator tool." },
  { id: "p3s7", phase: "3. File Manager", title: "Upload player spawn points (optional)", detail: "Upload cfgplayerspawnpoints.xml to the mission root.", path: "cfgplayerspawnpoints.xml", tip: "Generated by DankSpawn Maker tool." },

  // Phase 4: Teleporters (PRA)
  { id: "p4s1", phase: "4. Teleporters (PRA)", title: "Create playerRestrictedAreaFiles folder", detail: "In the mission root, create a folder named exactly: playerRestrictedAreaFiles", path: "playerRestrictedAreaFiles/", tip: "Folder name is case-sensitive." },
  { id: "p4s2", phase: "4. Teleporters (PRA)", title: "Upload PRA JSON files", detail: "Upload your .json teleport files (e.g. RestrictedAreaPadA.json) into the folder.", path: "playerRestrictedAreaFiles/RestrictedAreaPadA.json", tip: "Generated by DankTeleport Maker tool." },
  { id: "p4s3", phase: "4. Teleporters (PRA)", title: "Reference PRA files in cfggameplay.json", detail: "In cfggameplay.json, add the playerRestrictedAreaFiles array with your file names.", tip: "DankTeleport Maker generates this automatically." },

  // Phase 5: Object Spawners
  { id: "p5s1", phase: "5. Object Spawners", title: "Create env/ folder", detail: "In the mission root, create a folder named: env", path: "env/", tip: "This is where decorative object spawner JSONs go." },
  { id: "p5s2", phase: "5. Object Spawners", title: "Upload object spawner JSONs", detail: "Upload your objectSpawnersArr JSON files into the env/ folder.", path: "env/myObjects.json", tip: "Generated by DankDayz Builder tool." },
  { id: "p5s3", phase: "5. Object Spawners", title: "Reference spawner files in cfgenv", detail: "Edit cfgenvironment.xml to reference your spawner files in the objectSpawners section.", tip: "Or use the init.c approach for simpler setups." },

  // Phase 6: Restart & Test
  { id: "p6s1", phase: "6. Restart & Test", title: "Restart the server", detail: "Dashboard → Actions → Restart. Wait 2–5 minutes for the server to fully start.", tip: "Check the server log for errors after restart." },
  { id: "p6s2", phase: "6. Restart & Test", title: "Join and verify changes", detail: "Join your server and check that loot, spawns, and teleporters work as expected." },
  { id: "p6s3", phase: "6. Restart & Test", title: "Check server logs for errors", detail: "Dashboard → Tools → Log Files → script.log. Look for ERROR or WARNING lines.", path: "script.log" },
];

// ─── Component ────────────────────────────────────────────────────────────────

export default function DankNitradoHelper() {
  const [steps, setSteps] = useState<Step[]>(INITIAL_STEPS.map(s => ({ ...s, done: false })));
  const [showHow, setShowHow] = useState(false);
  const [copied, setCopied] = useState(false);

  const phases = [...new Set(steps.map(s => s.phase))];
  const doneCount = steps.filter(s => s.done).length;
  const pct = Math.round((doneCount / steps.length) * 100);

  function toggle(id: string) {
    setSteps(prev => prev.map(s => s.id === id ? { ...s, done: !s.done } : s));
  }

  function resetAll() {
    setSteps(prev => prev.map(s => ({ ...s, done: false })));
  }

  function buildSummary(): string {
    const done = steps.filter(s => s.done);
    const pending = steps.filter(s => !s.done);
    return [
      "# DankNitrado Setup Progress",
      `# ${new Date().toLocaleDateString()}`,
      "",
      `Progress: ${doneCount}/${steps.length} steps (${pct}%)`,
      "",
      `COMPLETED (${done.length}):`,
      ...done.map(s => `  ✓ [${s.phase}] ${s.title}`),
      "",
      `PENDING (${pending.length}):`,
      ...pending.map(s => `  ○ [${s.phase}] ${s.title}`),
    ].join("\n");
  }

  function copy() {
    navigator.clipboard.writeText(buildSummary()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="min-h-screen bg-[#080f09] text-[#b8d4b8] font-mono">
      <div className="border-b border-[#1a2e1a] bg-[#0c1510] px-6 py-4 flex items-center gap-3">
        <a href="/" className="text-[#5a8a5a] hover:text-[#27ae60] text-[11px]">← HOME</a>
        <span className="text-[#1a2e1a]">/</span>
        <span className="text-[11px] font-black text-[#27ae60]">🖥 DANKNITRADO HELPER</span>
        <span className="ml-auto px-2 py-0.5 rounded text-[9px] font-black bg-[#0e2010] border border-[#27ae60] text-[#27ae60]">UNIQUE TOOL</span>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-6 space-y-4">
        {/* HOW TO USE */}
        <div className="border border-[#1a2e1a] rounded overflow-hidden">
          <button onClick={() => setShowHow(h => !h)}
            className="w-full flex items-center justify-between px-4 py-2 bg-[#0c1510] text-[11px] font-black text-[#5a8a5a] hover:text-[#27ae60]">
            <span>📖 HOW TO USE</span><span>{showHow ? "▲" : "▼"}</span>
          </button>
          {showHow && (
            <div className="px-4 py-3 text-[10px] text-[#5a8a5a] space-y-1 bg-[#080f09]">
              <p>1. Work through each step in order.</p>
              <p>2. Tick steps as you complete them — progress is tracked.</p>
              <p>3. File paths shown in green are exact Nitrado paths.</p>
              <p>4. Tips in yellow give extra context for tricky steps.</p>
              <p>5. Copy your progress summary to share with your team.</p>
            </div>
          )}
        </div>

        {/* Progress bar */}
        <div className="bg-[#0a1209] border border-[#1a2e1a] rounded p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="text-[10px] font-black text-[#27ae60]">SETUP PROGRESS</div>
            <div className="flex items-center gap-3">
              <span className="text-[10px] text-[#b8d4b8] font-black">{doneCount}/{steps.length} ({pct}%)</span>
              <button onClick={resetAll} className="text-[9px] text-[#5a8a5a] hover:text-[#c0392b]">RESET</button>
              <button onClick={copy} className="text-[9px] text-[#5a8a5a] hover:text-[#27ae60]">
                {copied ? "✅ COPIED" : "COPY SUMMARY"}
              </button>
            </div>
          </div>
          <div className="w-full bg-[#0c1510] rounded h-3 overflow-hidden">
            <div className="h-full rounded transition-all duration-300"
              style={{ width: `${pct}%`, background: pct === 100 ? "#27ae60" : "#3498db" }} />
          </div>
          {pct === 100 && (
            <div className="mt-2 text-[10px] font-black text-[#27ae60]">✅ All steps complete — your server is ready!</div>
          )}
        </div>

        {/* Steps by phase */}
        {phases.map(phase => {
          const phaseSteps = steps.filter(s => s.phase === phase);
          const phaseDone = phaseSteps.filter(s => s.done).length;
          return (
            <div key={phase} className="space-y-2">
              <div className="flex items-center gap-2">
                <div className="text-[10px] font-black text-[#27ae60] tracking-widest">{phase.toUpperCase()}</div>
                <div className="text-[9px] text-[#5a8a5a]">({phaseDone}/{phaseSteps.length})</div>
                <div className="flex-1 h-px bg-[#1a2e1a]" />
              </div>
              {phaseSteps.map(step => (
                <label key={step.id}
                  className={`flex items-start gap-3 p-3 rounded border cursor-pointer transition-colors ${
                    step.done
                      ? "border-[#27ae60] bg-[#0e1a0e]"
                      : "border-[#1a2e1a] bg-[#0a1209] hover:border-[#2a4a2a]"
                  }`}>
                  <input type="checkbox" checked={step.done} onChange={() => toggle(step.id)}
                    className="mt-0.5 accent-[#27ae60]" />
                  <div className="flex-1 min-w-0">
                    <div className={`text-[11px] font-black ${step.done ? "text-[#27ae60] line-through" : "text-[#b8d4b8]"}`}>
                      {step.title}
                    </div>
                    <div className="text-[10px] text-[#5a8a5a] mt-0.5">{step.detail}</div>
                    {step.path && (
                      <div className="mt-1 text-[9px] font-mono text-[#27ae60] bg-[#050c06] px-2 py-0.5 rounded inline-block">
                        📁 {step.path}
                      </div>
                    )}
                    {step.tip && (
                      <div className="mt-1 text-[9px] text-[#d4a017] bg-[#1a1000] px-2 py-0.5 rounded">
                        💡 {step.tip}
                      </div>
                    )}
                  </div>
                </label>
              ))}
            </div>
          );
        })}
      </div>
    </div>
  );
}
