/**
 * DankServerDNA — Server identity card generator.
 * Produces a shareable "DNA card" summarising a server's config fingerprint:
 * loot economy, zombie density, time acceleration, base-building rules, etc.
 * Output: copyable text block + downloadable PNG-style ASCII card.
 */
import { useState } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface DNAConfig {
  serverName: string;
  map: string;
  maxPlayers: number;
  // Economy
  lootMultiplier: number;
  zombieMultiplier: number;
  animalMultiplier: number;
  // Time
  dayDuration: number;   // real minutes per in-game day
  nightDuration: number;
  timeAccel: number;
  // Gameplay
  crosshair: boolean;
  stamina: boolean;
  baseBuildingAnywhere: boolean;
  safezoneEnabled: boolean;
  pvpEnabled: boolean;
  // Extras
  modList: string;
  discordUrl: string;
  notes: string;
}

const DEFAULT: DNAConfig = {
  serverName: "My DayZ Server",
  map: "ChernarusPlus",
  maxPlayers: 60,
  lootMultiplier: 1.0,
  zombieMultiplier: 1.0,
  animalMultiplier: 1.0,
  dayDuration: 60,
  nightDuration: 15,
  timeAccel: 6,
  crosshair: false,
  stamina: true,
  baseBuildingAnywhere: false,
  safezoneEnabled: false,
  pvpEnabled: true,
  modList: "",
  discordUrl: "",
  notes: "",
};

const MAPS = ["ChernarusPlus", "Livonia", "Sakhal", "Namalsk", "Deer Isle", "Takistan", "Other"];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ratingBar(value: number, max: number, char = "█"): string {
  const filled = Math.round((value / max) * 10);
  return char.repeat(Math.min(filled, 10)) + "░".repeat(Math.max(0, 10 - filled));
}

function lootLabel(m: number) {
  if (m <= 0.5) return "SCARCE";
  if (m <= 0.8) return "LOW";
  if (m <= 1.2) return "VANILLA";
  if (m <= 2.0) return "HIGH";
  return "EXTREME";
}

function zombieLabel(m: number) {
  if (m <= 0.3) return "MINIMAL";
  if (m <= 0.7) return "LOW";
  if (m <= 1.2) return "VANILLA";
  if (m <= 2.0) return "HIGH";
  return "HORDE";
}

function buildCard(cfg: DNAConfig): string {
  const mods = cfg.modList.trim() ? cfg.modList.split(",").map(s => s.trim()).filter(Boolean) : [];
  const flags: string[] = [];
  if (!cfg.crosshair) flags.push("NO CROSSHAIR");
  if (!cfg.stamina) flags.push("NO STAMINA");
  if (cfg.baseBuildingAnywhere) flags.push("BUILD ANYWHERE");
  if (cfg.safezoneEnabled) flags.push("SAFEZONE");
  if (!cfg.pvpEnabled) flags.push("PVE");
  if (cfg.pvpEnabled) flags.push("PVP");

  const lines: string[] = [
    "╔══════════════════════════════════════════════════════╗",
    `║  🧬 DANK'S DAYZ STUDIO — SERVER DNA                  ║`,
    "╠══════════════════════════════════════════════════════╣",
    `║  SERVER : ${cfg.serverName.padEnd(43)}║`,
    `║  MAP    : ${cfg.map.padEnd(43)}║`,
    `║  SLOTS  : ${String(cfg.maxPlayers).padEnd(43)}║`,
    "╠══════════════════════════════════════════════════════╣",
    `║  LOOT   : ${ratingBar(cfg.lootMultiplier, 3)} ${lootMultiplier(cfg.lootMultiplier).padEnd(32)}║`,
    `║  ZOMBIES: ${ratingBar(cfg.zombieMultiplier, 3)} ${zombieLabel(cfg.zombieMultiplier).padEnd(32)}║`,
    `║  ANIMALS: ${ratingBar(cfg.animalMultiplier, 3)} ${lootLabel(cfg.animalMultiplier).padEnd(32)}║`,
    "╠══════════════════════════════════════════════════════╣",
    `║  DAY    : ${String(cfg.dayDuration + "min").padEnd(9)}  NIGHT: ${String(cfg.nightDuration + "min").padEnd(9)}  ACCEL: ${String(cfg.timeAccel + "x").padEnd(7)}║`,
    "╠══════════════════════════════════════════════════════╣",
    `║  FLAGS  : ${flags.join(" · ").substring(0, 43).padEnd(43)}║`,
    ...(mods.length ? [
      "╠══════════════════════════════════════════════════════╣",
      `║  MODS   : ${mods.slice(0, 3).join(", ").substring(0, 43).padEnd(43)}║`,
      ...(mods.length > 3 ? [`║           ${("+" + (mods.length - 3) + " more").padEnd(43)}║`] : []),
    ] : []),
    ...(cfg.discordUrl ? [
      "╠══════════════════════════════════════════════════════╣",
      `║  DISCORD: ${cfg.discordUrl.substring(0, 43).padEnd(43)}║`,
    ] : []),
    ...(cfg.notes ? [
      "╠══════════════════════════════════════════════════════╣",
      `║  NOTES  : ${cfg.notes.substring(0, 43).padEnd(43)}║`,
    ] : []),
    "╚══════════════════════════════════════════════════════╝",
    `  Generated by DankDayz Tools · ${new Date().toLocaleDateString()}`,
  ];
  return lines.join("\n");
}

function lootMultiplier(m: number) { return lootLabel(m); }

// ─── Component ────────────────────────────────────────────────────────────────

export default function DankServerDNA() {
  const [cfg, setCfg] = useState<DNAConfig>(DEFAULT);
  const [copied, setCopied] = useState(false);
  const [showHow, setShowHow] = useState(false);

  const card = buildCard(cfg);

  function set<K extends keyof DNAConfig>(key: K, value: DNAConfig[K]) {
    setCfg(prev => ({ ...prev, [key]: value }));
  }

  function copy() {
    navigator.clipboard.writeText(card).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function download() {
    const blob = new Blob([card], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${cfg.serverName.replace(/\s+/g, "_")}_DNA.txt`;
    a.click();
  }

  const inputCls = "w-full bg-[#0a1209] border border-[#1a2e1a] text-[#b8d4b8] text-[11px] px-2 py-1.5 rounded focus:outline-none focus:border-[#27ae60]";
  const labelCls = "text-[10px] text-[#5a8a5a] font-bold uppercase tracking-wider mb-1 block";
  const sectionCls = "bg-[#0a1209] border border-[#1a2e1a] rounded p-4 space-y-3";

  return (
    <div className="min-h-screen bg-[#080f09] text-[#b8d4b8] font-mono">
      {/* Header */}
      <div className="border-b border-[#1a2e1a] bg-[#0c1510] px-6 py-4 flex items-center gap-3">
        <a href="/" className="text-[#5a8a5a] hover:text-[#27ae60] text-[11px]">← HOME</a>
        <span className="text-[#1a2e1a]">/</span>
        <span className="text-[11px] font-black text-[#27ae60]">🧬 DANKSERVER DNA</span>
        <span className="ml-auto px-2 py-0.5 rounded text-[9px] font-black bg-[#0e2010] border border-[#27ae60] text-[#27ae60]">UNIQUE TOOL</span>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: inputs */}
        <div className="space-y-4">
          {/* HOW TO USE */}
          <div className="border border-[#1a2e1a] rounded overflow-hidden">
            <button
              onClick={() => setShowHow(h => !h)}
              className="w-full flex items-center justify-between px-4 py-2 bg-[#0c1510] text-[11px] font-black text-[#5a8a5a] hover:text-[#27ae60]"
            >
              <span>📖 HOW TO USE</span>
              <span>{showHow ? "▲" : "▼"}</span>
            </button>
            {showHow && (
              <div className="px-4 py-3 text-[10px] text-[#5a8a5a] space-y-1 bg-[#080f09]">
                <p>1. Fill in your server details below.</p>
                <p>2. The DNA card updates live in the preview panel.</p>
                <p>3. Copy or download the card to share on Discord, Reddit, or your server listing.</p>
                <p>4. The card summarises loot, zombie density, time settings and gameplay flags in a compact ASCII format.</p>
              </div>
            )}
          </div>

          {/* Identity */}
          <div className={sectionCls}>
            <div className="text-[10px] font-black text-[#27ae60] tracking-widest mb-2">IDENTITY</div>
            <div>
              <label className={labelCls}>Server Name</label>
              <input className={inputCls} value={cfg.serverName} onChange={e => set("serverName", e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className={labelCls}>Map</label>
                <select className={inputCls} value={cfg.map} onChange={e => set("map", e.target.value)}>
                  {MAPS.map(m => <option key={m}>{m}</option>)}
                </select>
              </div>
              <div>
                <label className={labelCls}>Max Players</label>
                <input type="number" className={inputCls} value={cfg.maxPlayers} min={1} max={200}
                  onChange={e => set("maxPlayers", Number(e.target.value))} />
              </div>
            </div>
          </div>

          {/* Economy */}
          <div className={sectionCls}>
            <div className="text-[10px] font-black text-[#27ae60] tracking-widest mb-2">ECONOMY MULTIPLIERS</div>
            {(["lootMultiplier", "zombieMultiplier", "animalMultiplier"] as const).map(key => (
              <div key={key}>
                <label className={labelCls}>{key.replace("Multiplier", "").toUpperCase()} ×{cfg[key].toFixed(1)}</label>
                <input type="range" min={0.1} max={5} step={0.1} value={cfg[key]}
                  onChange={e => set(key, Number(e.target.value))}
                  className="w-full accent-[#27ae60]" />
              </div>
            ))}
          </div>

          {/* Time */}
          <div className={sectionCls}>
            <div className="text-[10px] font-black text-[#27ae60] tracking-widest mb-2">TIME SETTINGS</div>
            <div className="grid grid-cols-3 gap-3">
              <div>
                <label className={labelCls}>Day (min)</label>
                <input type="number" className={inputCls} value={cfg.dayDuration} min={1} max={240}
                  onChange={e => set("dayDuration", Number(e.target.value))} />
              </div>
              <div>
                <label className={labelCls}>Night (min)</label>
                <input type="number" className={inputCls} value={cfg.nightDuration} min={1} max={120}
                  onChange={e => set("nightDuration", Number(e.target.value))} />
              </div>
              <div>
                <label className={labelCls}>Accel ×</label>
                <input type="number" className={inputCls} value={cfg.timeAccel} min={1} max={24}
                  onChange={e => set("timeAccel", Number(e.target.value))} />
              </div>
            </div>
          </div>

          {/* Flags */}
          <div className={sectionCls}>
            <div className="text-[10px] font-black text-[#27ae60] tracking-widest mb-2">GAMEPLAY FLAGS</div>
            <div className="grid grid-cols-2 gap-2">
              {(["crosshair", "stamina", "baseBuildingAnywhere", "safezoneEnabled", "pvpEnabled"] as const).map(key => (
                <label key={key} className="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" checked={cfg[key] as boolean}
                    onChange={e => set(key, e.target.checked)}
                    className="accent-[#27ae60]" />
                  <span className="text-[10px] text-[#b8d4b8]">{key.replace(/([A-Z])/g, " $1").toUpperCase()}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Extras */}
          <div className={sectionCls}>
            <div className="text-[10px] font-black text-[#27ae60] tracking-widest mb-2">EXTRAS</div>
            <div>
              <label className={labelCls}>Mods (comma-separated)</label>
              <input className={inputCls} value={cfg.modList} placeholder="CF, VPPMap, DayZ-Expansion..."
                onChange={e => set("modList", e.target.value)} />
            </div>
            <div>
              <label className={labelCls}>Discord URL</label>
              <input className={inputCls} value={cfg.discordUrl} placeholder="discord.gg/..."
                onChange={e => set("discordUrl", e.target.value)} />
            </div>
            <div>
              <label className={labelCls}>Notes</label>
              <input className={inputCls} value={cfg.notes} placeholder="Wipe every 2 weeks..."
                onChange={e => set("notes", e.target.value)} />
            </div>
          </div>
        </div>

        {/* Right: preview */}
        <div className="space-y-3">
          <div className="text-[10px] font-black text-[#27ae60] tracking-widest">LIVE PREVIEW</div>
          <pre className="bg-[#050c06] border border-[#1a2e1a] rounded p-4 text-[10px] text-[#b8d4b8] overflow-x-auto whitespace-pre leading-relaxed">
            {card}
          </pre>
          <div className="flex gap-2">
            <button onClick={copy}
              className="flex-1 py-2 rounded text-[11px] font-black border border-[#27ae60] text-[#27ae60] hover:bg-[#0e2010] transition-colors">
              {copied ? "✅ COPIED" : "📋 COPY CARD"}
            </button>
            <button onClick={download}
              className="flex-1 py-2 rounded text-[11px] font-black border border-[#5a8a5a] text-[#5a8a5a] hover:bg-[#0a1209] transition-colors">
              ⬇ DOWNLOAD .TXT
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
